### ISSUE TITLE
Updates to All other xDSCResources Readme

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/DscResources#100]
As referenced in issue https://github.com/PowerShell/xSQLServer/issues/25 it would make sense for all the Repositories related to DSC Resources to detail a rough guideline to the release schedule for the resources in the Readme file

**Comment by mgreenegit** [comment]
Can you share an example from another open source project?  I'm mostly interested in how to represent community contribution.

**Comment by KarolKaczmarek** [comment]
We try not to have strict release schedule in favor of flexibility, as it depends on what changes we've taken in for specific resources. We had few cases where we fixed important bug and released the same day. If there's no critical changes, we usually tend to release modules in bulk every few weeks, usually every 4-6 weeks which also depends on overall number of changes we had. I'll add some info on that to DscResources readme.

**Comment by kilasuit** [comment]
@mgreenegit the OfficeDevPnP team do a monthly release and a community call on the cross repository additions

A singular Monthly release of the full DSCResources Repo would be great but a Community call where the latest updates cross all Repos could be benefical as it allows an open QA.

But its just a thoughtful suggestion of what I've seen work well elsewhere

**Comment by tysonjhayes** [comment]
:+1: on the community call, I've suggested it before and think it would be neat to be able to dive into some of what the community is seeing and needing.

**Comment by kwirkykat** [comment]
@kilasuit @tysonjhayes @mgreenegit 

[Community Agenda](https://github.com/PowerShell/DscResources/blob/master/CommunityAgenda.md) has been added to announce release dates before they actually happen. I will also post them on [my Twitter](https://twitter.com/katiedsc) if you would like more of a push notification.

Though the release cadence will stay pretty flexible, you will can now at least be warned ahead of time before we do a major release.

Also, we will be doing a community call this Thursday which we just announced [here](https://blogs.msdn.microsoft.com/powershell/2016/06/27/dsc-resource-kit-community-call/).

**Comment by kilasuit** [comment]
Again this is Awesome news - thanks for getting this setup and I'll be sure to share about the community call this as widely as possible :-)
