### ISSUE TITLE
The Win32_Product WMI class should not be used

### ISSUE THREAD

**Issue by J0F3** [PowerShell/DscResources#108]
A lot of the resources are using the Win32_Product WMI class to detect the current installation state in the Set or Test functions. Especially the System Center and the xSQLServer resource are making use of it. Even Mircosoft self does not recommend the usage of the class. So these queries should be replaced by another detection logic.

> If you have an application that makes use of the above class, please contact the vendor to get an updated version that does not use this class.

https://support.microsoft.com/en-nz/kb/974524

**Comment by Zuldan** [comment]
More proof from Microsoft that the use of Win32_Product is bad.

https://blogs.technet.microsoft.com/askds/2012/04/19/how-to-not-use-win32_product-in-group-policy-filtering/

**Comment by johlju** [comment]
Either we create an issue in DscResource.Tests so we can make a test of this, at least a test that warns about it (non-blocking).  Or. we add an issue to each of these repos that after a search in the PowerShell organization have this referencing in code files. I suggest the later.

- PSDscResources
- xPSDesiredStateConfiguration
- xSCOM
- xSCSPF
- xSCVMM
- xSCSR
- xSCSMA
- xSCDPM
- ~~xAzurePack~~ (already in https://github.com/PowerShell/xAzurePack/issues/8)
- xExchange

**Comment by johlju** [comment]
Issues has been opened in all repositories that have a reference to Win32_Product WMI class. This is now being tracked in each repo. Closing this issue at this time.

**Comment by danielboth** [comment]
@johlju, please note that the Win32reg_AddRemovePrograms is only available when the system is running the SCCM Client. On systems managed by DSC that might (should?) not be the case, so if possible we should not use any of those classes.

**Comment by johlju** [comment]
@danielboth Ah, I see. I guess each repo then either has to continue using Win32_Product or find another way of getting the same information (if there is any). 🙂

**Comment by J0F3** [comment]
@johlju @danielboth Win32_Product WMI Class can really not be consider as a solution! It is slow, will fill up the eventlog with MsiInstaller events and may trigger a self repair of installed MSI packages. Triggering that every 15min (when it is in the Get or Tests function of the DSC Resource) is not really 'nice'. :-)
That was also the main reason why I could not use these resources in the past for productive setups. Because on a production system you don't can to risk that every 15min your msi packages will make a self repair.

But Win32reg_AddRemovePrograms is neither, that's correct. The MS article is misleading here. 

I would just use the uninstall registry key instead. Like:
`(Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*,
 HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Where-Object {![string]::IsNullOrWhiteSpace($_.DisplayName)} | Sort-Object DisplayName -Unique).DisplayName`

Or to get the product IDs:
`(Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*,
HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*
)| select PSChildName`

It is fast, independent and would even work on PowerShell 6 ;-)

Alternatively `Get-Package -ProviderName msi` can be used but this works only on PS 5.1, I think.

**Comment by johlju** [comment]
@J0F3 Thanks a lot for that! It will help contributors to resolve this I think.
