### ISSUE TITLE
xDatabase resource does not apply 'Select' or 'Execute' permissions appropriately

### ISSUE THREAD

**Issue by dpatelapx** [PowerShell/DscResources#113]
We are using xDatabase DSC resource for our database deployments. However, when we add a new object (let's say a function) and assign 'Select' and/or 'Execute' permission on it associated to a DB login the object gets deployed on the target server, however, the permissions doesn't get applied.

Is this a known issue ?

**Comment by kwirkykat** [comment]
@dpatelapx If this is still a problem, can you please open a new issue in the [xDatabase](https://github.com/PowerShell/xDatabase) repository?
