### ISSUE TITLE
Text files for all resources should end with a new line

### ISSUE THREAD

**Issue by KarolKaczmarek** [PowerShell/DscResources#114]
Per our style guidelines:
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md
all text files should end with a new line.
Once it's done, we should enable our test checking this to run also in appveyor test passes (see https://github.com/PowerShell/DscResource.Tests/pull/36 )

**Comment by mbreakey3** [comment]
So, basically, I need to go through all of the files in the resource kit and make sure there's a newline at the end?

**Comment by KarolKaczmarek** [comment]
No need to go through all of them. Since we have tests for this (Meta.tests.ps1), just run this for all our repos and it will tell you what files need to be fixed. 

This may help: https://github.com/PowerShell/DscResource.Tests/blob/master/TestRunner.psm1 
You can also use -TestName parameter to Invoke-Pester in order to just run specific test.

**Comment by johlju** [comment]
Closing this as solved as per previous comment. Please reopen or comment if this was closed in error.
