### ISSUE TITLE
Unit test template seems to encourage the use InModuleScope

### ISSUE THREAD

**Issue by narrieta** [PowerShell/DscResources#115]
In the unit test template, it seems like we are encouraging people to wrap all the Describes within an InModuleScope scope.

InModuleScope should be restricted to those sections of the code that actually want to reach into the private implementation of the module. It is not needed to reach into the Get/Test/Set functions, which are exported from the module.

Take for example the unit tests for xFirewall: 

   InModuleScope $DSCResourceName {
        $FirewallRuleName = ...
        $FirewallRule = ...
        $Properties = ...
        $FirewallRules = ...

        Describe 'MSFT_xFirewall\Get-TargetResource' {
            Context 'Absent should return correctly' {

Those assignments may end up corrupting the state of the module if the variable names happen to collide with existing module variables.

**Comment by KarolKaczmarek** [comment]
@PlagueHO What was the original intent of using InModuleScope?

**Comment by PlagueHO** [comment]
@narrieta - excellent point. @KarolKaczmarek  - the intent was to allow non-exported cmdlets to be tested, but as @narrieta points out this should not include the exported *-TargetResource cmdlets.

The template should be adjusted accordingly.

I'll submit a PR with this change as well as the other changes that @narrieta pointed out and we can go from there. Would that work for you gents?

**Comment by KarolKaczmarek** [comment]
sure, thanks!
