### ISSUE TITLE
Clarify use of Describe blocks in the unit test template

### ISSUE THREAD

**Issue by narrieta** [PowerShell/DscResources#116]
The unit test template is organized as 1 Describe block for each of Get/Test/Set:

        Describe "$($Global:DSCResourceName)\Get-TargetResource" {
        }
        Describe "$($Global:DSCResourceName)\Test-TargetResource" {
        }
        Describe "$($Global:DSCResourceName)\Set-TargetResource" {
        }

We should clarify whether this pattern is a requirement for unit tests or just a sample. Hopefully it is the later, since there may be other ways to organize the tests (e.g. per-scenario, rather than per-function) .

**Comment by PlagueHO** [comment]
@narrieta - it is definitely the latter. It is the most common pattern that I've seen, but by no means the only one or a restriction.

I'll clarify this in a PR.

Thanks! :+1:

**Comment by narrieta** [comment]
@PlagueHO - thank you much for your prompt response!

**Comment by PlagueHO** [comment]
@narrieta - no problem! Thanks for pointing out the issues :smile:
