### ISSUE TITLE
Clarify comment wrt Load Mock in unit test template

### ISSUE THREAD

**Issue by narrieta** [PowerShell/DscResources#117]
The unit test template includes this comment:

        #region Pester Test Initialization
        # TODO: Optopnal Load Mock for use in Pester tests here...
        #endregion

        Describe "$($Global:DSCResourceName)\Get-TargetResource" {
            ...
        }

I think this comment needs some clarification. Are we asking people to define all their mocks at this place? Some mocks are better defined at Describe/Context/It scope.

**Comment by PlagueHO** [comment]
@narrieta - good point. This should be clarified.

The actual intent of this area are actually:
A place to put variables used by all tests and mocks - not usually the mocks themselves.

Although some Mocks may be declared here if they are to be applied to all contexts/describes.

A good example of this can be found here: https://github.com/PlagueHO/xActiveDirectory/blob/dev/Tests/Unit/MSFT_xADUser.Tests.ps1

I'll make some changes to this and submit a PR.
