### ISSUE TITLE
Add a new StyleGuidline on layout of Hashtables/Objects and Arrays

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#120]
Currently there is no StyleGuideline on the recommended layout of Hashtables and Arrays.
Could we add one?

I can submit a PR if agreeable.

e.g. Which should be the recommended style:
- Option 1:
```powershell
data ParameterList
{
    @( 
        @{ Name = 'Name'; Source = '$FirewallRule.Name'; Type = 'String' },
        @{ Name = 'DisplayName'; Source = '$FirewallRule.DisplayName'; Type = 'String' },
    )
}
```
- Option 2:
```powershell
data ParameterList
{
    @( 
        @{
               Name = 'Name'
               Source = '$FirewallRule.Name'
               Type = 'String'
           },
          @{
               Name = 'DisplayName'
               Source = '$FirewallRule.DisplayName'
               Type = 'String'
           }
     )
}
```
- Option 3: Are there any other options?

I personally prefer Option 2 as Option 1 often causes lines to go over the 100 char limit.

@tysonjhayes, @iainbrighton, @TravisEz13?

**Comment by tysonjhayes** [comment]
Option 2. Is my vote. Keeps it under the 100 character limit, and keeps it pretty tidy looking (to me, which is totaly a subjective opinion).

**Comment by SNikalaichyk** [comment]
I'd prefer not to enforce this.
**Option 1** is easier to read and follow when there are a lot of items.
**Option 2** is okay when there aren't many items.

**Comment by KarolKaczmarek** [comment]
Agree with @SNikalaichyk 
There's nothing wrong with option 1 if it isn't too long (and we have another rule to mandate that: https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#each-line-should-have-less-than-100-characters) 

Mandating option 2 for hashtables with two items is a bit too strict imo, so I wouldn't enforce it.

**Comment by PlagueHO** [comment]
Seems like this one might not be a good idea to enforce - as long as the 100 char limit is being met we're OK. I'll leave it open for a couple more days and if no further comment I'll close it. Is that OK with everyone?

**Comment by TravisEz13** [comment]
I think one thing we might want to suggest here is that one declaration should be consistent at least with itself.

But, no project wide you must use a particular declaration style.

**Comment by PlagueHO** [comment]
So the style guideline should simply be: All elements in an Array/Hashtable should follow a consistent layout/pattern.

Sounds OK to me. I'll put a PR through next week.
