### ISSUE TITLE
Add a StyleGuideline for Params block format

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#121]
At the moment there is a lot of inconsistencies with the params block formats.
E.g.
- Option 1:
```powershell
param (
  [string] $Name
)
```
 - Option 2:
```powershell
param (
  [string]
  $Name
)
```

Option 1 looks to be the most common and is also a seems the most logical as declaring variables is usually done with:
```powershell
[string] $Name
```

Param decorations should always be on their own lines.

@TysonJHayes, @IainBrighton, @TravisEz13?

**Comment by SNikalaichyk** [comment]
Hello all,

As a contributor, I'd prefer **Option 2** because it's arguably more readable in the following cases:
1. There are other attributes (e.g., `[Parameter()]`, `[ValidateNotNullOrEmpty()]` etc.).
2. There are a lot of parameters with different types.
3. There are parameters with long type names (e.g., `[System.Security.AccessControl.FileSystemSecurity]`).

The main advantage of **Option 2** is that parameter names always start at the very same position making the code easier to follow.
Please see the examples below:

* **Option 1.** The `$Path` parameter name starts at column 18 while the `$Acl` parameter name starts at column 34.
```powershell
    param
    (
        [Parameter(Mandatory = $true)]
        [ValidateScript({Test-Path -Path $_})]
        [String] $Path,

        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [System.Security.AccessControl.FileSystemSecurity] $Acl
    )
```
vs.
* **Option 2.** Both the `$Path` and the `$Acl` parameter names start at column 9.
```powershell
    param
    (
        [Parameter(Mandatory = $true)]
        [ValidateScript({Test-Path -Path $_})]
        [String]
        $Path,

        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [System.Security.AccessControl.FileSystemSecurity]
        $Acl
    )
```

**Comment by tysonjhayes** [comment]
Personally I vote for Option 1, it's the most common, and most logical.

**Comment by iainbrighton** [comment]
I vote for Option 1 too as it's closer to what I tend to use. This is typical of what I have settled on:
```powershell
param
(
    [Parameter(Mandatory)] [ValidateScript({Test-Path -Path $_})]
    [String] $Path,

    [Parameter(Mandatory)] [ValidateNotNullOrEmpty()]
    [System.Security.AccessControl.FileSystemSecurity] $Acl
)
```
I don't bother with `Mandatory = $true` as DSC only runs on v4+

**Comment by Justin-DynamicD** [comment]
To be honest, this detail of style guideline feels to rigid to me. I mean, heck,  I don't do either of these options,  instead putting a parameter per line which, for me, is the easiest to read:

`
param (
    [Parameter(Mandatory=$true)][String][ValidateSet("Root","Issue")]$Role,   
    [Parameter(Mandatory=$true)][String]$CAName,
    [Parameter(Mandatory=$false)][String]$DomainDN,
    [Parameter(Mandatory=$false)][String]$FQDN = "pki.contoso.com"
    )
`
For me it is the fastest way to see "ok I have 4 parameters, 2 are mandatory" as well as making it a little more obvious and clear where that trailing coma goes ;).  My point isn't that my method "is best", rather that the param block is inherently flexible and I don't see why we should be enforcing a specific format for this part, especially for such a small part of the codebase.  I think should stay more general like "when to indent" and "back ticks are evil, just stop that".

**Comment by johlju** [comment]
I'm happy with either way, as long as it is consistent. I normally code using option 1, but for DSC I used option 2 because that is what xDSCResourceDesigner give me, so I stuck with that as I thought that was the guideline. 

And as a side not, is there a guideline when to use or not to use default parameters.

**Comment by KarolKaczmarek** [comment]
My preference is option 1 as well, but agree with @johlju that either way is fine as long as it's consistent across all resources

**Comment by SNikalaichyk** [comment]
Is the whitespace required between `[Type] $Name` in Option 1?

**Comment by KarolKaczmarek** [comment]
On a side note - in the guideline for this we should have example with not only type, but also other attributes (as pointed by @SNikalaichyk )

**Comment by PlagueHO** [comment]
@KarolKaczmarek , I agree, there does need to be guidance on the attributes.  @johlju raises a good point though -if xDSCResourceDesigner outputs parameters with Option 2 formatting then either xDSCResourceDesigner should be changed to output option 1 format or we go with Option 2. Seems like a bad idea to have a style guideline that goes against xDSCResourceDesigner?

**Comment by PlagueHO** [comment]
@TravisEz13 - care to weigh in on this one?

Perhaps in the absence of a clear decision on which format is best we go with the "Make it match the format of any existing resources in the module?"

**Comment by TravisEz13** [comment]
I voted with @KarolKaczmarek ' agreement  "that either way is fine as long as it's consistent across all resources"

**Comment by KarolKaczmarek** [comment]
It seems most people suggested option 1, we just need to file an issue and fix xDSCResourceDesigner to generate proper formatting.

**Comment by PlagueHO** [comment]
Ok, cool. Thanks for that. I'll get the changes under way (including raising an issue on xDscREsourceDesigner).

**Comment by KarolKaczmarek** [comment]
Fixed with https://github.com/PowerShell/DscResources/pull/126 
Thanks!
