### ISSUE TITLE
Problem running pester in specific unit/integration folder

### ISSUE THREAD

**Issue by mbreakey3** [PowerShell/DscResources#122]
Right now it seems that you need to be in the root Test folder in order to invoke-pester. We want to be able to invoke-pester from the sub folders as well.

**Comment by PlagueHO** [comment]
Hi @mbreakey3 - this should have been fixed with this PR: https://github.com/PowerShell/DscResources/pull/85

However, this was only with DSC Resources that updated to use this new Test Template. If a DSC Resource wasn't updated with it then it will not work when run from a subfolder.

Are you able to confirm this?

**Comment by mbreakey3** [comment]
Ah, yes. This was happening specifically with xWebAdministration do you know if that was one of the resources that wan't updated?

**Comment by KarolKaczmarek** [comment]
Yes, the xWebAdministration contains previous version of the template https://github.com/PowerShell/xWebAdministration/blob/dev/Tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1#L5 , so you may need to add there changes from #85

**Comment by mbreakey3** [comment]
Okay, should I move this issue to xWebAdmin then?

**Comment by KarolKaczmarek** [comment]
sure, and we can close this one.
I just checked that xNetworking is using updated template, but if you would see any other modules which use the old one, please update them as well.

**Comment by KarolKaczmarek** [comment]
I created an issue to discuss adding versioning to test templates which would help in situations like this.
https://github.com/PowerShell/DscResources/issues/124 Please let me know your opinions
