### ISSUE TITLE
Cannot make the module work through proxy

### ISSUE THREAD

**Issue by riponbanik** [PowerShell/DscResources#131]
We use proxy in our environment and the module fails when downloading packages from internet.

**Comment by PlagueHO** [comment]
@riponbanik - Which module are you referring to? If this is a specific resource module you're referring to, could you please raise this against the specific repository (e.g. https://github.com/PowerShell/xNetworking).

**Comment by riponbanik** [comment]
Hi @PlagueHO , thanks for looking into it, it is about xRemoteFile Resource, which I raised with puppet before - https://github.com/puppetlabs/puppetlabs-dsc/issues/160#issuecomment-163691226

**Comment by PlagueHO** [comment]
@riponbanik - ah cool! I see it there. I'll take a look and see what can be done. Could we close this issue as it is now open on the other repo?
Thanks!

**Comment by PlagueHO** [comment]
@riponbanik - I've submitted a PR to resolve this issue here https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/123.

In the meantime, can we close this issue in this repo (leaving the one in xPSDesiredStateConfiguration open)?

**Comment by PlagueHO** [comment]
@TravisEz13  - I think this issue should be closed (it's in the xPSDesiredStateConfiguration repo anyway).

**Comment by kwirkykat** [comment]
PowerShell/xPSDesiredStateConfiguration#122 has been closed.
