### ISSUE TITLE
Integration Test Templates require AppVeyor WMF 5 build machines

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#133]
If a DSC Resourse module includes integration tests that are built using the standard Integration test templates then AppVeyor.yml must be configured with `os: WMF 5` otherwise the Integration tests will fail because the Resource module will not be able to be located.

This error (or similar) will occur:

```
The PowerShell DSC resource xauditpolicy does not exist at the PowerShell module path nor is it registered as a WMI DSC resource. + CategoryInfo : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException + FullyQualifiedErrorId : DscResourceNotFound + PSComputerName : localhost
```

Suggest that information regarding this is added to the [Integration Test Template file](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/integration_template.ps1) in the comments and/or the [TestGuidelines.md](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) document.

**Comment by tysonjhayes** [comment]
My question to this would be is the behavior we want? Personally I'm still targeting WMF4.0 on most of my machines. With no plans at this point of rolling forward to WMF5 anytime soon (though I'd love to just not on the roadmap...) If the default template is WMF5 are we dropping support of WMF4 by default?

**Comment by KarolKaczmarek** [comment]
I agree with @tysonjhayes , we should make the template compatible with both WMF 4 and 5. There's still many repos which run tests on WMF4 and even after switching them to WMF 5 by default, we may want to introduce test matrix to run on multiple SKUs.

**Comment by PlagueHO** [comment]
You're both 100% correct. I did some investigation a while back on how this might be done. I'll dig it out and see if I can make it work. I think it will require a minor update to the integration configuration template.

**Comment by tysonjhayes** [comment]
Could you help me understand the dependency as it is currently? I didn't see a command or anything that was 5 specific. But I might have just missed it.

**Comment by PlagueHO** [comment]
The problem seems to be that DSC in WMF 4.0 seems to ignore the $ENV:PSModule path setting. So when the LCM tries to apply the configuration during the apply phase it can't find the DSV module.

The resolution could be to inject the module path into the integration config file at the time the tests are run.

I recall that I  experimented with this a few months back but didn't fully investigate it if put a wiring solution together.

**Comment by PlagueHO** [comment]
Here is an example of the error when the machine running the Integration tests isn't WMF5:
```
The PowerShell DSC resource xauditpolicy does not exist at the PowerShell module path nor is it registered as a WMI DSC resource. 
+ CategoryInfo : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException 
+ FullyQualifiedErrorId : DscResourceNotFound 
+ PSComputerName : localhost
```
Taken from [this comment](https://github.com/PowerShell/DscResources/issues/86#issuecomment-219352604) by @athaynes

This week is a bit crazy, but if no one else gets to this by the weekend I'll try and come up with a solution over the weekend.

**Comment by PlagueHO** [comment]
I haven't made any progress on this one. Has anyone else had any thoughts on this?

**Comment by KarolKaczmarek** [comment]
Perhaps template should be updating user/machine environment variable instead and then do the cleanup? I believe DSC would pick that one up also in WMF4.

**Comment by johlju** [comment]
@PlagueHO is this still an issue? Maybe it is resolved? I see this comment in TestHelper https://github.com/PowerShell/DscResource.Tests/blob/62cca028018fcab83df7108f11e4402f5f8e8267/TestHelper.psm1#L360-L363

**Comment by PlagueHO** [comment]
This is resolved now as the default AppVeyor machine has long moved on. WMF 5 is now default on AppVeyor so I'll close this.
