### ISSUE TITLE
New resource module HybridRunbookWorker

### ISSUE THREAD

**Issue by bgelens** [PowerShell/DscResources#134]
Used to onboard Hybrid Runbook Workers in Azure Automation and manage WorkerGroup assignment.
MOF based resource as minimum requirement for AA hybrid workers is PSv4
https://github.com/bgelens/HybridRunbookWorker

**Comment by kwirkykat** [comment]
@bgelens 
I just posted a [new guide](https://github.com/PowerShell/DscResources/issues/158) on submitting new resource modules for review.

Please open a PR to an empty branch.
Also you will need an Examples folder that contains script files of the examples you provide in your README.

Then the README should have a description of the resource and its parameters.

You can refer to the [xPSDesiredStateConfiguration respository](https://github.com/PowerShell/xPSDesiredStateConfiguration) to see the Examples folder and README.

**Comment by BrianFarnhill** [comment]
@kwirkykat I think you copy/pasted to wrong link for the guide :) 

Should be https://github.com/PowerShell/DscResources/blob/master/HighQualityModuleGuidelines.md

**Comment by kwirkykat** [comment]
@BrianFarnhill Oops. Yes it is the wrong link.
It should be https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md

Will edit the comment above.

**Comment by bgelens** [comment]
Hi @kwirkykat, I'll look into it when I have some time. TBC

**Comment by bgelens** [comment]
Created new GH repo to comply with __Dsc Naming convention and module structure
https://github.com/bgelens/HybridRunbookWorkerDsc

**Comment by bgelens** [comment]
@kwirkykat I added a new resource, tests and think I comply. Could you have a look before I do a PR to the Master branch?
https://github.com/bgelens/HybridRunbookWorkerDsc

**Comment by PlagueHO** [comment]
I took a brief look over it and it's looking really fantastic @bgelens 

I did notice a few bits and bobs that might need to be addressed (nothing major at all - e.g. Remove the #TODO comments from the unit tests). I think it'll be easier to review though if you do this: https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md#how-to-set-up-the-review-pull-request

Great work though and just my 2c!

**Comment by bgelens** [comment]
@PlagueHO Copied in the TODOs when I updated the test template headers :-) Thanks, fixed. I'll go ahead with the review PR

**Comment by johlju** [comment]
Are there still interest of adding the HybridRunbookWorker resource module to the DSC Resource Kit?
If so I like to help getting this reviewed according to the new process of getting a resource module added to the DSC Resource Kit.
I have opened an issue to update the text on [How to do a new resource module submission](https://github.com/PowerShell/DscResources/issues/356),
but basically if we gonna submit this resource module to DSC Resource Kit we need to make sure it follows the [Quality Governance](https://github.com/PowerShell/DscResources/blob/master/Naming.md#quality-governance).

**Comment by bgelens** [comment]
Hi @johlju, I don't have interest in this anymore as I've moved ahead some time ago and [published](https://www.powershellgallery.com/packages/HybridRunbookWorkerDsc) it myself. I'll close the issue.
