### ISSUE TITLE
Structure of unit test examples

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/DscResources#143]
I wanted to throw this one out for some discussion around the approach taken when putting together unit tests for DSC resources.

Currently [the example](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1) suggests that we should be creating a describe block for each of the three main DSC methods (get/test/set). I feel that this results in people writing tests that match the code, rather than tests that match the desired functionality to the end user.

An example of an alternative is the approach that came together in SharePointDsc - we use the Context block to describe potential states of a system when we run different methods. A basic example of this can be understood by looking at [SPInstall's unit tests](https://github.com/PowerShell/SharePointDsc/blob/dev/Tests/SharePointDsc/SharePointDsc.SPInstall.Tests.ps1). Here you see context's for:

 * SharePoint binaries are not installed but should be
 * SharePoint binaries are installed and should be
 * SharePoint installation executes as expected
 * SharePoint installation fails
 * SharePoint binaries are installed and should not be
 * SharePoint 2013 is installing on a server with .NET 4.6
 * SharePoint is not installed and should be, using custom install directories

Looking at this list, we don't really target the functions, rather the specific functionalities and potential states of the server when the methods run. This gives a few benefits:

 * Writing mocks becomes simpler as I can group together the mocks based on the state of the system, rather than write the mock in multiple places to align with the get/test/set structure. For example, in my above example I mock the methods to say that SharePoint isn't installed just inside the context blocks that align with that state, where as the current model would have me making the same mock in all three get/test/set describe blocks
 * This approach makes authors consider the state of target machines, rather than just consider the structure of the code they wrote. From what I've seen with SharePointDsc it's gotten authors to look at the tests from a different angle, which can help make sure we cover more use cases because as they write a context they expect it to run in they might discover they didn't consider it fully and need to extend the code

I feel this approach sets us up a bit better in terms of structuring tests that would map back to "requirements" essentially - not that we document those specifically right now, but this test structure could start to be that documentation in that a context object could represent a specific supported scenario that we know works because we test for it. In the back of my head I've got an idea for SharePointDsc where we take the code that auto-generates our wiki documentation that scans the tests and includes this list of "supported scenarios" in the documentation so users are clear on what to expect.

Anyway - would love to get the thoughts of other resource contributors on this approach to see if it is worth adopting more widely or worth tweaking to fit a bit better.

**Comment by KarolKaczmarek** [comment]
I agree, it makes more sense to structure tests based on scenarios rather than what function we test. @BrianFarnhill would you have some time to send PR with modified template?

**Comment by BrianFarnhill** [comment]
@KarolKaczmarek Absolutely, I'll set something up and open PR this week

**Comment by BrianFarnhill** [comment]
@KarolKaczmarek Just opened #144 with a first cut of my proposed changes, let me know what you think.

**Comment by BrianFarnhill** [comment]
The PR just got closed, so happy to close this issue off as well.
