### ISSUE TITLE
Request for resource to manage OS Locale

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/DscResources#145]
There was a request today for a DSC resource that manages the system locale setting.  This could be implemented using Get/Set-WinSystemLocale that was implemented for Server 2012.
https://technet.microsoft.com/en-us/library/hh852118.aspx

Filing issue to track if anyone in the community might like to take on this effort.  Thanks!

**Comment by PlagueHO** [comment]
@mgreenegit - I reckon I could put this together this weekend if you like? I have an existing DSC resource design pattern that I think would fit this resource and make light work of it. It's actually not that dissimilar to xTimezone either.

As this is would be a shiny new resource, should be created as an "x" resource, or are we ready to start doing away with the "c" or "x"? @KarolKaczmarek ?

**Comment by kwirkykat** [comment]
@PlagueHO  It would be an 'x' resource for now since the new naming convention hasn't been finalized yet.

**Comment by KarolKaczmarek** [comment]
I think we should be pushing it as non "x" with 0.1 version. This seems to be agreed on and the only think missing is the exact criteria of going to 1.0 for non "x", which we will have time to figure out before this module reaches that state.

**Comment by PlagueHO** [comment]
Thanks @kwirkykat , @KarolKaczmarek  - I'll create it without the x for now. I could always add the 'x' if there is a delay in the HQRM plans.

**Comment by PlagueHO** [comment]
@kwirkykat, @mgreenegit, @KarolKaczmarek  - I've finished this resource now: https://github.com/PlagueHO/SystemLocale

I'm guessing HQRM won't be in place in time. But It might take a while before this resource can be reviewed and moved over to be part of the Resource Kit. So I'll hold off changing it over to an 'x' resource until I hear otherwise from you peeps. I'm happy to convert it to 'x' though if it'll help move it across.

Cheers!

**Comment by PlagueHO** [comment]
Question: I've named the resource SystemLocale, but I'm assuming that if the plan is to do HQRM then this resource might need to be renamed SystemLocaleDSC at some point? Should I do this now or just wait?

**Comment by kwirkykat** [comment]
@PlagueHO 
You should rename it to SystemLocaleDsc now.

I just posted a [new guide](https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md) for submitting resource modules to the DSC Resource Kit.

Please open a PR to an empty branch so the reviewers can make comments.

From my quick look at this module, it looks pretty good.
Thanks for all your hard work!

**Comment by PlagueHO** [comment]
@kwirkykat - cool! I'll have a read tonight (NZ time) and get this changed over. Thanks for the heads up and all the work!

**Comment by PlagueHO** [comment]
Hi @kwirkykat  - I've done all the prep work for this resource (renamed to SystemLocaleDsc), but I'm having trouble performing steps 4 and 5 of the [new guide](https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md).

I've managed to figure out how to create an empty branch that is in a different commit history (https://github.com/PlagueHO/SystemLocaleDsc/tree/transfer). However I can't submit a PR from my Dev (or Master) branches to the new Empty branch:
![2016-07-26_20-00-47](https://cloud.githubusercontent.com/assets/7589164/17130249/b0da08b6-536b-11e6-8d38-54650197f47e.png)

I feel like I'm probably missing something completely obvious. If you could guide me through the process (steps 4 and 5 only) then I could submit a PR with some more details of the process. I hope I'm not just being really dumb here.

**Comment by kwirkykat** [comment]
@PlagueHO  [This blog](http://astrofrog.github.io/blog/2013/04/10/how-to-conduct-a-full-code-review-on-github/) seems to have the right process. Apparently you will need to create 2 new branches. I will update the documentation

**Comment by PlagueHO** [comment]
@kwirkykat - awesome! Thank you! I'll look through it tonight and get it sorted. Thanks for the link.

**Comment by kwirkykat** [comment]
@PlagueHO Updated the [new module guide](https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md) with better instructions for setting up the review PR.

**Comment by PlagueHO** [comment]
This PR is ready for full review:

https://github.com/PlagueHO/SystemLocaleDsc/pull/2

**Comment by kwirkykat** [comment]
Module submission progess:
- [x] 1. Separate public repository created
- [x] 2. Review pull request open
- [x] 3. 1st reviewer approved (Katie)
- [x] 4. 2nd reviewer approved (Travis)
- [ ] 5. 3rd reviewer approved (Mariah)
- [x] 6. Tests passing
- [ ] 7. Repository transferred
- [ ] 8. Module released

**Comment by PlagueHO** [comment]
@mgreenegit - I think this one is complete. Can it be closed? Cheers!

**Comment by kwirkykat** [comment]
This module has been added to the DSC Resource Kit and released https://www.powershellgallery.com/packages/SystemLocaleDsc/1.0.0.0
