### ISSUE TITLE
Remove Chocolately From appveyor.yml Files Using WMF5

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/DscResources#147]
Chocolately has been making the AppVeyor test runs unreliable lately due to errors installing Pester.
This issue has been causing a lot of failed AppVeyor runs like [this one](https://ci.appveyor.com/project/PowerShell/xpsdesiredstateconfiguration/build/3.11.324.0).

To make the test runs more reliable, for all WMF5 tests we can now use the PSGallery to install Pester instead. An example of an appveyor.yml file with the update to use PSGallery has already been implemented in the xPSDesiredStateConfiguration appveyor.yml file [here](https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/appveyor.yml). This fix now needs to happen for all resources running tests with WMF5.

The use of Chocolately to install Pester for all WMF4 tests is still required.

**Comment by PlagueHO** [comment]
Is it worth asking the AppVeyor team if they'd consider adding the [PowerShell package management module](https://www.microsoft.com/en-us/download/details.aspx?id=51451) to their non WMF5 build images? I've seen the add stuff to their build images before on request.

**Comment by kwirkykat** [comment]
^? @TravisEz13

**Comment by vors** [comment]
WMF 5 is actually on the default image already

**Comment by KarolKaczmarek** [comment]
Agree with @vors we should switch to WMF 5 image by default, however ideally we should introduce test matrix to all repos and run on WMF 4 as well (perhaps WMF 5 on every PR and WMF 4 nightly? Not sure what capabilities appveyor has in that regards). 

For WMF4 runs we can use chocolatey or as @PlagueHO suggested ask if AppVeyor would be willing to add PackageManagement module to their image - that would be preferable since it would simplify our appveyor templates.

**Comment by PlagueHO** [comment]
@vors - I see what you mean. If you're not specifying an os: in the AppVeyor.yml then it defaults to WMF 5. Are there any DSC Resource modules that are actually overridding the OS: to set it to either "Visual Studio 2013" or "Visual Studio 2015"?

**Comment by vors** [comment]
The image "WMF 5" is obsolete, because "Visual Studio 2015" (default one) includes WMF 5 now.

I just updated platyPS to use the package manager
https://github.com/PowerShell/platyPS/blob/master/appveyor.yml#L3

Note: you need `Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force` part

```yml
install:
    - ps: |
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
        Install-Module Pester -Force
```

**Comment by PlagueHO** [comment]
@kwirkykat - is it common for the Install-Module to fail (requiring the 10 retries)? @vors ' simpler code is a bit simpler, but if there is a problem with Install-Module failing then I'm happy to use the more complex code with retrying.

**Comment by kwirkykat** [comment]
@PlagueHO We prolly don't need the retry. It's leftover from the code I copied from. I can take it out.
I'm not sure just those two lines will ensure that the module is *always* downloaded from PSGallery rather than from a different repository, so I'm going to leave the slightly-more-complicated code that specifically pulls from the PSGallery for now.

@vors I will take out ```os: WMF 5```

**Comment by PlagueHO** [comment]
@kwirkykat - Cool. Fair enough.

I was thinking this code:
```powershell
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
Install-Module -Name Pester -Repository PSGallery -Force
```
Will always download from PSGallery only. The force will install it even if the PSGallery repo is untrusted.

**Comment by kwirkykat** [comment]
^ That looks good to me :+1: 
Will try to start rolling it out on Monday

**Comment by PlagueHO** [comment]
Cool! Thanks @kwirkykat . I've submitted the PRs to xNetworking, xDFS, xTimezone, xDHCPServer. I also removed the OS: from them so that they all use the default AppVeyor build image. I might get a few more submitted before the end of the day.

**Comment by kwirkykat** [comment]
@PlagueHO Thanks! :)

**Comment by KarolKaczmarek** [comment]
don't forget about the template itself ;) https://github.com/PowerShell/DscResources/blob/master/DscResource.Template/appveyor.yml

**Comment by kwirkykat** [comment]
Big thanks to @PlagueHO @Indhukrishna and @Dan1el42. All blocking issues have been fixed and all AppVeyor files have been updated :tada:
