### ISSUE TITLE
Create guidance on how to properly create singleton resources

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/DscResources#15]
Create guidance on how to properly create singleton (where only one resource of this type is allowed per configuration) resources

**Comment by TravisEz13** [comment]
My initial suggestion would be to create a key that specifies the host but only allows localhost, this would not be used in the resource anywhere.  DSC itself needs to handle this better and I've already given this feedback to that team.

**Comment by KarolKaczmarek** [comment]
@TravisEz13 wrote a blog post about it http://blogs.msdn.com/b/powershell/archive/2015/06/23/want-to-write-a-dsc-resource-where-only-a-single-instance-can-be-configured.aspx 
Closing
