### ISSUE TITLE
[New Resource] FileContentDsc

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#155]
A DSC resource for modifying XML files (elements, attributes, nodes etc) would be very useful. I know [cXML](https://cxml.codeplex.com/) is available but the project is stagnant and is fairly bare bones with no unit tests and practically no documentation.

Besides, the company I prefers not to use DSC resources that are maintained outside the DSC PowerShell team (e.g. 'c' resources).

If I have time I'll implement this - unless someone already has something they'd be able to bring into the DSC PowerShell team resources.

**Comment by ArieHein** [comment]
On a similar note I would go for a much broader Resource for JSON and INI files as well.
There are some XML Powershell repos that are interesting like https://github.com/Jaykul/Xml
I liked the Idea of a DSL for XML but that might be offtopic.

**Comment by PlagueHO** [comment]
Definitely agree there. It seems like some generic text file content manipulation resources are needed.

I'd say at least the following would be extremely useful:
- XML
- JSON
- INI
- Generic Regex/Replace

If anyone out there already has created these resources and would like to submit them to the community but need help getting them up to minimum standards (unit tests, examples, style etc), I'm happy to help.

Otherwise I'll add them to my list of resources I need to create when I have time :smile:

**Comment by ArieHein** [comment]
question is, do you want it as a DSC resource or simply a PowerShell module.

Do you want to make sure a Node configuration changes just because one INI entry doesn't match ?
I can see valid usages but at the same time see it used wrongly on so many other ways.

Something to ponder about ;)

**Comment by KarolKaczmarek** [comment]
Good point @ArieHein, but one doesn't necessarily contradict another. One way to do it is to implement a PS module for operations mentioned above, publish it to PS Gallery, then use it in the implementation of the resource module itself by listing it as a dependency.

That being said, PowerShell has access to e.g. System.Xml.XmlDocument for XML operations, so not sure how much value we can really add in the new module, but as you said that's one thing to consider - I'll leave it up to the author.

**Comment by PlagueHO** [comment]
@ArieHein - while I'm definitely a fan of encapsulating functionality into a modules (which can then be distributed via PS Gallery), in this case it would cause some problems:
- It would require WMF5 or PS PackageManagement to be installed and available on all DSC nodes - many companies are not quite at this point yet (despite how much I wish they were :smile: )
- It would require access to the PS Gallery from the target node or the module to be copied onto the target node during initial deployment - which in some cases isn't possible.
- As @KarolKaczmarek says, we are just obfuscating functionality that is provided by the .NET System.XML classes (although I'll concede that System.XML can be a bit fiddly to use sometimes and wrapping it would be nice).

I think this approach would probably cause more problems than it solves.

Just my 2c!

**Comment by ArieHein** [comment]
example of something recently published

https://github.com/IngoGege/xXMLConfigFile

**Comment by IngoGege** [comment]
@ArieHein I was going to request that my resource is added to DscResources. What do you think?

**Comment by ArieHein** [comment]
Thumbs up for that. Think @PlagueHO  started something as well. Team up as he has experience in how to build and setup the repo for all the checks and tests needed prior to moving the repo to MS hands. Perhaps some of the ideas mentioned here for ini and json and rest might be incorporated into a general TextStream Manipulation framework ;)

**Comment by IngoGege** [comment]
@ArieHein sounds good, but to get all the different types into one resource would be a huge effort. Wouldn't it be better to have them seperated. My resource is based on .NET functionality and looking only at XML...as @PlagueHO mentioned it can be a bit fiddly to use (case-sensitivity).

**Comment by PlagueHO** [comment]
Hi @ArieHein, @IngoGege - I'm all for including your resource (the more we existing stuff we use the better)!

I'd definitely in agreement - we don't want to put all the functionality in one resource, but I'm thinking 3 resources in one resource module. E.g.:

ConfigFileDsc - containing the following resources:
MSFT_XMLConfig
MSFT_JSONConfig
MSFT_INIConfig

The tricky part is getting a resource up to the requirements for getting it included in the MSFT Community Resource kit - that said, I'm definitely up for helping out on that one. I could start submitting some PRs with the tests into your repo if you like? I've got a few of my own resources that I'm working on getting included at the moment, but after that I'll have some more time.

**Comment by IngoGege** [comment]
Hi @PlagueHO , @ArieHein ,
I think this would be the best solution and I would be more than happy to get some PRs. How about a modules gets generated in the community and we just add the existing code as resources. I think this would make the most sense, or?
@PlagueHO : No rush!J

**Comment by PlagueHO** [comment]
I'm thinking about working on these resources if I have the time. At the moment I'm just trying to throw out ideas so don't take anything I'm saying as "the right way to do it". Just looking for discussion at this point.

What I was thinking was creating a new HQRM resource module called:
ConfigFileDsc (or something along those lines).

It could contain (with potential for more) the following WMF4 (non class based) HQRM resources:
MSFT_XMLConfigDsc - for working with XML configs (@IngoGege - would your resource fit the bill here? Would you want to have it submitted to the resource kit?)
MSFT_JSONConfigDsc - for working with JSON files (this might be more difficult as it would really need an XPATH type query language for specifying nodes).
MSFT_INIConfigDsc - for adding/removing INI settings.
MSFT_StringConfigDsc - for using RegEx expressions for ensuring specific patterns are replaced with different text (this could handle other types of Config not specifically covered by the XML, JSON and INI).

The above resources are just a rough guess off the top of my head and are likely to change.

I have a need for these resources myself (for our workloads at IAG), but it would be useful to know if anyone else has requirements, suggestions etc.

So, just wanted to kick off the conversation.

**Comment by ArieHein** [comment]
Why limit this to DSC ?

Preferably would be tocreate a general module that you can then use as is inside DSC and non DSC scripts for that matter. Reviving the idea for TextStream Manipulation Framework  ;)

At one point there was a xReleaseManagement DSC resource that had xToken*something* in it that I used as part of my pipeline built on TFS and ReleaseManagement that helped change any xml based config files, like web.config so I could inject things like the connection string and various custom values based on the environment I was deploying to ( Test, QA, Prod etc).

I think there's even an issue about the xToken or xReleaseManagement as somewhere along they way, something went missing.

**Comment by IngoGege** [comment]
@PlagueHO that's sound good and is also my point of view. This would make the module more flexible to add different kinds of resources.

**Comment by ArieHein** [comment]
Well, this is a nice read :)

https://www.simple-talk.com/blogs/psyaml-powershell-yaml/

**Comment by PlagueHO** [comment]
@ArieHein - it would definitely be really useful to have a general purpose Text Manipulation Framework module that could be used to modify text files in any way we need. Is there any word on a module like this being created? I'd throw code into it for sure, but I expect it is actually a significant job on it's own.

One question I'd have is: What is the policy/process for having DSC Resources that are dependent on another PowerShell module that is maintained or licensed outside the DSC community? I'd expect there are resources that are dependent on other modules, I'm just not aware of which ones and whether or not it is safe to do that.

So @ArieHein  - you'd be wanting YAML file manipulation resource as well - and you're right - that is a great read and a pretty awesome module!

But I've definitely encountered at least 5 or 6 different config file formats for workloads we deploy (sometimes one workload has multiple different config file types). It would be awesome for a single module that could handle all of them, but I doubt that is the case.

Anyway, not sure what the best way to approach this is. Perhaps we just propose MOF Files for each resource and the discuss each?

**Comment by ArieHein** [comment]
I dont see YAML being treated as first class citizen within .Net like XML is, in the near future. Only recently did SQL started offering JSON as a datatype, and even that isn't 100% iirc.

Were bound to see more community-based text manipulation frameworks but I doubt it would be approved to be used inside DSC resources. Its more likely that it will have to be written by MS, published to Gallery and then you use it inside, much like @KarolKaczmarek said. Although there are exceptions, like Pester for example. Perhaps if it comes from a contributor that MS knows and has shown previous experience and good programming skills, they might adopt it and accept it.

But I'm sure id like what @IngoGege  or similar wrote as a DSC resource. I see config files as part of the system health. If values are changed manually that affect how a system behaves, I want to know them or even revert the change. I'm sure some would use it to all sort of files that shouldn't be idempotent as a configuration should be, but that's an education issue.

As everything in DevOps, pick a small area, one simple subject, automate, iterate, expand :)

**Comment by KarolKaczmarek** [comment]
@PlagueHO @ArieHein Depending on third party open source module would certainly be a possibility, as long as it would be released under well known permissive OSS license like MIT, I don't think that would be much of a problem, even if it wasn't created by Microsoft (we are long past the not-invented-here syndrome ;) ).

It would also be preferable that the module we depend on is deployable via PSGallery, as that would simplify packaging and updates.

**Comment by PlagueHO** [comment]
Good to know, thanks @KarolKaczmarek! Now to find (or create) an OSS MIT PS Module that can manipulate configuration files in a generic and extensible way - any thoughts?

**Comment by kamranayub** [comment]
This would be excellent, especially when configuring web servers and ASP.NET there's a lot of configs to work through including IIS apphost, machine config, etc. Also when configuring vendor products that rely on Java and XML config files, it can be very useful. I created a small general-purpose XPath resource that will change any node(s) matched and update the node's value but it's limited in scope. I'd love an official, more robust module to use.

**Comment by PlagueHO** [comment]
Hi @kamranayub - agreed. I too would really love a general purpose module that could fit the various different scenarios. I use it for configuring Web Apps, but also for configuring Tomcat Web Apps (and other non IIS based workloads). There hasn't been much progress around any of this for some time, so I may just start from scratch with a simple HQRM module that manages the four scenarios I have: XML, INI, JSON and general REGEX replace (I have a few workloads that don't adhere to any of the first three).

**Comment by PlagueHO** [comment]
Our infrastructure teams are going to need the regex Replacement DSC Resource next week so I'm going to kick this resource module off.

I'll only add the Regex one for now and then submit that through to the DSC Resource kit. I will be creating this as HQRM.

Anyone will then be able to add the more complex resources (XML, JSON, INI etc) to the module either once it is in the resource kit or to my repo (if they want).

The Regex Replacement DSC resource will be able to insert or replace text with a string or password from a credential object.

**Comment by ArieHein** [comment]
@PlagueHO if you go for a general Regex, this should also cover XML, JSON and INI as well, if we use the correct Regex patterns. It might not be the most effective manner for each type though.

On a genreal broader range, this isn't really a ConfigFile, but rather "AnyFile" that is text based.
Nothing stops us from using an application file say main.html, and change HTML tags inside of it, based on the Regex pattern...but then this goes more into orchestration and less of configuration.

**Comment by PlagueHO** [comment]
@ArieHein - so a better name might be FileContentDsc?

Agreed, the Regex replace pattern could be used across many scenarios, which is one of the reasons I am starting with it. The other reason being that we need to deploy some Java workloads and they have a crazy mishmash of config file types with some that I don't even think have names (I'm sure every framework/app vendor makes up a brand new config file style every time). So the Regex one will at least allow me to configure these for now.

Plus, I'm going to include the ability to pass PSCredential objects across so that the values can be covered with MOF Encrpytion. This is because we often have to set things like Java Key Store passwords in config files (yep - in plain text - *sigh*).

**Comment by PlagueHO** [comment]
This is now in progress: https://github.com/PlagueHO/FileContentDsc

@mbreakey3 - are you able to tag this as in progress?

I aim to have the first 3 HQRM resources (ReplaceText, KeyValuePair and IniSettings) completed in the next week. JSON and XML will follow soon after with the possibility of YML as well. I won't release this to the PS Gallery, but will submit it for inclusion in the Resource Kit instead.

**Comment by PlagueHO** [comment]
I've completed the first three resources in this module now. Working on XML, YML and JSON over the next few weeks.

They should meet HQRM standards (full integration test suite, 81% unit test coverage) and also contain Wiki generated using the auto-documentation method.

However, I have not released these to the PSGallery because I plan to submit this to the resource kit, so all the documentation is configured as if it is included. This is because reworking a module to get it included in the resource kit takes effort, so I thought I'd just save the time and just put it together as if I was already undergoing the submission process.

The problem though is that modules do take a little while ( :grin: ) to be added to the resource kit. And if I release this module myself to the PSGallery, it will need to be renamed *if* it is released as part of the resource kit. Renaming a module is a lot of work for the maintainer and for any consumers of the resource module - so it would be good to avoid it.

@zjalexander - what are your thoughts here? Should I just release this myself or hold out to get this added to the resource kit? I know there is a backlog of stuff to go in and the DSC team don't have the resource to review them, so do you have any advice?

I do plan on adding additional modules (XML, JSON, YML) to this repo over the next few weeks, so even if it was accepted in the resource kit I'd likely be still adding to it.

**Comment by PlagueHO** [comment]
I have one more resource I'd like to add to this module as well: a Text file templating resource.
One of the needs our teams have is to take text based template config files out of a source repo (via HTTPS) and them merge some values into it.

For example, we could have a file like this in our config repo:
```json
{
  "connectionstring": "{{value1}}",
  "somesetting": "{{value2}}",

  "machine": {
    "option3": "{{value3}}"
  }
}
```

We could then have resource called `TextTemplateFile` that looked like this (property names not final):
```PowerShell
TextTemplateFile myConfig {
    File = 'https:\\myconfigs\myapp\appsettingstemplate.json'
    Dest = 'c:\myapp\appsettings.json'
    Values = @(
        'This is my database connection string',
        'and somesetting',
        'and value3'
    )
}
```

The only problem with this is that the template has been copied and the values merged into it, it will be considered in state from ever after - even if the source template changes. So I'm not sure if this is that useful. I will still be completing the JSON repo which would handle this scenario.
Does anyone have any thoughts on if this is useful or not?

**Comment by ArieHein** [comment]
There is a concept called Tokenization, when dealing with say a Release pipeline.
You place a web.config  for a website that instead of values has similar template as your template but where the values are replaces with __Property__ 
and then in the pipeline process you have a step that searches for any __Property__ and replaces I according to the environment your deploying to.

Thus you have only one web.config in your code and the values for various fields are controlled outside of the repo once the website is released and deployed.

There used to be a xTokeniztion in the old TFS Release Management, before it was embedded into the TFS itself.

**Comment by PlagueHO** [comment]
Hi @ArieHein - sorry I missed your comment here (too much going on at the same time). Thinking about your idea, it definitely could be really awesome. Definitely something I'd be keen on adding. So I'll get onto it :grin:

**Comment by johlju** [comment]
@PlagueHO the resource in https://github.com/PlagueHO/FileContentDsc seems like a good candidate to make a submission to DSC Resource Kit? Either way, maybe we should move any outstanding enhancement from this issue to new issues in that repo instead?

**Comment by PlagueHO** [comment]
HI @johlju - oh yes, I was meaning to submit all my other resources: FSRMDsc, WSManDsc, FileContentDsc, iSCSIDsc

After the Azure Global Bootcamp is done this weekend I'll get some work done to submit these for inclusion. Thanks for the reminder!

**Comment by johlju** [comment]
Sounds good. 😄 

Wish you very much good luck with hosting the Azure Global Bootcamp, bet it will be fun and your attendees will learn a lot!

**Comment by johlju** [comment]
@PlagueHO Can we close this one now?

**Comment by PlagueHO** [comment]
@johlju yes indeed.
