### ISSUE TITLE
[New Resource] OfficeOnlineServerDsc

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/DscResources#158]
I've been working with a few other Microsoft guys on a resource for deploying/managing Office Web Apps 2013 and Office Online Server 2016. The module is currentlin in my repo at https://github.com/BrianFarnhill/OfficeOnlineServerDsc so once it's been reviewed we can move this one across.

Let me know what you need updated from me and I'll get on to it ASAP. Thanks guys!

**Comment by kwirkykat** [comment]
@BrianFarnhill Can you please open a PR to an empty branch in your new repo so that the reviewers can make comments?

Also, I noticed that you included the Modules folder like in SharePointDsc. Is this repo going to have anything other than the DSC resources in the future?

**Comment by BrianFarnhill** [comment]
@kwirkykat I'll open it shortly and tag it here for review. As for the other modules, once we finish the "reverse" module for SharePointDsc I'll want to do the same thing with this one, which is why I've followed the same structure as SharePointDsc. That said, if its a massive issue we can swap it around, but I also like that in this approach we don't ship the tests and other bits inside the module itself. On the flip side though I know the publishing scripts you guys use don't like the folder structure I have, so happy to go with whatever your preference is for now on this one and deal with rearranging it later if that's the case. Let me know what you think.

**Comment by kwirkykat** [comment]
@BrianFarnhill The structure is fine. The publishing scripts should be made more flexible. Don't swap it just for them.
Just asking to make sure you weren't planning to add a bunch of other stuff in here as well because our PMs don't want anything not-DSC in a repository with a ______Dsc name.

**Comment by BrianFarnhill** [comment]
@kwirkykat Yea the only other thing that will go in here that I can foresee will be the reverse engineering thing to generate a DSC config from an existing server, so definitely DSC related and tightly linked to the main module itself.

**Comment by BrianFarnhill** [comment]
@kwirkykat The PR is now open for review - will wait for your feedback :)

**Comment by BrianFarnhill** [comment]
@kwirkykat Sorry use that second PR, got the branches set up so it shows everything as an addition so you can review it right :)

**Comment by kwirkykat** [comment]
Module submission progess:
- [x] 1. Separate public repository created
- [x] 2. Review pull request open
- [x] 3. 1st reviewer approved (Katie)
- [x] 4. 2nd reviewer approved (Karol)
- [ ] 5. 3rd reviewer approved (Mariah)
- [ ] 6. Tests passing
- [ ] 7. Repository transferred
- [ ] 8. Module released

**Comment by kwirkykat** [comment]
This module has been added to the DSC Resource Kit and released https://www.powershellgallery.com/packages/OfficeOnlineServerDsc/0.1.0.0
