### ISSUE TITLE
Step 8 on the NewResourceModuleSubmissions.md Needs Adjustment

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#159]
Step 8 of the NewResourceModuleSubmissions.md document requires that the new resource module is transferred to the PowerShell Organization. However, this is only possible if the person transferring the Module is a member of the PowerShell Organization (which most of us aren't).

I ran into this problem when I transferred xDFS over. The way we solved it was that I transferred the repo over to @KarolKaczmarek and then he transferred it into the PowerShell Organization.

It might be worth noting that this will process will need to be used.

**Comment by kwirkykat** [comment]
Updated the [document](https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md) with clearer instructions to transfer the module to me first so that I can transfer it to PowerShell. Also included a link to the instructions for transferring a module.
