### ISSUE TITLE
xOneGet

### ISSUE THREAD

**Issue by dfinke** [PowerShell/DscResources#16]
Is this still working/supported? Will it be added to the repo?

https://www.powershellgallery.com/packages/xOneGet/

**Comment by vors** [comment]
@jianyunt is it the same resource? https://github.com/PowerShell/OneGetProviderResource

**Comment by jianyunt** [comment]
No. xOneGet is to download the OneGet platform itself. It's in inbox now so it should be removed from the gallery.
