### ISSUE TITLE
Sample UTs do not follow UT template

### ISSUE THREAD

**Issue by narrieta** [PowerShell/DscResources#166]
The samples pointed out in

```
https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md
```

do not follow the test template (e.g. they wrap the entire test within InModuleScope)

**Comment by KarolKaczmarek** [comment]
Thanks.

Could you file an issue about that in xNetworking repo where these samples come from (we need to update them)?

Also, do you know of any real world implementation of the updated samples so that we could point to those instead?

**Comment by kwirkykat** [comment]
These templates are only examples and do not need to be strictly adhered to.
@mbreakey3 is updating the test templates to make them more clear.

If there is an issue with xNetworking tests please open an issue under that repository.

**Comment by kwirkykat** [comment]
Norberto explained this offline.
Re-opening since sample links do need to be changed until this is fixed.

**Comment by PlagueHO** [comment]
I'd like to fix the xNetworking ones as well anyway: @narrieta  - are you going to log this against xNetworking? I'll get onto fixing xNetworking as soon as I can.

**Comment by narrieta** [comment]
Done: https://github.com/PowerShell/xNetworking/issues/132

**Comment by johlju** [comment]
I think this one is solved. To me it looks like the links to samples do link to correct sample that follow the templates. I suggest we close this issue.
