### ISSUE TITLE
Community Call meeting ics file upload

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/DscResources#170]
As noted in this discussion on twitter with @kwirkykat  https://twitter.com/ryanyates1990/status/760944875856592896 having an ics file uploaded in the repo would be a good idea for ensuring that people don't accidentally miss out on the community calls (like I did this evening) as it can also be linked to in the blog announcements as well.

**Comment by kilasuit** [comment]
Have we managed to get any further with this one @kwirkykat  ?

**Comment by kwirkykat** [comment]
@kilasuit Haven't finalized the date for the next community call yet, sorry. I'll try to post the file as soon as the date is final.

**Comment by kilasuit** [comment]
Thats good to hear - thought I may have missed it being announced with the amount of other things going on lately.

**Comment by kwirkykat** [comment]
@kilasuit Uploaded an [ICS file](https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/09-15-16/CommunityCall091516.zip?raw=true) for the next community call 09/15/16 1-2PM PST
