### ISSUE TITLE
Suggesting additions to GettingStartedWithGitHub.md

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#176]
I suggest additions to GettingStartedWithGitHub.md to help beginners with `git`.
* How to resolve merge conflicts
* How to create a .gitignore file

**Comment by johlju** [comment]
I have put together a draft for this. I send it as a PR for your review. Let me know if this is something that is suitable.

**Comment by mbreakey3** [comment]
@johlju This looks great! Thank you for taking the initiative to write this up.

**Comment by johlju** [comment]
@mbreakey3 Thank you! I hope it helps other contributors. :smile: 

I have put together a new section, I will add that to the same PR. This is for the steps I did today when I took over a PR. Might be useful for someone else too.

* How to take over a pull request from another contributor

"Take over" feels so definitely, is there a better phrasing I could use?

**Comment by mbreakey3** [comment]
How about: "How to take over a pull request when the previous owner is unable to complete it"?

**Comment by KarolKaczmarek** [comment]
Other suggestions:
"How to continue working on abandoned pull request" 
"How to continue working on a pull request when author is unable to complete it"

**Comment by KarolKaczmarek** [comment]
Also, even though it's not strictly git related, but more of a guidelines, I'd suggest adding that when you continue working on someone else's PR, the new PR should point to the original one and mention the work is based on it.

**Comment by johlju** [comment]
I have changed so that is uses all suggestions.
