### ISSUE TITLE
Suggestion: Add guidance on parameter documentation format in Readme.md

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#180]
I've noticed that there isn't much consistency between the parameter documentation of resources. Even within the same module there are often different formats used to list the parameters available. _Many resource parameter lists in the Readme.md are also missing important information such as parameter format, valid values, defaults, required vs optional. *This results in having to look in the MOF or PSM1 file to find the missing info before being able to use the resource properly._

In future it would be great if all modules were using @BrianFarnhill 's Documentation Helper and generating the content from the MOF's themselves. However, until all modules are at that point I think we should adopt a more formal structure to the parameter format to ensure:
1. All required information is provided in one place.
2. It is provided in a standard format.
3. It "could" be generated automatically directly from the MOF files (ensuring support for the DocumentationHelper).

I have found myself adopting the following format:
- **[Type] ParameterName** _(Read/Write/Required/Key)_: Description. Defaults to "default value" (if applicable). { _DefaultOption (if applicable)_ | Option2 | Option3 }.

I've also been ensuring that the description of each parameter in the MOF contains the default value that is used if specified. This enables the readme content to be created automatically from the MOF file. This also allows the *-TargetResource Get-Help .PARAMETER sections to be generated from the MOF as well.

I'm OK with using some other format (table?) for this information, as long as it's consistent and there is a standard to use.

I feel it would be worthwhile adding some form of guideline for this.

Any thoughts?

**Comment by johlju** [comment]
Awesome suggestion! I thought about this the other day, that many resources have different descriptions in MOF and README.md (release notes), and lacking information about what parameters are keys and if they are required. I did not think about adding the type, that makes it even better!

I'm happy with he format you suggest. It's like the one today, it doesn't take up a lot of white space.

It's gonna be neat with the automation when we can get that.

**Comment by PlagueHO** [comment]
Are there any suggestions/preferences where this documentation should be included? It doesn't seem to fit in with any of the other guidelines or documentation.

Perhaps we should add a new "DocumentationGuidelines.md" file?

**Comment by johlju** [comment]
@PlagueHO When the new "automatic parameter documentation" to wiki is incorporated (to DscResources.Test?), I think it would be good if it used this format. If it doesn't already (haven't checked).

Regarding where to document this. I think in the BestPractices.md with a new section "Documenting Resources" maybe?

**Comment by PlagueHO** [comment]
@johlju - you raise some good questions. The "automatic parameter documentation" generates everything except the default values:
https://github.com/PowerShell/xNetworking/wiki/xDhcpClient

If we ensure that the Description in all MOFs mentions the default value then we should be OK here. Is this going to be acceptable do you think? @BrianFarnhill  - did you guys putting any specific handling in around default values?

But I actually didn't migrate the Wiki/Help auto generation code into DSCResource.Tests - but thinking about it after you mention it -it definitely makes sense to do so (as well as the Markdown.md validation tests). So I've put the other PR on hold while I add this.

**Comment by johlju** [comment]
That's is great if we can get it in. One thought though. How long can the descriptions be in the schema mof? It is from there the descriptions are gotten (I think). I have long parameter descriptions in the README in some cases. Which is not in the schema becuase I had an issue adding a long description. 
I might document this in the resources .md. But then there is two places where the parameter is documented. 
See xSQLServerSetup resource as an example.

**Comment by johlju** [comment]
@PlagueHO getting a bit off topic here now. You mentioned validation for markdown, that would be good. But also if it is possible, it would be great if the test for testing the examples would be incorporated into DSCResource.Tests as well. I made some improvements (I think) to the tests from Networking, so it tests each example in its own It-block, so one sees easy which example broke.
https://github.com/PowerShell/xSQLServer/blob/dev/Tests/xSQLServerCommon.Tests.ps1#L9

**Comment by PlagueHO** [comment]
@johlju - good point about the MOF description length. @kwirkykat  - are you aware of a description length limit in the MOF file? If there is none (or it is very long) then it would be good if we could load the entire parameter documentation into it. Otherwise auto documentation won't work (or we'll need some additional metadata storage).

Oh yes, the Example tests should also be incorporated - I had forgotten those. I think Tyson and Brian had both implemented this in xNetworking and SharePointDsc as well. I'll see if your code/method is different to what they implemented. Hopefully it is similar process and we can combine them into a single test. Will check it out tonight!

**Comment by BrianFarnhill** [comment]
@PlagueHO Nah nothing specific on our end - we are very hit an miss on explaining the defaults on our end, its something we try to make sure we do but its manually added when the schemas are written by hand.

**Comment by PlagueHO** [comment]
@BrianFarnhill - cool. Well that is fine with me. I'm happy enough to set the default in the description on the MOF of the resources I maintain. It would be just a one off job really. @johlju - what do you think - is this something you'd be prepared to do for xSQLServer?

**Comment by PlagueHO** [comment]
One thought about adding Example and Markdown.md validation to the Meta.Tests.ps1 file in DSCResources is that it is likely to fail for a number of repos - most in fact. Most repos have a large number of markdown violations as well as a few example errors.

It would be good to get these resolved, but I wouldn't want to make the call on this - @kwirkykat ?

As for the code for auto help documentation, that is actually already in the DSCResources repo (this repo) - but I'm really not sure why it is in here? It really should be in DSCResource.Tests. I'll raise an issue to get it moved.

**Comment by johlju** [comment]
@PlagueHO I usually makesure the defaults are in the schema description for the parameter. So I think we are good there. I will make it work, defaults and length. :)

But this morning another thought hit me. What about [PowerShell-Docs](https://github.com/PowerShell/PowerShell-Docs)? Shouldn't we document over there, or in a repo of our own (DscResources-Docs) with the same process? At least for the HQRM modules.
We then follow the documentation guidelines setup in PowerShell-Docs.

My thought was this. 
1. Deploy doc .md's to the resource module repo (SharePointDsc, xNetworking, xSQLServer).
2. On release this doc .md's goes to master branch of the resource module repo.
3. From master they are deployed to PowerShell-Docs or our own DscResources-Docs repo. (how this is gonna work practically is yet to be determined).
4. In the *-Docs repo they are reviewed and merged, and released according to that Repos release process.

This will make the documentation lag a bit of course. But the documentation for the user will be there they expect it to be. There could be a ling to the doc in the master branch in the resource repo that says "For the most updated documentation, check here" or something.

We could document directly to the *-Docs repo, but then a contributor would need to send in a PR in two repos.

@kwirkykat what are your thoughts on this?

**Comment by johlju** [comment]
@PlagueHO regarding markdown and example validation, that would be good if that could be added using a switch parameter in the AppVeyor.yml.
```
Start-AppveyorTestScriptTask -ExampleValidation -MarkdownValidation
```
Without those, those tests will not run. Would that work?

**Comment by PlagueHO** [comment]
@johlju - regarding pushing HQRM documentation over to PowerShell-Docs, that sounds like a pretty good idea to me, and should be technically possible as the docs are just published as a set of MD files.

As for the Markdown and Example tests, we would only really need to worry about repos that call tests using a straight call to Invoke-Pester (e.g. ones that don't use a test harness). The Test Harness repos are xNetworking and SharePointDsc (and I'd propose implementing the test harness in xSQLServer too). Here is an example of the TestHarness: https://github.com/PowerShell/xNetworking/blob/dev/Tests/xNetworking.TestHarness.psm1

Repos using the TestHarness are have tests run by:
```powershell
Start-AppveyorTestScriptTask -Type Harness ....
```
For these repos the harness could control whether or not to run them, but I'd say, these repos are all very clean and should run the Markdown and Example tests anyway.

But testing in older non test harness repos are called by a straight Invoke-Pester - which will run every file *.tests.ps1. But we could ```tag``` the Markdown and Example tests as "Makrdown" and "Examples" or something along those lines. Any repo that can't handle these tests (e.g. are in a bad state) could be run with:
```powershell
Invoke-Pester -ExcludeTag Markdown,Examples
```

Once these repos are fixed up the or have a harness added then we could start executing these tests.

Either way, very minor changes would have to be made to legacy repos:
Invoke-Pester -ExcludeTag Markdown,Examples

Thoughts?

**Comment by johlju** [comment]
@PlagueHO That sounds like a good idea to tag the tests and exclude them!
I can't see a way to do this without changing all repos who do not use the Test Harness, we don't know which will fail so we have to change all. But, as you say, it is an easy enough change.

**Comment by johlju** [comment]
Regarding pushing HQRM documentation over to PowerShell-Docs then I think we should not add that documentation to the wiki. I think we should not duplicate the documentation.

**Comment by kwirkykat** [comment]
@PlagueHO @johlju Just posted a question to the team about the length limit of Description in the mof files. There are certain characters that don't work in the mof file (I think back or forward slashes had a problem), but that is work-aroundable.

If you want to add markdown and example tests to Meta.Tests, that would be great, but it would be best to implement it like we have the PSScriptAnalyzer rules where they only spit out warnings (instead of test failures) for all the 'x' modules. You could turn the tests on for the HQRMs and have them actually fail for those though.

Moving (rather than duplicating) the main DSC Resource Kit documentation (because I'm not sure why we would move only the HQRM guidelines) over to PowerShell-Docs is an interesting idea. Let me run it by @joeyaiello and @zjalexander to see what they think

**Comment by kwirkykat** [comment]
@PlagueHO Response about the mof file length limit: "it's implementation dependent but the mof standard itself seems to consider it to have no max length". So putting documentation into the mof should be fine 👍

**Comment by PlagueHO** [comment]
@kwirkykat - awesome! That is good news. Thanks for finding that out for us.

**Comment by PlagueHO** [comment]
Closing this issue because it has been answered.
