### ISSUE TITLE
README.md in Resource folders

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#183]
In the SharePointDsc module, each resource has a README.md. That is probably specific to SharePointDsc right now. But if it has a good purpose then maybe that is something we should implement in other resources as well? 
Is that part of the automatic build of the release notes from the .MOF file maybe? 

@BrianFarnhill Can you elaborate on this one?

**Comment by kwirkykat** [comment]
@johlju Yes this is answered in #167, so I'm going to close this as a duplicate.
The pull request with the doc-generator is currently open in #171 and awaiting further review from @KarolKaczmarek
