### ISSUE TITLE
Include overall license here please

### ISSUE THREAD

**Issue by ferventcoder** [PowerShell/DscResources#19]
@vors do you think you could include an overall license here?

**Comment by vors** [comment]
We recommend use MIT license, but there could be cases, where we will allow another license. That's why there is a separate LICENSE file per module in every repo. What's your use case?

**Comment by ferventcoder** [comment]
Making our lawyers comfortable with this repo. It currently has no license. Stating that each module has their own as well is also fine.

**Comment by vors** [comment]
Yes, please tell them that each module has it's own `LICENSE` file at the root. This repo is pretty much for aggregated view and work coordination. It doesn't have any source code itself. Once it would have source code, we will create `LICENSE`, but it still would not apply to sub-modules. Let us know, if it doesn't work for some reasons.

**Comment by ferventcoder** [comment]
I edited my words, I think there is a want for this to also carry a license as it contains documents and code related to combining all of the submodules. What defines as source code in lawyer speak usually relates to a source code repository, which a github repo qualifies as.

**Comment by ferventcoder** [comment]
Without a license this repo is considered non-usable.

**Comment by vors** [comment]
Ok, done.

**Comment by ferventcoder** [comment]
:+1: Thanks!
