### ISSUE TITLE
Please push to the referenced submodules 

### ISSUE THREAD

**Issue by msutter** [PowerShell/DscResources#198]
Hi,

I think you have to push the commits referenced in this repo to your submodules.

Cheers
Marc

fatal: reference is not a tree: 16a05a08d815337efa5950d145d1267680c61095
fatal: reference is not a tree: 1ba0bfd85a99c51753e1f1348217bf2ff3febb2c
fatal: reference is not a tree: c321817b393a5d17d2dfb78e066ff2a1e6dda167
fatal: reference is not a tree: 0a5f4c29e5276cb92748ca6a08be1faa7a5bce0b
fatal: reference is not a tree: 60e254624487c9b445c9e8df6dda20dc35d22a50
fatal: reference is not a tree: 253009776f0ac50ba5fac103ece89d8ef65de240
fatal: reference is not a tree: e9bff6db5b4477413f200d3d5130662dd2e1853d
fatal: reference is not a tree: 7764536155835b41d6a8f3caa86c3f92cdb57851
fatal: reference is not a tree: e8ab0fc14090e71ee699dfb5ac25c17053c71b44
fatal: reference is not a tree: 331ef7062f960ac66a9ea6e3d99f38e0273110dd
fatal: reference is not a tree: e9802ed1039f0593b2cefd5e7ccb20ee98dbab53
fatal: reference is not a tree: 621bf609a87cbf685e6c90339e59edb73680a982
fatal: reference is not a tree: 821696d2cba5ec9ecc6dd5dbbef9092d3fbf7a43
fatal: reference is not a tree: 35c26734b3317c5ec1dc77c5d9cb283028befbc8
fatal: reference is not a tree: ed5299845cf5d536609dc344aa816a914cb9663b
fatal: reference is not a tree: 023dbdd99823e3886f77b9e2c9987268fe950ff3
fatal: reference is not a tree: 964503240bb357745ac2f3acacf4656e63aadb48
fatal: reference is not a tree: b979b12156f0d301fa59a74b534adca66ad5d2f8
fatal: reference is not a tree: 628d41bb3e2439e272879690310ba7646431853b
fatal: reference is not a tree: c9261756f12b5b40e6b98e0d0b37ffc715f03920
fatal: reference is not a tree: f046efbcd2d6eb585e5964a281426cf59d0d99f1
Unable to checkout '16a05a08d815337efa5950d145d1267680c61095' in submodule path 'xDscResources/xChrome'
Unable to checkout '1ba0bfd85a99c51753e1f1348217bf2ff3febb2c' in submodule path 'xDscResources/xCredSSP'
Unable to checkout 'c321817b393a5d17d2dfb78e066ff2a1e6dda167' in submodule path 'xDscResources/xDFS'
Unable to checkout '0a5f4c29e5276cb92748ca6a08be1faa7a5bce0b' in submodule path 'xDscResources/xDSCResourceDesigner'
Unable to checkout '60e254624487c9b445c9e8df6dda20dc35d22a50' in submodule path 'xDscResources/xDnsServer'
Unable to checkout '253009776f0ac50ba5fac103ece89d8ef65de240' in submodule path 'xDscResources/xFirefox'
Unable to checkout 'e9bff6db5b4477413f200d3d5130662dd2e1853d' in submodule path 'xDscResources/xJea'
Unable to checkout '7764536155835b41d6a8f3caa86c3f92cdb57851' in submodule path 'xDscResources/xMySql'
Unable to checkout 'e8ab0fc14090e71ee699dfb5ac25c17053c71b44' in submodule path 'xDscResources/xPSDesiredStateConfiguration'
Unable to checkout '331ef7062f960ac66a9ea6e3d99f38e0273110dd' in submodule path 'xDscResources/xPendingReboot'
Unable to checkout 'e9802ed1039f0593b2cefd5e7ccb20ee98dbab53' in submodule path 'xDscResources/xPhp'
Unable to checkout '621bf609a87cbf685e6c90339e59edb73680a982' in submodule path 'xDscResources/xRemoteDesktopSessionHost'
Unable to checkout '821696d2cba5ec9ecc6dd5dbbef9092d3fbf7a43' in submodule path 'xDscResources/xRobocopy'
Unable to checkout '35c26734b3317c5ec1dc77c5d9cb283028befbc8' in submodule path 'xDscResources/xSCSMA'
Unable to checkout 'ed5299845cf5d536609dc344aa816a914cb9663b' in submodule path 'xDscResources/xSQLServer'
Unable to checkout '023dbdd99823e3886f77b9e2c9987268fe950ff3' in submodule path 'xDscResources/xSharePoint'
Unable to checkout '964503240bb357745ac2f3acacf4656e63aadb48' in submodule path 'xDscResources/xStorage'
Unable to checkout 'b979b12156f0d301fa59a74b534adca66ad5d2f8' in submodule path 'xDscResources/xTimeZone'
Unable to checkout '628d41bb3e2439e272879690310ba7646431853b' in submodule path 'xDscResources/xWebAdministration'
Unable to checkout 'c9261756f12b5b40e6b98e0d0b37ffc715f03920' in submodule path 'xDscResources/xWebDeploy'
Unable to checkout 'f046efbcd2d6eb585e5964a281426cf59d0d99f1' in submodule path 'xDscResources/xWindowsUpdate'

**Comment by msutter** [comment]
Hi Katie,

I fixed this issue on a fork with following code to update the submodules ref.
Maybe it's also usefull for you:

https://github.com/msutter/DscResources/blob/master/update_submodule_to_last_tag.sh

cheers
Marc

**Comment by kwirkykat** [comment]
@msutter Thanks 😄 All submodules should be fixed now
