### ISSUE TITLE
Convert modules documentation from html to README.md in all xDscResources

### ISSUE THREAD

**Issue by vors** [PowerShell/DscResources#2]

**Comment by vors** [comment]
[xComputeManagement](https://github.com/PowerShell/xComputerManagement) doesn't have html description. We need to create one from scratch. cc @joeyaiello , @JKeithB

**Comment by vors** [comment]
Thank @JKeithB, I took docs from technet.

**Comment by tysonjhayes** [comment]
The PowerShellOrg group did this for a number of the resources. [xHyperV](https://github.com/PowerShellOrg/cHyper-V/blob/master/TechNetDocumentation-cHyperV.md) for example. Browse through [their resources](https://github.com/PowerShellOrg) to see which ones have already been done.

**Comment by vors** [comment]
Thank you @tysonjhayes, it's a good suggestion. I would keep it separate for now and convert from existing html / technet documentation, because existing PowerShellOrg resources documentation may contain diffs.

**Comment by vors** [comment]
@joeyaiello thank you for taking care of the major part of it.
