### ISSUE TITLE
Request for resource to create and remove a custom service

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/DscResources#204]
There was a request from the DSC booth at Ignite for a resource that would create and remove custom Windows services given a file path and relevant properties.  I would suggest something like "CustomService" rather than introducing potentially breaking changes in to the existing Service resource.  Filing this as a "help wanted" if someone is interested in taking it on.

**Comment by ArieHein** [comment]
I might be missing something but why cant I use the built-in Service DSC resource for this ?

**Comment by mgreenegit** [comment]
Ah, I stand corrected, on closer inspection I see that this is already covered!  Thank you.
