### ISSUE TITLE
Link to CLA in contribution guidelines

### ISSUE THREAD

**Issue by rhencke** [PowerShell/DscResources#21]
In the contribution guidelines, it states 'If this is your first contribution to DscResources, you may be asked to sign a Contribution Licensing Agreement (CLA) before your changes will be accepted.'.  However, there is no mention of where to obtain the CLA.  This would be helpful so organizations could review this before beginning to create pull requests.

**Comment by vors** [comment]
Thank you, it's a good suggestion. Fixed.
