### ISSUE TITLE
StyleGuideline: Comment-based help

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#219]
Just to make sure. In the StyleGuilde the 'Good' example says comment-based help should look like this.

```
<#
    .SYNOPSIS
        Creates an event

    .PARAMETER Message
        Message to write

    .PARAMETER Channel
        Channel where message should be stored

    .EXAMPLE
        New-Event -Message 'Attempting to connect to server' -Channel 'debug'
#>
```

Shouldn't it be like this? (Contributors write it like this mostly?)

```
<#
    .SYNOPSIS
    Creates an event

    .PARAMETER Message
    Message to write

    .PARAMETER Channel
    Channel where message should be stored

    .EXAMPLE
    New-Event -Message 'Attempting to connect to server' -Channel 'debug'
#>
```

**Comment by johlju** [comment]
@mbreakey3 Did you had a chance to look at this issue yet? If something needs to change I could do it in the open PR I got already. 
Or, if the current 'Good' example is correct, then I need to start changing my comment-based help in the PR's :)

**Comment by mbreakey3** [comment]
The top one is correct.

**Comment by johlju** [comment]
Thank you! Closing this.
