### ISSUE TITLE
StyleGuideline: Add guideline to not use backslash in file paths

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#223]
Since we are starting to enforce this, I think we should have a guideline to not use backslashes in file paths.

Instead we should join paths with `Join-Path`.

**Comment by mbreakey3** [comment]
Agreed, you can go ahead and make this change if you get a chance. I think you could add it to #217 since that hasn't been merged yet.

**Comment by dcrreynolds** [comment]
I understand that Join-Path is a really powerful tool especially when working with different providers. I'm not sure I am following how not using any backslashes provides value. Many of the paths in resources are very simple, relative, and easy to follow, using Join-Path would add complexity without changing the result.

**Comment by mbreakey3** [comment]
The main reason is so that these resources could eventually be used cross-plat in the future.

**Comment by dcrreynolds** [comment]
Ah, right, wasn't thinking about cross-plat support. That will be valuable for the resources that are applicable.

**Comment by johlju** [comment]
@mbreakey3 I will add this to #217

**Comment by johlju** [comment]
@mbreakey3 The PR is updated with this guideline as well 😄

**Comment by mbreakey3** [comment]
Can you add that that PR Fixes this issue?

**Comment by johlju** [comment]
Done! Did it in the commit message, so forgot to do it in the PR. But all done now. Should now auto-close both issues that the PR fixes.
