### ISSUE TITLE
Review process: There is contradicting procedures on how to review discussions should be handled

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#225]
in Maintainers.md the following states to leave the comments with an ending LGTM.

> DO reply to new issues and pull requests (while reviewing PRs, leave your comment even if everything looks good - simple "Looks good to me" or "LGTM" will suffice, so that we know someone has already taken a look at it).

In CONTRIBUTING.md is says that one should resolve the discussion by acknowledge it. Thus hiding it.

> When the author replies or makes the changes you requested and you are satisfied with the changes/reply, you will need to resolve the discussion. You can do this in one of two ways:
> 1. Click the Acknowledge button on the comment

I would prefer the later, the procedure in CONTRIBUTING.md.

**Comment by mbreakey3** [comment]
So the first part is referring to commenting on the whole change/PR being approved (add LGTM once you are ready for the PR to be merged). The second is referring to an individual comment (Make sure that all of your comments are resolved before merging)

**Comment by johlju** [comment]
Ah I see... Misread that because of the 'while reviewing' :)
Maybe we could rephrase that then? Suggestion:

>DO reply to new issues and pull requests (after your review and everything looks good to you, leave a comment like "Looks good to me" or "LGTM" so we know that someone has looked at it and approved).

Or

>DO reply to new issues and pull requests
>DO review pull requests (after your review and everything looks good to you, leave a comment like "Looks good to me" or "LGTM" so we know that someone has looked at it and approved).

**Comment by mbreakey3** [comment]
Yes - that sounds good. Slight change:
>DO reply to new issues and pull requests (after you finish reviewing and everything looks good to you, leave a comment like "Looks good to me" or "LGTM" so we know that someone has looked at it and approved it).

**Comment by johlju** [comment]
I sent in a PR for this change in PR #226 😄
