### ISSUE TITLE
Add CSV import module to AuditPolicyDsc resource

### ISSUE THREAD

**Issue by athaynes** [PowerShell/DscResources#227]
@zjalexander 
I have a new module ready to submit that takes advantage of the new security cmdlets released for nano server that I would like to add to the existing Audit Policy resource.

**Comment by zjalexander** [comment]
cc @kwirkykat @mbreakey3

**Comment by mbreakey3** [comment]
@athaynes - You can open an issue in the AuditPolicyDsc repo for this enhancement and then open a PR in AuditPolicyDsc now that it's published

**Comment by kwirkykat** [comment]
Closing as external since this is open in PowerShell/AuditPolicyDsc#28 now
