### ISSUE TITLE
Does PowerShell DSC provide feature that the user can review execution results of client nodes by a GUI way?

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#231]
One quick question: Does PowerShell DSC provide a feature that the user can review execution results of client nodes by a GUI way?Thanks in advanced.

**Comment by KosherSalt** [comment]
There's not a dedicated GUI tool that I know of. However, you can see the results in the event viewer: Applications and Services Logs/Microsoft/Windows/Desired State Configuration

For more information, see "Where are DSC event logs?" in the troubleshooting docs https://msdn.microsoft.com/en-us/powershell/dsc/troubleshooting

**Comment by chancein007** [comment]
This post(https://blogs.msdn.microsoft.com/powershell/2016/12/06/wmf-5-1-releasing-january-2017/) mentioned that WMF 5.1 RTM will be released on Jan-2017.  Any idea what day in January it will be available?

**Comment by DevOpsTrawler** [comment]
In regards to your question about a Powershell DSC GUI.
I know of 2 one commercial offering (Otter by Indeo) and the other is a new open source effort (Stephen Owen a Powershell MVP). 
We are also building a Powershell DSC GUI application and we are in beta looking for early adopters if you are interested [http://devopstrawler.com/]()
