### ISSUE TITLE
Does PowerShell DSC provide the ability to dynamically match the client nodes by some filter to execute MOF file?

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#232]
Does PowerShell DSC provide the ability to dynamically match the client nodes by some filters or roles to execute MOF file? Or Does PowerShell DSC only support one mof file which UUID can only be executed by a specified client node? Thanks in advanced.

**Comment by chancein007** [comment]
It's perfectly legal to configure multiple computers' LCMs to have the same ConfigurationId. When you do so, they'll all be pulling the exact same configuration MOF from the pull server.

**Comment by grayzu** [comment]
Although you can technically use ConfigurationId as you state, we have introduced ConfigurationNames in WMF 5 which is built for doing what you are describing. With ConfigurationNames, you create a configuration that represents a role and then configure multiple nodes to use that role. See documentation here: https://msdn.microsoft.com/en-us/powershell/dsc/pullclientconfignames

**Comment by chancein007** [comment]
Thanks for your reply!!!
