### ISSUE TITLE
File resource, support URI as sourcepath

### ISSUE THREAD

**Issue by kittholland** [PowerShell/DscResources#234]
It would be nice if the file resource could accept a URI as the sourcepath. This would validate that the DestinationPath the same as the file at the URI, if not it would download and copy it to the DestinationPath location.

I can't seem to find the home of the builtin File resouce on github however.

**Comment by kilasuit** [comment]
Isnt this what xRemoteFile does from the xPSDesiredStateConfiguration resource?

**Comment by kittholland** [comment]
Yes, it appears that does, I guess based on the amount of extra parameters they support (user agent, authentication etc) there is reasonable justification to have it broken out. 

Thanks for pointing that out @kilasuit
