### ISSUE TITLE
Discussion: How to translate logs when resources are localized

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#236]
When a user recently submitted an issue over at xSQLServer, and added an output log mostly in Spanish I had an epiphany. The reason the log was still partly in English was because the resource are not yet localized in Spanish. So the verbose output in the logs contained the English localization strings.
When that resource is localized to Spanish and other languages I think we need some way to "translate" the logs (other than a online translate service). 

I'm glancing over at PSDSCResource now, because I'm about to change the localization over at xSQLServer. But looking at the code I see there are no unique way to distinguish a particular localized string (except the key). 

Example snippet from MSFT_WindowsOptionalFeature:
```
ConvertFrom-StringData @'
    GetTargetResourceStartMessage = Started Get-TargetResource on the {0} feature.
'@

Write-Verbose -Message ($LocalizedData.GetTargetResourceStartMessage -f $Name)
```

Should we have a "unique ID" in each localized string? Or should we output the key `GetTargetResourceStartMessage` as well? Or is there a more clever way of doing this?

**Comment by PlagueHO** [comment]
Hi @johlju - don't we just create a new localization folder at the same level as the en-US (e.g. es-AR) and just load a localized copy of the *.strings.psd1 file in that folder?

Then the code at this position loads the appropriate *.strings.psd1 file:
https://github.com/PlagueHO/PSDscResources/blob/dev/DscResources/MSFT_WindowsOptionalFeature/MSFT_WindowsOptionalFeature.psm1#L7

Or are you meaning that we should add something like "en-US" to every entry in the strings file to show what localization file it came from. E.g.
```powershell
ConvertFrom-StringData @'
    GetTargetResourceStartMessage = Started Get-TargetResource on the {0} feature (en-US).
'@
```
Is this what you mean?

If that was the case it might be better to create a generic function to return a message that adds the localization "unique ID" to the string rather than modifying all the strings files.

**Comment by johlju** [comment]
You are almost there. I'm gonna try to explain better. :smile:

You right that we create a new localization folder. Let say we localize the resource to Swedish. So we create a new folder 'sv-SE'. In that folder we localize a copy of the *.strings.psd1. It might look like this.

```
ConvertFrom-StringData @'
    GetTargetResourceStartMessage = Startade Get-TargetResource för komponenten {0}.
'@
```

The verbose output might look like this (not an accurate example, I just mocked an example from top of my head)
```
FÖRTYDLIGANDE: [SQLTEST4]: [[WindowsOptionalFeature]MinKomponent] Startade Get-TargetResource för komponenten NET-Framework-Core.
```

When a non-swedish speaking needs to understand the log, we need a way to "translate" the text 
'Startade Get-TargetResource för komponenten NET-Framework-Core.'
into
'Started Get-TargetResource on the {0} feature.'.

Either we use the same "Unique ID" for the string in each localized file.
```
ConvertFrom-StringData @'
    GetTargetResourceStartMessage = Started Get-TargetResource on the {0} feature (ID:WOF0001).
'@

ConvertFrom-StringData @'
    GetTargetResourceStartMessage = Startade Get-TargetResource för komponenten {0} (ID:WOF0001).
'@
```

Or we output the key in the verbose output, which we can use to search for in the english localization.
```
FÖRTYDLIGANDE: [SQLTEST4]: [[WindowsOptionalFeature]MinKomponent] Startade Get-TargetResource för komponenten NET-Framework-Core (Key: GetTargetResourceStartMessage).
```

Either of these ways would make it possible to identify the string we need to search for in the english localization when reading logs.
Maybe if we have an standard way of doing this, we could just run the log entries thru a helper function and get a "translated" log. 

But maybe there is a better way of doing this. 😄

**Comment by PlagueHO** [comment]
@johlju - Oh I see! I'm with you now. So to make sure I understand:

This is a way for a user to look in the DSC logs, identify a message (english or non-english), see the code (e.g. ID:WOF0001) and then use that to look it up in the *.string.psd1 file. This will lead them to the actual string name (e.g. GetTargetResourceStartMessage) which will then be used to identify where in the DSC Resource the error actually occurred.

Sounds like a great idea to me!

**Comment by johlju** [comment]
@PlagueHO That would be another benefit from this that I did not thought of. Easier for the user to debug them self. 😄 

But also, it would be easier for contributors reading issues, or support services, to find out what the error actually says. With an ID (of some sort) after the each verbose, warning and error message (for each localized string) this would be easy to figure out what the text says in the users own language.

This log in Spanish, the verbose text parts that are in english will be translated at some point, making it less easy to read unless you know Spanish (or use a online translating service). :)

_Note: Not an accurate log. I mocked this to illustrate my point._  
```
DETALLADO: Realice la operación 'Invocar método de CIM' con los parámetros siguientes, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
DETALLADO: Se recibió una llamada de método de LCM desde el equipo DES001 con el SID de usuario S-1-5-21-3370056077-3368664693-1737765451-1238.
DETALLADO: [SERVIDOR1]: LCM: [ IniciarEstablecer]
DETALLADO: [SERVIDOR1]: LCM: [ IniciarRecurso ] [[xSQLServerScript]SqlEstablecer]
DETALLADO: [SERVIDOR1]: LCM: [ IniciarProbar ] [[xSQLServerScript]SqlEstablecer]
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Unloading SQLPS module.
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] SQLPS module changes CWD to SQLSERVER:\ when loading, pushing location to pop it when module is loaded.
DETALLADO: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] 2016-12-21_13-12-54: Importing SQLPS module.
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Called Initialization method
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Starting extension DAC
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Starting extension DataCollection
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Starting extension SQLPolicy
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Starting extension Utility
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Starting extension SQLRegistration
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Starting extension SQLSERVER
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Starting extension SQL
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Starting extension SSIS
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Starting extension XEvent
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Starting extension DatabaseXEvent
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Starting extension SQLAS
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] ItemExists: SQLSERVER:
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] ItemExists: SQLSERVER:
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] SQLPS module imported.
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Popping location back to what it was before importing SQLPS module.
DETALLADO: [SERVIDOR1]: LCM: [ FinalizarProbar ] [[xSQLServerScript]SqlEstablecer] en 0.5780 segundos.
El recurso de DSC de PowerShell MSFT_xSQLServerScript generó uno o más errores de no terminación al ejecutar la funcionalidad de Test-TargetResource. Estos errores se registran en el canal
ETW llamado Microsoft-Windows-DSC/operativo. Consulte este canal para obtener más detalles.
+ CategoryInfo : InvalidOperation: (:) [], CimException
+ FullyQualifiedErrorId : NonTerminatingErrorFromProvider
+ PSComputerName : SERVIDOR1

La función SendConfigurationApply no se completó correctamente.
+ CategoryInfo : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
+ FullyQualifiedErrorId : MI RESULT 1
+ PSComputerName : SERVIDOR1

DETALLADO: La operación 'Invocar método de CIM' se completó.
DETALLADO: El tiempo que tarda el trabajo de configuración en completarse es de 0.688 segundos

```

**Comment by johlju** [comment]
WIth an ID after each localized string, it could look like this.

```
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Unloading SQLPS module (ID: SSS001).
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] SQLPS module changes CWD to SQLSERVER:\ when loading, pushing location to pop it when module is loaded. (ID: SSS002)
DETALLADO: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] 2016-12-21_13-12-54: Importing SQLPS module. (ID: SSS003)
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] SQLPS module imported. (ID: SSS004)
DEPURACIÓN: [SERVIDOR1]: [[xSQLServerScript]SqlEstablecer] Popping location back to what it was before importing SQLPS module. (ID: SSS005)
DETALLADO: [SERVIDOR1]: LCM: [ FinalizarProbar ] [[xSQLServerScript]SqlEstablecer] en 0.5780 segundos.
````

**Comment by johlju** [comment]
Okay, so I have started translating xSQLServer into Swedish. I thought I submit a few verbose logs from real life, not just mockups.

I thinking of adding unique ID to every localized string, as mentioned above, when resources become "localized enabled".

This is the verbose log from xSQLServerSetup (when Test-TargetResource is run). _Stripped it from the the first columns to save white space)_
```
[[xSQLServerSetup]InstalleraSQL2016]
[[xSQLServerSetup]InstalleraSQL2016] Använder sökväg '\\fs01.shamn.se\images\SQL2016RTM-ENT\setup.exe'.
[[xSQLServerSetup]InstalleraSQL2016] Letar efter Database Engine funktionen.
[[xSQLServerSetup]InstalleraSQL2016] Database Engine funktionen hittad.
[[xSQLServerSetup]InstalleraSQL2016] Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM Win32_Service WHERE Name = 'MSSQL$SQL2016','q
ueryDialect' = WQL,'namespaceName' = root\cimv2'.
[[xSQLServerSetup]InstalleraSQL2016] Operation 'Query CimInstances' complete.
[[xSQLServerSetup]InstalleraSQL2016] Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM Win32_Service WHERE Name = 'SQLAgent$SQL2016'
,'queryDialect' = WQL,'namespaceName' = root\cimv2'.
[[xSQLServerSetup]InstalleraSQL2016] Operation 'Query CimInstances' complete.
[[xSQLServerSetup]InstalleraSQL2016] Letar efter funktionen Replication (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL13.SQL2016\ConfigurationState).
[[xSQLServerSetup]InstalleraSQL2016] Replication funktionen hittades inte.
[[xSQLServerSetup]InstalleraSQL2016] Letar efter Data Quality Client funktionen (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\130\ConfigurationState).
[[xSQLServerSetup]InstalleraSQL2016] Data Quality Client funktionen hittades inte.
[[xSQLServerSetup]InstalleraSQL2016] Letar efter Data Services Client funktionen (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\130\DQ\*).
[[xSQLServerSetup]InstalleraSQL2016] Data Quality Services funktionen hittades inte.
[[xSQLServerSetup]InstalleraSQL2016] Ansluten till SQL instans 'SQLTEST12\SQL2016'.
[[xSQLServerSetup]InstalleraSQL2016] Klustrad instans hittades inte.
[[xSQLServerSetup]InstalleraSQL2016] Letar efter Full-text funktionen.
[[xSQLServerSetup]InstalleraSQL2016] Full-text funktionen hittades inte.
[[xSQLServerSetup]InstalleraSQL2016] Letar efter Reporting Services funktionen.
[[xSQLServerSetup]InstalleraSQL2016] Reporting Services funktionen hittades inte.
[[xSQLServerSetup]InstalleraSQL2016] Letar efter Analysis Services funktionen.
[[xSQLServerSetup]InstalleraSQL2016] Analysis Services funktionen hittades inte.
[[xSQLServerSetup]InstalleraSQL2016] Letar efter Integration Services funktionen.
[[xSQLServerSetup]InstalleraSQL2016] Integration Services funktionen hittades inte.
[[xSQLServerSetup]InstalleraSQL2016] Letar efter Documentation Components funktionen (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\130\ConfigurationState).
[[xSQLServerSetup]InstalleraSQL2016] Documentation Components funktionen hittades inte.
[[xSQLServerSetup]InstalleraSQL2016] Letar efter Client Connectivity Tools funktionen (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\130\Tools\Setup\Client_Components_Full).
[[xSQLServerSetup]InstalleraSQL2016] Client Connectivity Tools funktionen hittades inte.
[[xSQLServerSetup]InstalleraSQL2016] Letar efter Client Connectivity Backwards Compatibility Tools funktionen (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\130\Tools\Setup\Client_Com
ponents_Full).
[[xSQLServerSetup]InstalleraSQL2016] Client Connectivity Backwards Compatibility Tools funktionen hittades inte.
[[xSQLServerSetup]InstalleraSQL2016] Letar efter Client Tools SDK funktionen (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\130\Tools\Setup\Client_Components_Full).
[[xSQLServerSetup]InstalleraSQL2016] Client Tools SDK funktionen hittades inte.
[[xSQLServerSetup]InstalleraSQL2016] Letar efter Master Data Services (MDS) funktion (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\130\ConfigurationState).
[[xSQLServerSetup]InstalleraSQL2016] Master Data Services (MDS) funktionen hittades inte.
[[xSQLServerSetup]InstalleraSQL2016] Funktioner funna: SQLENGINE
[[xSQLServerSetup]InstalleraSQL2016]  in 0.8600 seconds.
``` 

This is the verbose log from xSQLServerNetwork (when Test-TargetResource is run). Helper functions are translated only so that's why some are in english still. _Stripped it from the the first columns to save white space)_
```
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] 
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] SQL major version är 13.
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] SQL major version är 13.
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] Skapar applikationsdomän 'xSQLServerHelper'.
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] Laddar samling 'Microsoft.SqlServer.Smo, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'.
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] Laddar samling 'Microsoft.SqlServer.SqlWmiManagement, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'.
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] Getting network protocol [Tcp] for SQL instance [SQL2016].
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] Reading current network properties.
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] InstanceName = SQL2016
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] IsEnabled = True
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] TcpPort =
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] ProtocolName = Tcp
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] TcpDynamicPorts = 49822
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] Återställer applikationsdomän 'xSQLServerHelper'.
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] Comparing desired state with current state.
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration] In desired state.
[[xSQLServerNetwork]SQL2016-Nätverkskonfiguration]  in 0.5630 seconds.
```

**Comment by johlju** [comment]
Is there any ideas of the ID we should use? Or is the following format okay to use? Looking for the standard so I don't have to change later 😉 

**Suggestion**

Format: `(ID:yyyyZZZZ)`

'yyyy' - is the prefix, the concatenation of every first letter of every word in the resource name.
'ZZZZ' - The suffix is a serial number starting from '0001'.

Example en-US: `Detecting Database Engine feature. (SS:ID0001)`
Example sv-SE: `Letar efter Database Engine funktionen. (SS:ID0001)`

Example of prefixes:

Module | Resource | Localized String ID prefix (xxxx)
--- | --- | ---
PSDscResources | GroupResource | GR
PSDscResources | Windows Optional Feature | WOF
xSQLServer | xSQLServerSetup | SSS
xSQLServer | xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership | SSAOAGDM
xNetworking | xDnsClientGlobalSetting | DCGS
xNetworking | xFirewall | F
xCertificate | xPfxImport | PI
xCertificate | xWaitForCertificateServices | WFCS

**Comment by PlagueHO** [comment]
That looks OK to me.

So to confirm, we'll "hard code" these into the strings PSD1 files?

**Comment by johlju** [comment]
Updated my previous comment so the example strings had the correct format for the ID.

Yes, my thought is to hard-code them. I don't see another option than to hard-code them. But if anyone has another option, please feel free to share. 😄 

Since this is hard-coded. We could add a couple of test to [this issue](https://github.com/PowerShell/DscResource.Tests/issues/145)

Tests:
* All localized strings should have an ID.
* No string ID can be equal to any other string ID in the same file.
* The same string ID's should exists on the corresponding key in all localized language files.

**Comment by johlju** [comment]
If we don't want to hard code the ID in strings, we could create a helper function that builds the localized string, and then the ID could be the Key of the string which is added to the returned localized string. 
Then there is no need to add more text to strings. And it is dynamic.

**Comment by PlagueHO** [comment]
I'm OK with hard coding. Because I think this will make it easier to add/remove messages. E.g. if we remove a message we don't want all the ID's to change. Once a message has been defined the ID should stay the same (even if we remove or add new messages).
