### ISSUE TITLE
Community Call Comments, Questions, and Feedback (January 18)

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/DscResources#241]
This issue is open for the community to submit comments, questions, or feedback from the DSC Resource Kit community call on January 18, 2017 9-9:30 AM.

The agenda for the call is available on GitHub [here](https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/01-18-17/Agenda.md).

**Comment by PlagueHO** [comment]
Doh! Sorry I missed this! :cry:

**Comment by RafDelgadoUK** [comment]
Hi @kwirkykat,

Where can I find the link to the call so join the next on please? :)

Kind Regards,

Raf

**Comment by LiamFisher92** [comment]
I had some family stuff to attend to. Typical. I've had this penciled in my calendar for ages! 😢

**Comment by kwirkykat** [comment]
@RafDelgadoUK Links for the next community call are now posted [here](https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/03-01-17/Agenda.md)
