### ISSUE TITLE
[Discussion] Move DSCResources.DocumentationHelper to DSCResource.Tests Repo

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#244]
Is DSCResources the best location for the DSCResources.DocumentationHelper code? I think locating it here adds extra complexity and overhead downloading this repository.

E.g. every build requires both DSCResource.Tests and DSCResources to be cloned into the repo folder and then manipulated.

Because we are moving shared code like AppVeyor.psm1 into DSCResources.Tests repository it would make things a lot easier if all shared code for builds, tests and publishing were in this same repo rather than scattered across two repos. As AppVeyor.psm1 will actually be responsible for making the calls to the DocumentationHelper code, moving it shouldn't affect any repositories. DocumentationHelper could also be retained in DSCResources temporarily while the transition was made (e.g. changes made to xNetworking and SharePointDsc and any other resources using it - are there any?).

I feel it would make more sense to move it to DSCResource.Tests.

If this is workable then I could include a copy with the changes I'm making for https://github.com/PowerShell/DscResources/issues/205

My 2c!

**Comment by johlju** [comment]
I agree moving it to DSCResource.Tests.

**Comment by PlagueHO** [comment]
This has now been moved over to DSCResource.tests in https://github.com/PowerShell/DscResource.Tests/pull/90

@kwirkykat, @BrianFarnhill - are you OK with this folder being removed from this repo? It is now available in DSCResource.tests.

**Comment by kwirkykat** [comment]
@PlagueHO Yes I'm good with the removal from this repo

**Comment by BrianFarnhill** [comment]
@PlagueHO Yea I don't mind, I recall asking the question up front about where it should go and it was decided that "its not a test" so lets not put it there, but at the end of the day I really don't mind :)

**Comment by PlagueHO** [comment]
This has now been completed. But I think we still need to remove it from this repo once @BrianFarnhill has updated SharePointDsc to use the DSCResources.tests copy.

**Comment by PlagueHO** [comment]
@kwirkykat - One query on this.

There is some documentation and examples of usage of the Documentation Helper in the DSCResources.DocumentationHelper folder. Should this documentation remain in this repo or moved over to DSCResource.tests?

**Comment by kwirkykat** [comment]
@PlagueHO I think it should move over to DSCResource.Tests

**Comment by BrianFarnhill** [comment]
@PlagueHO @kwirkykat OK I'll commit some time either next week or at latest the week after to get SharePointDsc and OfficeOnlineServerDsc moved over to the new locations and we can get it sorted from there :)

**Comment by PlagueHO** [comment]
@BrianFarnhill - I'm happy to submit a PR to the OfficeOnlineServerDsc to bring it over to use the shared code in DSCResource.tests and also add the CodeCov.io support. I've updated 5 repos now with this change. You could then use that as a guide of what to change in SharePointDsc (it shouldn't be too much because it's all based around your code anyway).

**Comment by PlagueHO** [comment]
@kwirkykat - Ok cool. I'll submit a PR to that repo with the Docs and Examples and once that is through will submit a PR to remove it from here. Thank you!

**Comment by BrianFarnhill** [comment]
@PlagueHO I've got a PR open for the changes to SharePointDsc - actually ended up being way easier than I thought, so good job on it dude! I'll get OfficeOnlineServerDsc done shortly though as I need to write the doco for that one, so its on my todo list for next week.

**Comment by PlagueHO** [comment]
@BrianFarnhill - cool! Really glad it wasn't too difficult to move over to! I'll wait to hear back from you before doing anything more on this one (bit short on time this week anyways). Cheers mate!

**Comment by PlagueHO** [comment]
We've moved the auto documentation helper over to DSCResource.Tests now - is it worth removing from this repo? @BrianFarnhill, does SharePointDsc still use this copy or the one over in DSCResource.Tests?

**Comment by johlju** [comment]
Both [SharePointDsc appveyor.yml](https://github.com/PowerShell/SharePointDsc/blob/dev/appveyor.yml#L26) and [OfficeOnlineServerDsc appveyor.yml](https://github.com/PowerShell/OfficeOnlineServerDsc/blob/dev/appveyor.yml#L25) are using the "harness"-model of DscResource.Tests.

@ykuijs or @NikCharlebois can you confirm that you are no longer dependent on the DscResource.DocumentationHelper folder in the DscResources repo? You are using the one in DscResource.Tests now?

@PlagueHO Can you confirm that none of your "harness"-modules are dependent on DscResource.DocumentationHelper folder in the DscResources repo? You are using the one in DscResource.Tests now?

**If there are no one using this let's remove it from this repo.**

**Comment by PlagueHO** [comment]
@johlju - all good with me - none of the repos I support use the one in DscResources - only DscResource.Tests

**Comment by ykuijs** [comment]
@johlju - For SharePointDsc as well.....we are only using the DscResource.Tests

**Comment by johlju** [comment]
@PlagueHO @ykuijs Thanks! Then we just need someone to send in a PR that removes it from here. 🙂
