### ISSUE TITLE
Add Markdown & Example validation tests as well as AppVeyor.psm1 to DSCResource.tests

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#246]
Hi @tysonjhayes , @johlju , @kwirkykat and @BrianFarnhill 

I thought I'd make an attempt to combine the following discussion threads into a single discussion and proposal:
https://github.com/PowerShell/xNetworking/issues/177
https://github.com/PowerShell/DscResources/issues/244
https://github.com/PowerShell/DscResources/issues/205
https://github.com/PowerShell/DscResources/issues/180

The proposal:
1. DSC Team creates a new Repo DSCResources.HQRM (or whatever name the community things is appropriate) that is an identical copy of DSCResources.Tests
2. A PR to this new DSCResources.HQRM repo with the changes I've been making to DSCResources.Tests (all of this code is already pretty much complete anyway). These changes are:
   a. Markdown validation tests included in Meta.tests.ps1 (this includes code for using NPM to install Gulp etc).
   b. Example validation tests included in Meta.tests.ps1
   c. AppVeyor.psm1 that can be used by the newer style repos (SharePointDsc, xNetworking, soon xStorage and xSQLServer) as well as the older ones.
   d. The three modules from the DscResource.DocumentationHelper folder in this repo (https://github.com/PowerShell/DscResources/tree/master/DscResource.DocumentationHelper/Modules).
3. I or someone else issue PR's to xNetworking and SharePointDsc to convert them over to use the shared code in the new DSCResources.HQRM repo.

This allows repos to move to the newer repo over time when and if they choose to. It also means that only repos choosing to use the new repo will be affected by the larger set of tests (markdown, examples). 

This would also all the PSSA warnings to be flagged as errors for the HQRM repos as well (all are now fixed in xNetworking- I haven't checked SharePointDsc though).

Wiki and Automatic help generation will still be optional (call AppVeyor.psm1 with an option to generate Wiki/Help etc). It should be encouraged to make use of the newer methods as it only took me about an hour to convert a xStorage to use all of the above. Larger or less well organized repos might take longer - but don't have to change over at all.

What ever happens going forward I think it would be good to continue all discussion in this thread instead of it being scattered (my fault I'm sorry). Thanks all!

**Comment by kwirkykat** [comment]
@PlagueHO I really don't want to have an entire repository of duplicated code. It's already been hard to manage the duplicate PRs between xPSDesiredStateConfiguration and PSDscResources. I'd rather we just merge the code into DscResource.Tests and add logic to run all tests on HQRM modules and then a subset of tests on experimental modules. The logic can just go by the name of the repo (whether it ends with 'Dsc' or starts with 'x')

**Comment by PlagueHO** [comment]
@kwirkykat - I can completely understand that! :grin:

So keeping everything in DSCResource.Tests is fine with me.

Using "x" to identify repos that should execute the Examples and MD tests seems like a pretty good idea. But it does mean renaming the repos that want to adopt these tests - which I think you're intending to do anyway when the meet HQRM - is that correct?

What we could do is include the Examples and MD tests in xNetworking until it is ready to rename (I actually think it is ready to move to HQRM - I was meaning to ask you about how we do that). 

SharePointDsc can be changed to use the Examples and MD tests in DSCResources.Tests (because it is not an "x" repo). Is the plan to cause PSDscResources to use this as well?

What do you think of this idea?

**Comment by PlagueHO** [comment]
@kwirkykat - one other possible way of doing this would be to ask the Pester team for a new feature: "Optional Tests".

The exact mechanism that was implemented for this would be up to the Pester team, but the gist would be:
Add a new "-Optional" parameter to the ```Describe``` block that would indicate tests that were never run unless specifically requested by something like: ```Invoke-Pester -IncludeOptional [<name>[]]``` - you could specify an array of optional tests to run. Any tests that are not flagged as ```Optional``` would always be run.

But if that was implemented then we could easily add new tests to the shared tests and repos could "opt-in" to running them when they were ready. We could then just "opt-in" the Invoke-Pester in the Test Harness in xNetworking and SharePointDsc.

Worth pursuing?

Sorry for all the info dump on this particular change, but I'd really like to bring xStorage, xCertificate and xDFS up to using these new tests and documentation/wiki stuff and would rather not replicate the code in each of the repos. And I expect going forward newer tests will be added and I reckon it would be good to not go through the same problems each time :grin:

**Comment by mbreakey3** [comment]
You can actually already pretty much do this with the [-Skip](https://github.com/pester/Pester/wiki/It) parameter.

**Comment by PlagueHO** [comment]
@mbreakey3 - I had no idea! That is awesome. That does look like it would do exactly what is required. Thank you for pointing this out :grin:

**Comment by kwirkykat** [comment]
@mbreakey3 @PlagueHO You can only put -Skip on individual It's not on Contexts or Describes. Which doesn't mean we can't use it. There just might be better alternatives. Like maybe we could use the existing tags feature on Describes/Contexts to run only certain ones for experimental/high quality modules.

**Comment by PlagueHO** [comment]
@kwirkykat - That is a pity about the -skip.

I did think about using the -tag parameter on the Describe block, but the problem with this approach is that you can only "ExcludeTags" from the Invoke-Pester - e.g. it is an "Opt-out" rather than an "Opt-in". This would mean that we'd have to go through every "x" repo and add ```-ExcludeTag``` to the ```Invoke-Pester``` - this wouldn't be a huge problem I think, but I was trying to avoid the need for this.

If we did go for this approach (the "Tag" approach), we could just set the ```-ExcludeTag Example,Markdown``` in the AppVeyor.psm1 for non-harness repos and convert each repo over to using AppVeyor.psm1. That shouldn't be a lot more work, but it is changing more lines of code - but if we're planning on doing this AppVeyor.psm1 change anyway...

But at the end of the day, totally your call on the approach here.

**Comment by PlagueHO** [comment]
@kwirkykat - I don't suppose you've had any time to think about what you'd like me to do with this one? I'd love to get my changes merged into DSCResources.tests, but I don't want to do anything that will add tech debt for you guys.

**Comment by kwirkykat** [comment]
@PlagueHO I like your suggestion where we just have the -ExcludeTag on the call to Invoke-Pester within AppVeyor.psm1 for the experimental repos. So that's what I would go with.

Not all HQRMs have a test harness though and it seems like some experimental modules may already have one? So I guess there are four logical tracks then HQRM with test harness, HQRM without test harness, experimental with test harness, and experimental without test harness... Is it easy to tell whether a repo has a test harness or not? Are they all named the same or in the same place? None of the repos outside the ones you, @BrianFarnhill and @johlju  have been working on have a test harness.

**Comment by PlagueHO** [comment]
@kwirkykat - okay cool! Sounds good. Consider it done.

**Comment by johlju** [comment]
@kwirkykat If they got the test harness they also changed the layout of folders, so they have a Modules folder in the root of the module. This is only done in xNetworking and SharePointDsc so far I think.
But looking at @PlagueHO's PR https://github.com/PowerShell/DscResource.Tests/pull/85 there might not be a need to change the folder structure anymore, which would be good if it is true.
@PlagueHO explains the changes need over at the PR https://github.com/PowerShell/DscResource.Tests/pull/85.

**Comment by PlagueHO** [comment]
HI @kwirkykat - I forgot to clarify, but yep, the change supports all four scenarios you have mentioned, plus is easily changed to support other future behaviors (because each AppVeyor.psm1 function has a "Type" parameter that specifies how it should work).

But as @johlju mentioned, I've tried to document this thoroughly in the PR and in the Readme.md in the DSCResource.tests.

**Comment by PlagueHO** [comment]
I'm closing this one because it has been completed in this PR:
https://github.com/PowerShell/DscResource.Tests/pull/90
