### ISSUE TITLE
Adding functionality to the xDSCWebService resource (might be a 'BREAKING CHANGE')

### ISSUE THREAD

**Issue by svenvanrijen** [PowerShell/DscResources#247]
Hi there,

I would like to discuss with you the following request, as it might end up as a 'BREAKING CHANGE':

I'm currently working on the possibility to have an on premises HTTPS DSC Pull Server being generated by making use of an Azure DSC server.

To make it more clear: I generate an on premises VM which gets its configuration from an Azure DSC server. Purpose is to make this new VM an on premises HTTPS DSC Pull Server, totally automated.

And this last two words are the catch 22, since you currently have to supply xDSCWebService with the valid thumbprint of the SSL certificate you want to be used. But you don't now the thumbprint yet, as it is not being generated at that point in time. The certificate will be requested using the xCertReq resource within the same config file.

So my proposal is to add the value of CertificateGeneratedInSameConfig to the list of possible values for Thumbprint within the xDSCWebService resource (besides an actual Thumbprint and AllowUnencryptedTraffic).
Furthermore it should be possible to supply the value of Subject to the resource when CertificateGeneratedInSameConfig is used. Since this is the key value of the xCertReq resource, based on this value the determined. 

This all can be accomplished by adding a small amount of code to the xDSC (aprox. 7 lines).

Please let me know what you think of it.

Kind regards,
Sven

**Comment by ArieHein** [comment]
Hi Sven,

I've seen your question on powershell.org as well but had no time this week to pitch in.

This sounds like you're trying to augment the purpose of xDSCWebService to play nicely with a very specific scenario and overall that's not what DSC resources are in general. It seems you're more trying to answer the problem DSC has with lack of orchestration tools, and the fact DSC isn't working well with logical evaluation in runtime (only at design time), although bare in mind DSC does support WaitFor and similar so you can chain various DSC resources to act in some sort of workflow and you can use the Script DSC resource to run additional steps before and after the DSC configuration. Remember DSC resources need to be used for immutable state, not necessarily orchestrating.

The scenario you're describing shouldn't be hard to accomplish without any changes to xDSCWebService, simply on the Azure side. Now, I'm not an Azure automation expert but I would look at
options within Azure automation first. 

Overall outside of DSC (this is the orchestration part):
You generate a certificate from the on premise CA, give the thumbnail to Azure DSC to create a MOF file for the on premise DSC pullserver, at the same time transfer the certificate to the on premise DSC pull server and install the certificate.  

Now that stage can be done by a job, a scheduled task, a running script, even an Azure function (you can run PowerShell scripts in it), as it has nothing to do with DSC.

Only then you send the mof file to the on premise DSC pull server and enact it.

This is exactly the same if you would have wanted a Azure DSC to create an on premise IIS webserver
and wanted to use HTTPS, thus would have needed a certificate installed before hand and using its thumbnail or subject 


Just my 0.5cent :)

**Comment by ChrisLGardner** [comment]
I'm running into a similar issue with a few resources, I'm writing a configuration that's using xCertReq to request it's certificate in the same configuration as I'm using that certificate but most resources require the Thumbprint. 

Obviously I'd rather not have two configs or any manual intervention in this process so the solution I'm currently using is to add CertificateSubject as a property on the DSC resource, within the resource I then check if CertificateSubject has a value and if it does I grab the Thumbprint from Cert:\ and set CertificateThumbprint property to have that value. If I do this near the top of the Set and Test then it lets the resource continue to work as normal but still provides the functionality I require. I'm doing a bit more testing on it before I start doing PRs into various resources but I'd be happy to add xDSCWebService to that list of things to look at.

I think a similar approach could be taken here, the only additional property needed is CertificateSubject and then the resource itself handles that.

**Comment by johlju** [comment]
@svenvanrijen Did you get your question answered? How did it work out for you?

**Comment by johlju** [comment]
I'm closing this as not fixed due to lack of response. Please reopen or comment if this was closed in error.
