### ISSUE TITLE
Request to submit xPackageManagement resource

### ISSUE THREAD

**Issue by mattmcnabb** [PowerShell/DscResources#25]
https://github.com/mattmcnabb/xPackageManagement/

This is barebones but I think it's needed. Additional development could add credentials, sources, and providers to the list of properties.

Thanks!

**Comment by vors** [comment]
Thank you for your interest in DSC resources development!

1. There is no need to duplicate common tests in your repo https://github.com/mattmcnabb/xPackageManagement/tree/master/tests

2. Please, write some information in `README.md`.

**Comment by mattmcnabb** [comment]
I have removed the common tests and updated the readme file. thanks!

**Comment by vors** [comment]
Thank you! 
@jianyunt is developing package https://github.com/PowerShell/PackageManagementProviderResource. Is it the same?

**Comment by jianyunt** [comment]
Looks similar to me. mattmcnabb, possibly can we merge them?

**Comment by mattmcnabb** [comment]
May not be a need to merge as yours looks much more developed. Not sure how I missed this! I'll take a look and see if there is anything I can contribute.

**Comment by jianyunt** [comment]
Thanks! Welcome to contribute it.

**Comment by mattmcnabb** [comment]
Thanks Sergei! I'll close this issue as my work was futile! :(
