### ISSUE TITLE
Clarify "Script, Environment and Global Variable Names Include Scope" Rule

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#250]
@Johlju and I have been [having a discussion](https://reviewable.io/reviews/powershell/xcertificate/48#-KdofZEwr17WePdsntxc) around the meaning of [this rule](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#script-environment-and-global-variable-names-include-scope).

Could we clarify this? Does it mean we need to add scope to every variable? Or just the variables that are defined as $script, $env or $global?

E.g. Should $local scope be specified for every variable.

I think we should only be specifying scope if a variable needs to be anything but $local

**Comment by mbreakey3** [comment]
Yes. Just $script, $env, and $global variables should be specified. $local does not need to be added.

**Comment by PlagueHO** [comment]
Yep, closing it! Thanks @johlju
