### ISSUE TITLE
Community Call Comments, Questions, and Feedback (March 1)

### ISSUE THREAD

**Issue by mbreakey3** [PowerShell/DscResources#251]
This issue is open for the community to submit comments, questions, or feedback from the DSC Resource Kit community call on March 1, 2017

The agenda for the call is available on GitHub [here](https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/03-01-17/Agenda.md).

**Comment by PlagueHO** [comment]
I am so bummed I missed this one. :cry: Are you going to post the call recording @mbreakey3 ? That would be awesome!

**Comment by mbreakey3** [comment]
Yep! It's available here: https://youtu.be/QVsuNzFZAPo
Notes are uploaded as well [here](https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/03-01-17/Notes.md)
