### ISSUE TITLE
TLS/SSL Ciphers, Protocols and Algorithms

### ISSUE THREAD

**Issue by Outek** [PowerShell/DscResources#254]
Hello 

Im looking for an "official" DSC Ressource to configure TLS/SSL Ciphers, Protocols and Algorithms with Dsc.

Is there already something in the queue or is this a new request?

Thanks in advance

**Comment by dchristian3188** [comment]
I believe all of these are just registry keys. I would take a look at [this article](https://technet.microsoft.com/en-us/library/dn786418(v=ws.11).aspx).

**Comment by Outek** [comment]
Ok, i'll try to do it with registry keys, but a resource for this "hardening" purpose would be nice. 
Thanks
