### ISSUE TITLE
Does PowerShell DSC 5.x support basic authentication for pull server?

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#256]
Does PowerShell DSC 5.x support basic authentication for pull server?  If so, how to configure the Pull Server and LCM? Thanks in advanced.

**Comment by BerheAbrha** [comment]
@chancein007  I am looking in to this and will provide you with example which uses 'Basic' authentication for pull.

**Comment by chancein007** [comment]
Look forward to your reply:)

**Comment by chancein007** [comment]
Is there any update? Thanks in advanced.

**Comment by chancein007** [comment]
@BerheAbrha  Look forward to your update:)

**Comment by johlju** [comment]
@chancein007 there has been a while since this issue was submitted. Did you solve the problem you were having?

**Comment by johlju** [comment]
Due to the age of this issue, and lack of response, I'm closing this as not fixed. Please reopen or comment if this was closed in error.

Here is a link to current information on how to set up a [Desired State Configuration Pull Service](https://docs.microsoft.com/en-us/powershell/dsc/pullserver).
