### ISSUE TITLE
Does DSC 5.x provide a API to query the execution results for all of nodes at one time?

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#257]
As we known that DSC 4.x provide a oData API that we can retrieve all of the execution results for all of the nodes. However, in the DSC 5.x, we need to query the execution results for the target node one by one via providing the target node's configuration ID or agent ID one by one. Does DSC 5.x provide a oData API to query the execution results for all of nodes at one time? Thanks in advanced.

**Comment by grayzu** [comment]
No it does not. 

If this is something that is important to you, please post this as a feature request on UserVoice: https://windowsserver.uservoice.com/forums/301869-powershell/category/148047-desired-state-configuration-dsc

MarkG
