### ISSUE TITLE
Does DSC 5.1 support SQL Server?

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#258]
After walking through the xDscWebService DSC resource,  the xDscWebService to install pull DSC server on the WMF 5.1 just support ESE  for file DB and OLE for Access DB rather than SQL Server database. For the small scale of application, it is enough on the performance; however, for a large scale of servers(more than >3000 servers), how about performance? Is there any solution to support SQL Server in the DSC 5.1? Thanks in advanced.

**Comment by zjalexander** [comment]
This repo is for discussion and development of DSC resources. You can file general DSC requests and questions on [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell/). 

This particular issue has a UserVoice suggestion here: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11088516-change-from-edb-file-to-sql-server-database-for-de

**Comment by ArieHein** [comment]
Look at powershell.org and youll find discussion about it and how people have solved it with using SQL Server as the backend. That said, its not MS supported yet afaik and to be honest if you have over 3000 you dont place them on the same pullserver, you create a few of them, so each gets less nodes to communicate with. You just have the gather all reports to a central place to ro full blow report, but when you think about it, its exactly what you when you want to gather windows sys event logs to once central place to create reports. I've split mine into Production servers and everything else and appropriate built2 reporting services to separate the chatting between clients and server.

**Comment by chancein007** [comment]
Thanks ArieHein, good suggestion. 
@ArieHein  Could you share the url of post that solved it with using SQL server as the backend?

**Comment by ArieHein** [comment]
https://powershell.org/forums/topic/dsc-edb-logs/

Follow the replies, especially Zuldans' link

**Comment by chancein007** [comment]
Great!!! We will follow it:)
https://leandrowpblog.wordpress.com/2016/10/26/using-sql-server-db-for-dsc/

**Comment by johlju** [comment]
We are gonna get native support for SQL Server. Below are snippet from [DSC pull service in Windows Server](https://docs.microsoft.com/en-us/powershell/dsc/pullserver#dsc-pull-service-in-windows-server)

>Starting in release 17090 of Windows Server Insider Preview, SQL Server is a supported option for the Pull Service (Windows Feature DSC-Service). 
>
>Note: SQL Server support will not be added to previous versions of WMF 5.1 (or earlier) and will only be available on Windows Server versions greater than or equal to 17090.

@chancein007 did you get your questions answered?

**Comment by johlju** [comment]
More information here how to set up SQL Server with Pull Server: https://docs.microsoft.com/en-us/powershell/dsc/pullserver

Closing this as resolved.
