### ISSUE TITLE
Meet the issue:"The requested feature DSC-Service is not found on the target" on Window Server 2008 R2 standard Server

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#260]
Today, I have installed WMF 5.1 on my Window Server 2008 R2  Standard edition with SP1 server successfully with .NET 4.5.2; however, I met the below exception when I tried to install the Pull Server on this machine.
PowerShell DSC resource MSFT_RoleResource  failed to execute Test-TargetResource functionality with error message: The requested feature DSC-Service is not found on the target 
machine. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

The configuraiton to setup the pull server for DSC 5.1 is as below:
configuration InstallxDsc5PullServer
{ 
    param  
    ( 
            [string[]]$NodeName = 'localhost', 

            [Parameter(Mandatory)]
            [ValidateNotNullOrEmpty()]
            [string] $RegistrationKey 
     ) 

     Import-DSCResource -ModuleName xPSDesiredStateConfiguration
     Import-DSCResource –ModuleName PSDesiredStateConfiguration

     Node $NodeName 
     { 

         WindowsFeature DSCServiceFeature 
         { 
             Ensure = 'Absent'
             Name   = 'DSC-Service'             
         } 

        File RegistrationKeyFile
        {
            Ensure          = 'Present'
            Type            = 'File'
            DestinationPath = "$env:ProgramFiles\WindowsPowerShell\DscService\RegistrationKeys.txt"
            Contents        = $RegistrationKey
        }
    }
}

InstallxDsc5PullServer   -RegistrationKey '5f75e0b6-041f-40c9-8924-4e28f9dc4648' -OutputPath c:\DSC\PullServer
Start-DscConfiguration -Force -Path c:\DSC\PullServer -Wait -Verbose

Is there any guys who can help me? Any suggestion is much appreciated.

**Comment by kwirkykat** [comment]
@chancein007 You need to enable the DSC-Service Windows Feature on your 2008 R2 machine. This might help as well: https://social.technet.microsoft.com/Forums/windows/en-US/da82aeb8-0a8c-4f4a-85e1-6dce7ae1276c/the-requested-feature-dscservice-is-not-found-on-the-target-machine?forum=winserverpowershell

**Comment by chancein007** [comment]
@kwirkykat  thanks
