### ISSUE TITLE
Community Call Comments, Questions, and Feedback (April 12)

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/DscResources#262]
This issue is open for the community to submit comments, questions, or feedback from the DSC Resource Kit community call on April 12, 2017

The agenda for the call is available on GitHub [here](https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/04-12-17/Agenda.md).

**Comment by PlagueHO** [comment]
Again I missed this. :cry: I need to get my scheduling in order. Was there a recording made? Thanks.

**Comment by johlju** [comment]
I will try to remember to tweet you and remind you next time then :wink:

Katie posted link to the video

https://twitter.com/katiedsc/status/852196105857236992

**Comment by PlagueHO** [comment]
Awesome! Thanks @johlju - and I think the tweet is a good idea! :grin: The call is usually at 4am or 5am for me so I always end up sleeping through my alarm. But next time...

**Comment by johlju** [comment]
I don't think a tweet is gonna help then ;) It might not even make buzz compare to the alarm clock. Perhaps you should schedule an all-nighter instead so you sleep after the community call haha :smile:

I'm 10 hours behind you, so I'm spoiled. Call usually starts when I winding down from the workday. :)

**Comment by PlagueHO** [comment]
I think you're right about the tweet. I've just got to plan better (early night) :grin:

The storm missed us last night - but made a bit of mess out of the east coast.

That sounds like a better time for the call - who ever invented timezones...? :grin: !!!

**Comment by cwhits** [comment]
@kwirkykat: Can the naming scheme for the CommunityCalls folders be switched to an ISO-8601 format—e.g., YY-MM-DD—so they list chronologically?

**Comment by kwirkykat** [comment]
@cwhits I made the folder for the new community call in the YYYY-MM-DD format, and I will do that for future calls as well so that they will order chronologically. I will open an issue to change the other folders as I can't do it right now. A lot of links in this repo will need to be updated when those are renamed.
