### ISSUE TITLE
[Question] Dsc Configurations on nas share, but deploy it with https

### ISSUE THREAD

**Issue by Outek** [PowerShell/DscResources#264]
Hello

I have a question about configuration files for partial resources on a nas share.

Is it possible to place only the Dsc configuration files on a nas share so i can build it with something like Jenkins automatically? 
- Project on GIT
- Build with Jenkins or something similar
- Place the Partial configuration files on a nas share after succesful test/build
- Configure the pull server to get the configuration files on the nas share but deploy it with https and configuration ids

Is this possible somehow?

**Comment by ArieHein** [comment]
technically you can, will it work not sure.

Basically when you create a pull server, its a website and as is, it has a configuration file
that holds the information on where the mof resource files will be stored. Normally it will be on the same server.
You can manually change those values to be a UNC path to the NAS.

However, when you create a pull server it creates an application pool with local service as the identity the application pool. As such it will not be able to access network resources such as the NAS.

You could try mounting a drive to the NAS under the local service user account and then change the configuration file to point to that mounted drive. There still might be an issue with permissions that might lead you to giving everyone full control on that share and obviously not the best way.


What prevents you from saving the results directly to the pull server though ?
or "worst case" add a step in Jenkins to copy the files from the NAS to the server hosting the pull server.

**Comment by Outek** [comment]
Thank you for your answer.

I'm looking for a simplest way do get things done. The step from jenkins to copy the files to the server could be a solution, but not every pull server in our environment is connectet to Jenkins, but every server is connected to the nas

**Comment by ArieHein** [comment]
Maybe using DFS/R ability connecting the output of Jenkins to a folder structure that is visible to all windows server, a server that is reachable from Jenkins and also visible to all the other servers
