### ISSUE TITLE
Is there any xSQL DSC resource that supported the features of the MS SQL Server backup and restore?

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#266]
Is there any xSQL DSC resource that supported the features of the MS SQL Server backup and restore?
If so, could you kindly share us which xSQLServer resource support the features of the MS SQL Server backup and restore? Thanks in advanced.

**Comment by johlju** [comment]
Currently there is not one. But you can submit an issue over at https://github.com/PowerShell/xSQLServer and suggest a new resource for this.
Though, there is the resource [xSQLServerScript](https://github.com/PowerShell/xSQLServer#xsqlserverscript) which you could use to write your own script which might work to backup and restore.

**Comment by chancein007** [comment]
Thanks, johlju

**Comment by johlju** [comment]
A resource has been proposed here https://github.com/PowerShell/SqlServerDsc/issues/532, so I suggest we close this issue.

**Comment by johlju** [comment]
Closing this as per previous comment. Please reopen or comment if this was closed in error.
