### ISSUE TITLE
Community Call Comments, Questions, and Feedback (May 24)

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/DscResources#269]
This issue is open for the community to submit comments, questions, or feedback from the DSC Resource Kit community call on May 24 20:17 noon Pacfic

The agenda for the call is available on GitHub [here](https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/2017-05-24/Agenda.md)

Video is [here](https://youtu.be/q4bT_nFej-8)

**Comment by johlju** [comment]
@zjalexander Is there a delay in the release schedule? Was expecting xSQLServer to be release yesterday. I have PR's with breaking changes I don't want to merge until after release. No hurry, just wondering.  😄

**Comment by mbreakey3** [comment]
@johlju Release will be happening today

**Comment by johlju** [comment]
@mbreakey3 Yay! 👍

**Comment by johlju** [comment]
Closing this issue since it was a long time ago we had this community call, and there are no unanswered questions.
