### ISSUE TITLE
[Question] dsc resource - ensure something dynamic

### ISSUE THREAD

**Issue by Outek** [PowerShell/DscResources#271]
Another question..
Is it possible to use a dsc resource with dynamic values? 
Something like a registry key with a value based on a json webrequest or something similar. 
Has anyone done something like this?

**Comment by ArieHein** [comment]
DSC at its core isn't "dynamic" per se.
When you have your DSC Script, it then needs to be enacted to a MOF file.
At that stage everything becomes static data.

If you are thinking about the configuration script phase, you can have a script that creates a new configuration file that has values that are dynamic and then the script will also create the mof file.

If you are thinking of the outcome of applying the mof file to a node, it will not know how to
evaluate the "dynamic" part at runtime.

**Comment by Outek** [comment]
Ok, i understand the concept better. 
Thank you for the explanation.
