### ISSUE TITLE
Exported cmdlet conflicts between xNetworking, xStorage, xCertificate

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#273]
@zjalexander , @kwirkykat , @mbreakey3 - there is a problem with the latest xStorage resource module release: it exports some common shared cmdlets (Get-LocalizationData etc) that it shouldn't.

This causes a conflict when loaded with xNetworking - because xNetworking also exports these same cmdlets. xCertificate also does the same (as does xDFS). None of these should have actually been exported at all (from any of the resources). The problem can be worked around with the -AllowClobber parameter, but this is not ideal.

I've submitted a PR to each of these repos with the changes to prevent the command cmdlets from being exported.

I've also added a new integration test to each repo to check for conflicts like this in future, but I think eventually the test could be moved into DSCResource.Tests instead. This could be used to test there are no conflicts with each new module that is released with all other existing modules.

The PR's for these changes can be found here:
https://github.com/PowerShell/xNetworking/pull/214
https://github.com/PowerShell/xStorage/pull/94
https://github.com/PowerShell/xCertificate/pull/65
https://github.com/PowerShell/xDFS/pull/34

**Comment by PlagueHO** [comment]
This issue is now closed because the PR's have been merged and the new versions of the modules have been released to the gallery. Thanks @johlju and @kwirkykat for all your help! 🥇

**Comment by BrianFarnhill** [comment]
Is this something that we should put in to the guidelines for each module along with the coding standards kinda thing? Like "if you're going to export a function, make sure it has a specific prefix on the verb". I know in SharePointDsc anything we export I prefix with "SPDsc", so things like "Invoke-SPDscCommand" for example. Just food for thought.

**Comment by PlagueHO** [comment]
Hi Brian - that definitely sounds like a really good idea - I'll raise an issue. In this particular case though, these should cmdlets shouldn't have been exported at all!
