### ISSUE TITLE
Configuring the Local Configuration Manager - RefreshFrequencyMins/ConfigurationModeFrequencyMins

### ISSUE THREAD

**Issue by Outek** [PowerShell/DscResources#275]
Hi

Is it possible to configure the LCM in Pull Mode based on a time and not on a intervall?
Something like:

        Settings
        {
            RefreshFrequencyMins            = 30;
            RefreshFrequencyTime       = 06:00;
            RefreshMode                     = "PULL";
            ConfigurationMode               ="ApplyAndAutocorrect";
            AllowModuleOverwrite            = $true;
            RebootNodeIfNeeded              = $false;
            ConfigurationModeFrequencyMins  = 30;
            ConfigurationModeFrequencyTime = 04:00;
        }

Or whats the simplest way to trigger the LCM on a schedule? Create a Scheduled Task?

Thank you

**Comment by ArieHein** [comment]
Nope.
Yes.
In that order.

Though not tested, you might be able set it 24hours, and start the agents once at 04:00 for example.
But pure observation I noticed that even if I set a lot of agents to the same values they dont connect at the exact time. I think there's some random amount of time (seconds/minutes) added so there is less chance of "DDoS" on the pullserver in places where there are multiple agents trying to query for changes at same time.

But that's my interpretation, at least.

**Comment by Outek** [comment]
Something like the random_fqdn function known from puppet would be nice, in combination with fixed time window to start the refresh and reconfigurations. 
Set the LCM Mode to a fixed maintenace window and start it randomly in this timeframe calculated out of the hostname or fqdn.

**Comment by johlju** [comment]
I asked if this could be considered for a future LCM - it might or might not be considered. I suggest you [add your proposal as a uservoice](https://windowsserver.uservoice.com/forums/301869-powershell/?query=LCM), if it doesn't already exist, so that you can track it and other users can vote on it.

I'm closing this issue at this time since we can't do anything more about it in this repository.
