### ISSUE TITLE
Running Script resource with different credentials

### ISSUE THREAD

**Issue by VerdonTrigance** [PowerShell/DscResources#276]
Running script resource with different credentials seems not working at all.
For example I have to run powershell.exe -version 2.0 from Script resource.
It will look like:
```
Script Deploy 
		{
			SetScript = { 
Write-Debug "! ! ! Entering SetScript"
                & powershell.exe -version 2.0 -executionPolicy bypass -file "C:\Deploy\Update.ps1" -Verbose
			}
			TestScript = { 
                return $false
			}
			GetScript = {
				Return @{ 
					Result = ""
				} 
			}
Credentials = $cred
		}
```
But it I can't check from which user this script runs (whoami, GetCurrent(), $env:UserName) in SetScript with Write-Debug not showing anything. Script returns no error and seems not executes at all.
Next chance is run powershell with cred, not resource:
```
Script DeployWsp 
		{
			SetScript = { 
                Start-Process powershell.exe -Credential $using:cred -NoNewWindow -Wait -Verb runas -ArgumentList("-version 2.0 -NonInteractive -NoProfile -executionPolicy bypass -file 'C:\Deploy\Update.ps1'") -Verbose
			}
			TestScript = { 
                return $false
			}
			GetScript = {
				Return @{ 
					Result = ""
				} 
			}
		}
```
But it can't deserialize $cred!
```
PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: Exception calling "Deserialize" with "1" argument(s): "Key not valid 
for use in specified state.
```
So, how to run script with different credentials passed from main process?

**Comment by bgelens** [comment]
Did you try using the `PsDscRunAsCredential`?

Example without compile (saves you from password encryption / plaintext requirements)

```powershell
Invoke-DscResource -ModuleName PSDesiredStateConfiguration -Name Script -Method Test -Verbose -Property @{
    GetScript = {
        return @{
            GetScript = $GetScript
            SetScript = $SetScript
            TestScript = $TestScript
        }
    }
    SetScript = {
        $null
    }
    TestScript ={
        Write-Verbose "Running as $(whoami.exe)"
        return $true
    }
    PsDscRunAsCredential = $cred
}
```

**Comment by VerdonTrigance** [comment]
No. I did not try PsDscRunAsCredential because it has not been listed as parameter on MSDN for this resource. I will check it and tell result in two days.

**Comment by bgelens** [comment]
It's a common property that is valid for all resources. [see this blog post](https://msdn.microsoft.com/en-us/powershell/dsc/runasuser) for more info. Forgot to mention, it does require you to have PowerShell 5+ installed.

**Comment by VerdonTrigance** [comment]
I have checked PsDscRunAsCredential and... it works! Thank you.

**Comment by nftw** [comment]
@bgelens Any idea what the difference between using `Credential` (as per https://msdn.microsoft.com/en-us/powershell/dsc/scriptresource) and `PsDscRunAsCredential` is? Is `Credential` a pre PS5 legacy property? I'm seeing different behaviour when using each option.

**Comment by bgelens** [comment]
if you use Credential with the script resource, the LCM runs as ```NT Authority\System``` and within the Script resource use Invoke-Command -Credential to run the code. See for the exact invocation: https://github.com/PowerShell/PSDscResources/blob/bba8fee7bd423dd9629a7a6cf3dea688de4b4e7d/DscResources/MSFT_ScriptResource/MSFT_ScriptResource.psm1#L269.

When you run with ```PsDscRunAsCredential```, the LCM is actually running the entire Script resource using the Credential specified and uses the call operator on the scriptblock instead.

So it's a case of ```Credential -> RunAs``` vs ```PsDscRunAsCredential -> Impersonation```

**Comment by VerdonTrigance** [comment]
Update.
I have  new use case, that brings new problems.
The case is next:
I have to run Script Resource (with that $using:Variable syntax) and pass to it several secure PSCredentials like proxy cred, release agent cred and so on. I have configured all certificates and other stuff: Sending server have publicKey cert, Target server have cert with privateKey, LCM use that cert.
I have tried multiple approaches with or without PsDscRunAsCredential.
For example:
`$cd = @{
    AllNodes = @(    
        @{ 
            NodeName = "devmsportal-02"
            CertificateFile = "C:\PublicKeys\PowerShellDSCEncryption.cer"
            Thumbprint = "1205503eaabe956f2077a3e7c6cb964ec3ad7df5"
        }
    ) 
}

Configuration MyConfiguration
{
    param(
        [Parameter(Mandatory)]
        [PSCredential]$MyCred
    )
 
    Import-DscResource -ModuleName "PSDesiredStateConfiguration"
 
    Node devmsportal-02
    {
        Script RunP
        {
            GetScript = {
                return @{Result = ''}
            }
            TestScript = {
                return $false
            }
            SetScript = {
                $using:MyCred > "C:\tmp\cred.txt"
            }
        }        
    }
}
$cred = Get-Credential -Message 'co\tfsbuild' -UserName 'co\tfsbuld'
MyConfiguration -ConfigurationData $cd -OutputPath C:\DSC\tmp -MyCred $cred -PsDscRunAsCredential $cred
Start-DscConfiguration C:\dsc\tmp -ComputerName devmsportal-02 -Wait -Force -Verbose`

When I run that I got:
Logon failure: the user has not been granted the requested logon type at this computer

That means that I can't use -PsDscRunAsCredential with system account that does not have this LogonLocally permission, right?
But without -PsDscRunAsCredential I'm getting error from the first post (PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: Exception calling "Deserialize" with "1" argument(s): "Key not valid for use in specified state."). 
It seams that DSC force me to work under my credential or open LogonLocally permission to system account.

**Comment by ewhitesides** [comment]
You have to do something like this (or at least its how i did it).... not sure its very secure, but i do use push configuration instead of pull, so the MOF is encrypted when pushed.

Configuration MyConfiguration {
     Param(
         [Parameter(Mandatory)]
         [PSCredential]$MyCred
    )

    $CredUser = $MyCred.UserName
    $CredPass = $MyCred.GetNetworkCredential().Password
  
    Import-DscResource -ModuleName "PSDesiredStateConfiguration"

    Node devmsportal-02 {
        Script RunP {
        GetScript = {
            return @{Result = ''}
        }
        TestScript = {
            return $false
        }
        SetScript = {
            $LocalJobUser = $Using:CredUser
            $LocalJobPass = ConvertTo-SecureString -AsPlainText -String $Using:CredPass -Force
            $LocalJobCred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $LocalJobUser,$LocalJobPass
        }
    }        
}

**Comment by VerdonTrigance** [comment]
For those who still facing this problem, I fond solution. If you need pass credentials for some services, web applications or other custom stuff, but you have to launch scripts under technical account like MyEpicDeployAgent you can't use PsDscRunAsCredential or Credential. It related to fact that DSC runs under current user account in compile machine and under System account in target machine. This cause an errors. Instead of this you encrypt and decrypt data manually. For this u should pass encrypt SecureString at compile time with Protect-CmsMessage, and then use it in resource with Unprotect-CmsMessage.

> You have to do something like this (or at least its how i did it).... not sure its very secure, but i do use push configuration instead of pull, so the MOF is encrypted when pushed.
> 
> ```
> Configuration MyConfiguration {
>      Param(
>          [Parameter(Mandatory)]
>          [PSCredential]$MyCred
>     )
> 
>     $CredUser = $MyCred.UserName
>     $CredPass = $MyCred.GetNetworkCredential().Password
>   
>     Import-DscResource -ModuleName "PSDesiredStateConfiguration"
> 
>     Node devmsportal-02 {
>         Script RunP {
>         GetScript = {
>             return @{Result = ''}
>         }
>         TestScript = {
>             return $false
>         }
>         SetScript = {
>             $LocalJobUser = $Using:CredUser
>             $LocalJobPass = ConvertTo-SecureString -AsPlainText -String $Using:CredPass -Force
>             $LocalJobCred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $LocalJobUser,$LocalJobPass
>         }
>     }        
> }
> ```

For those who still facing this problem, I fond solution. If you need pass credentials for some services, web applications or other custom stuff, but you have to launch scripts under technical account like MyEpicDeployAgent you can't use PsDscRunAsCredential or Credential. It related to fact that DSC runs under current user account in compile machine and under System account in target machine. This cause an errors. Instead of this you encrypt and decrypt data manually. For this u should pass encrypt SecureString at compile (inside Node) time with Protect-CmsMessage, and then use it in resource with Unprotect-CmsMessage.
