### ISSUE TITLE
xActiveDirectory: MSFT_xADDomainController.schema.mof is missing 'Ensure' variable

### ISSUE THREAD

**Issue by beggsm** [PowerShell/DscResources#277]
Get-TargetResource function in MSFT_xADDomainController.psm1 script returns a hash key labeled 'Ensure' but does not have a reference in the related MOF schema file.  This creates an invalid key 'Ensure' error when performing Get-DscConfiguration on targets.

MSFT_xADDomainController.psm1
    $returnValue = @{
        DomainName = $DomainName
        Ensure = $false
    }

MSFT_xADDomainController.shema.mof
[ClassVersion("1.0.1.0"), FriendlyName("xADDomainController")]
class MSFT_xADDomainController : OMI_BaseResource
{
    [Key] String DomainName;
    [Required, EmbeddedInstance("MSFT_Credential")] String DomainAdministratorCredential;
    [Required, EmbeddedInstance("MSFT_Credential")] String SafemodeAdministratorPassword;
    [write] String DatabasePath;
    [write] String LogPath;
    [write] String SysvolPath;
    [write] String SiteName;
};

**Comment by beggsm** [comment]
A couple questions:

1.  I have cloned the repo locally and corrected the schema file and tested against a target.  How do I request that this task get promoted to the help needed section so that it can be assigned?

2.  The pester tests pass for this DSC module but only when the AD features (providing the AD powershell commands) are installed.  Is this an expected requirement for testing or should the test be updated to support non-server test machines?

**Comment by mbreakey3** [comment]
1. Did you open an Issue or PR in xActive Directory? Because I don't see any open by you. Once you do that you can add a label for 'help wanted' if it's an issue that needs to be fixed or 'needs review' if it's a PR that you want reviewed and eventually merged in.

**Comment by beggsm** [comment]
Thank you, will do!
