### ISSUE TITLE
HQRM Plaster templates

### ISSUE THREAD

**Issue by bgelens** [PowerShell/DscResources#278]
I'm creating a couple of HQRM Plaster Templates [here](https://github.com/bgelens/NewDscHighQualityResourceModule)
I'm planning to have these merged into the [Plaster](github.com/powerShell/plaster/) repo eventually.

Since plaster is shipped together with the PowerShell vs code extension, this will bring HQRM Module and HQ Resource scaffolding as an easy wizard driven experience.

Help (in any way) is welcomed!

**Comment by PlagueHO** [comment]
Oh! Awesome! I'd love to see support for the auto-documentation type modules as well :grin: e.g. the ones like SharePointDsc, xNetworking, xStorage. These have quite a slightly different folder structure.

**Comment by bgelens** [comment]
@PlagueHO are these *auto-documentation type modules* formally documented?

**Comment by PlagueHO** [comment]
Hi @bgelens - no - they aren't yet. This is something we need to do as the folder structure is quite different from the standard module. I'll raise an issue to get a document added to this repo that covers the structure of this type of resource.

**Comment by johlju** [comment]
@bgelens This is really impressive work here! 😄 This Plaster template is very complete! I see there are potential to make it even better, tweak more properties in each file, make the first resource more complete example, adding a real unit test and integration inside the template. 

Maybe we should link from this repo's documentation so contributors can help make the Plaster template better? 🤔

**Comment by bgelens** [comment]
Hi @johlju, I know it's being linked to in a number of resources like books and such. I'm not planning to merge it up with the Plaster repo anymore though. Feel free to link to it and contribute if you like 😄 I'll take PRs! I'll leave the issue open so you can close when there isn't anything to be tracked anymore.

**Comment by johlju** [comment]
I thinking where the best places for this would be... Somewhere around the DscResource.Template 🤔
