### ISSUE TITLE
Why did Devices table is empty after switching to Access DB for DSC 5.1?

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#280]
After switching to Access DB for DSC 5.1, I found that devices table is always empty. Why did Devices table is empty after switching to Access DB for DSC 5.1?
The Devices table included the below columns:
TargetName
ConfigurationID
ServerCheckSum
TargetCheckSum
NodeCompliant
LastCompliant
LastHeartbeatTime
Dirty
StatusCode

**Comment by ArieHein** [comment]
Well to start off, switching database layer, doesnt mean data migration in any way.

Try registering a node again with the pull server and then see the changes
or wai ta few good hours (up to 24h i'd say)  till all your nodes will communicate and register fully.
As I've not tried it myself I'm assuming they will register on their own. If you want to force it to match your timeline, just re-register the node

**Comment by chancein007** [comment]
The registration data will be added to RegistrationData table rather than Devices table in the DSC 5.1. I thinks that Devices table maybe be used to back compatibility with DSC 4.x
