### ISSUE TITLE
How to setup Load Balance for DSC 5.1 Pull Server?

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#281]
So far, I have switched the database of the DSC 5.1 Pull Server to MS SQL Server, is there anyone that setup the load balance for the DSC 5.1 Pull Server? Thanks in advanced.

**Comment by chancein007** [comment]
Any suggestion is much appreciated.

**Comment by chancein007** [comment]
The issue has been resolved

**Comment by chancein007** [comment]
Used ngnix or apache to do loadbalnace

**Comment by ArieHein** [comment]
Just make sure all the nodes talk to the same mssql database else you didnt really do any real high availability.

If you want to remain in the Windows area, use IIS ARR which the same as apache reverse proxy.

While I understand and appreciate the reason to make the front end of the pullserver be HA, I dont think it was built to be such, with the implementation of local database on each node.
