### ISSUE TITLE
Unable to run Git Clone with apostrophe in the Directory Path

### ISSUE THREAD

**Issue by ld0614** [PowerShell/DscResources#287]
While attempting to run pester to test my new module against the DSC Resource tests I encountered an error while running the git clone command.  

git.exe : fatal: could not create work tree dir 'C:\Users\USERNAME\OneDrive - D'Arcy\Source\Repos\LanguageDsc\DSCResource.Tests"': Invalid argument

I believe that it is to do with the apostrophe within my name, is there a way to delimit this as replacing with %27, '', `' and \' haven't worked

**Comment by PlagueHO** [comment]
Hi @ld0614 - which DSC resource module were you running the tests against? Some of them use different methods of cloning the `DSCResource.Tests` repo.

**Comment by ld0614** [comment]
I've tried making my own one, using the Unit Test Template Version: 1.2.0.  After doing some more research this morning it looks like I just needed to remove the final \ from the DSCResource.Tests part of the line.  ie changing 
& git @('clone','https://github.com/PowerShell/DscResource.Tests.git',(Join-Path -Path $script:moduleRoot -ChildPath '\DSCResource.Tests\')) 
to:
 & git @('clone','https://github.com/PowerShell/DscResource.Tests.git',(Join-Path -Path $script:moduleRoot -ChildPath '\DSCResource.Tests'))

I've also run into issues with some of the other tests, specifically Meta.Tests.ps1:
Get-ChildItem : Could not find a part of the path 'C:\Users\USERNAME\OneDrive - D'Arcy\Source\Repos\LanguageDsc\DSCResource.Tests\node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\node_modules\micromatch\node_modules\braces\node_modules\expand-range\node_modules\fill-range\node_modules\is-number'.

I belive that this is due to MAX_PATH being hit.  Is there any way to refactor the tests directory to not require such a long path?  In my immediate case I've enabled long pathnames which seems to fix the issue.

**Comment by johlju** [comment]
Could you please help an find out which test that is trying to use Get-ChildItem. So we can filter out the node_modules folder from that test or tests.

**Comment by johlju** [comment]
@ld0614 Also, I don't understand what change you did to the below line to fix the apostrophe issue.
```
& git @('clone','https://github.com/PowerShell/DscResource.Tests.git',(Join-Path -Path $script:moduleRoot -ChildPath '\DSCResource.Tests'))
```

Although child path `'\DSCResource.Tests'` should not need to start with `'\'`. Was it that what you changed?

**Comment by johlju** [comment]
I have found a bug with apostrophe
https://github.com/PowerShell/DscResource.Tests/issues/166

**Comment by ld0614** [comment]
Apologies @johlju I hadn't realised that the final slash was hidden by the github markup language.  I used the unit_template.ps1 and integration_template.ps1 version 1.2.0 (https://github.com/PowerShell/DscResources/blob/2e34c0ae8ff2ff09732124d3db62c3102b7862ee/Tests.Template/unit_template.ps1#L24 and https://github.com/PowerShell/DscResources/blob/2e34c0ae8ff2ff09732124d3db62c3102b7862ee/Tests.Template/integration_template.ps1#L25) 

I'm not entirely sure why removing the final slashed worked, however, I could replicate the issue directly from git.exe.  It seems that git.exe is attempting to split the command into more arguments but resolves correctly without the final slash.

**Comment by johlju** [comment]
I have reproduced this.

Using the template I get this error when using the path
`'V:\Source\HelpUsers\Users\USERNAME\OneDrive - D'Arcy\Source\Repos\LanguageDsc\Tests\Unit'`

```plaintext
fatal: could not create work tree dir 'V:\Source\HelpUsers\Users\USERNAME\OneDrive - D'Arcy\Source\Repos\LanguageDsc\DSCResource.Tests"': Invalid argument
```

As you said, removing the trailing backslash, everything works. also removed the backslash in the beginning.

```
& git @('clone','https://github.com/PowerShell/DscResource.Tests.git',(Join-Path -Path $script:moduleRoot -ChildPath 'DSCResource.Tests'))
```

It worked

```
PS V:\Source\HelpUsers\Users\USERNAME\OneDrive - D'Arcy\Source\Repos\LanguageDsc\Tests\Unit> Invoke-Pester .\MSFT_LanguagePack.tests.ps1
Executing all tests in .\MSFT_LanguagePack.tests.ps1

Executing script .\MSFT_LanguagePack.tests.ps1
Cloning into 'V:\Source\HelpUsers\Users\USERNAME\OneDrive - D'Arcy\Source\Repos\LanguageDsc\DSCResource.Tests'...
remote: Counting objects: 812, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 812 (delta 9), reused 18 (delta 7), pack-reused 789
Receiving objects: 100% (812/812), 266.51 KiB | 418.00 KiB/s, done.
Resolving deltas: 100% (472/472), done.

  Describing Schema

    Context Check Variable requirements
      [+] LanguagePackName should be mandatory. 2.79s
      [+] LanguagePackLocation should not be mandatory. 870ms
      [+] Ensure should not be mandatory and only have two values. 860ms
```

@ld0614 Do you want to send in a PR fixing this or should I?

**Comment by ld0614** [comment]
Thanks @johlju I've created PR 299, I've also updated the version template numbers by 0.0.1 and fixed a spelling mistake in one of the files.  Please let me know if there is anything else I need to do (Apart from sign the CLA) as this is my first PR using github :)
