### ISSUE TITLE
New Language Resource Module

### ISSUE THREAD

**Issue by ld0614** [PowerShell/DscResources#288]
I've started writing a new DSC resource to handle modifications to Locale and Language packs for Windows Server Operating Systems.  There are currently two resources planned:
LangaugePack: This will allow for the creation and removal of language packs from a system
Language: This will configure all of the Language and Locales on a system as required.

I've been primarily writing it as an MOF-based DSC as it seemed that there was more documentation on the subject and was backward compatible.  

As this is my first attempt at writing a module I have attempted to follow all the guidance provided however I'm sure that there are parts which need some work.  I have attempted to complete the LanguagePack Resource fully to allow for feedback.  I believe that I have fully written the functionality for the Language Resource but I haven’t started on the unit or integration tests as I wanted some feedback from the LanguagePack Resource tests before wasting several hours getting two sets of tests wrong.  

I have uploaded my current code here: https://github.com/ld0614/LanguageDsc, Any feedback that you can provide would be most welcome

**Comment by PlagueHO** [comment]
Hi @ld0614 - these resources sound like a great idea. There is already a DSC Resource for configuring [SystemLocaleDsc](https://github.com/PowerShell/SystemLocaleDsc) - but I can see your resource configures other aspects of system Languages.

Is it worth combining the language resources into the SystemLocaleDsc resource? Or does that not make sense?

I'm happy with whatever is decided, but thought it was worth having the discussion.

Thanks for raising this and creating what look to be some really beautifully written resources!

**Comment by ld0614** [comment]
HI @PlagueHO Thanks for the feedback, I'd considered adding the resources to the SystemLocaleDsc module, however; I felt that that the name of the module wouldn't then reflect the full functionality of the resources located within it.  I exposed the SystemLocale Functionality through the Language Resource as I'm using the `control intl.cpl /f` functionality described here: https://support.microsoft.com/en-us/help/2764405/how-to-automate-regional-and-language-settings-in-windows-vista,-windo and felt that despite the duplication of resources which may confuse users it was better than requiring 2 different resources when the underlying functionality was available anyway.  

The way I see it there are 3 main options:
1.  Migrate all existing functionality and tests from SystemLanguageDsc into the new LanguageDsc (or renamed) Package and remove/deprecate the existing package
2.  Migrate the SystemLanguage resource into the LanguageDsc Module but keep the functionality duplicated as they use different methods to achieve the same result. 
3.  Continue to have two separate resources

I'm personally in favor of option one as it removes duplication of code and doesn't require a user to understand the reasoning for using one resource over another.  That being said I really don't feel strongly one way or another.  I'm happy to have a go at migrating anything missed into the new resource, I think that the only things missing are the multilanguage support and possibly some pester tests.

**Comment by ld0614** [comment]
I've made significant updates to my module proposal including pester tests and appveyor autobuilding.  The two things I'm currently struggling on is how to automate the integration tests as these require a reboot and a language pack file which I don't believe can be redistributed publically.  I'm also getting some test failures for BOM encoding on certain files (including files in the Resources.Tests directory).  When I look at these files through notepad++ they don't appear to have BOM encoding.  As such can these warnings be ignored?

**Comment by PlagueHO** [comment]
Hi @ld0614 
Sorry for not getting back to you earlier. Is the reboot required to occur in the middle of the integration tests? If so, that won't work in AppVeyor. However, if the reboot is required in the "Install" stage of the AppVeyor config - then that can work. I can point you at the right info if that is the issue.

Can you link to the BOM errors you're getting? I have a feeling these are actually warnings saying that the "BOM" tests weren't executed on the files because you haven't Opted into the tests.

You'd need to opt-in to the BOM tests by adding:
        "Common Tests - Validate Module Files"
        "Common Tests - Validate Script Files"

To the `.MetaTestOptIn.json` file.

**Comment by ld0614** [comment]
Thanks for all your help @PlagueHO I've published an initial module to the PowerShell gallery for ease of access and would be interested in submitting my module into the resource kit proper when the process has been defined.  

Most of the automated tests work in appveyor however the removal tests require the device to reboot before returning the fact that the language settings have been removed.  As a workaround, I have tagged these tests as reboot required and exclude them from automated testing.  If you have any ideas as to how to automate these tests across a reboot (Azure automation seems like a possible good fit) I'd be all ears :)

**Comment by PlagueHO** [comment]
A pleasure to help @ld0614 and very grateful for the contributions!

As for the restart in the tests, this is something I've always wanted to do as well, but so far I don't think anyone has solved it. We can execute a reboot of the AppVeyor node in the "Install" task, but anytime after that won't work.

There has been some work done by @mgreenegit over in this repo https://github.com/PowerShell/DscConfiguration.Tests, but this was for applying and testing DSC Configs using Azure Compute VMs, but I don't think it has been considered for being able to be used for test execution in the DSC Resource Kit.

But I think it is still acceptable to do what you've done with the tagging of the tests requiring a reboot.

What we need to figure out though is if we include this as a new resource module or add this to one of the other resource modules (e.g. xComputerManagement). I think probably it might be best to include it in xComputerManagement as we might also be moving SystemLocaleDsc over there as well. @kwirkykat - what are your thoughts?

**Comment by ld0614** [comment]
@PlagueHO After thinking about it for some time I think that your right in saying that this functionality should sit under the xComputerManagement module.  I'll start working on a PR for this now

**Comment by PlagueHO** [comment]
Cool! I'm also planning on moving SystemLocaleDsc and xTimezone into this xComputerManagement as well - so this should align with your resource. The intention is to convert xComputerManagement over to ComputerManagementDsc and at the same time move these resources over (if acceptable to @kwirkykat and the community).

**Comment by ld0614** [comment]
I've just finished renaming everything to xLanguage to fit :sob: Does the SystemLocaleDsc need to be migrated as the Language resource will also handle system locale changes? (independently or as part of a wider change).  If you can let me know which repo / branch to PR into and I'll get an initial request in to start the review and remediation process.

**Comment by kwirkykat** [comment]
@PlagueHO I'm good with all of this (moving these resources into ComputerManagement, renaming, and the new Language resource) 👍

**Comment by PlagueHO** [comment]
Awesome!

@ld0614 - does xLanguage allow changing just the System Locale without specifying the language? If that is the case then perhaps we can drop SystemLocaleDsc altogether as maintaining two methods for setting System Locale will probably just result in people implementing configs that conflict - plus it'll be just a waste of effort.

If not, how easy is it to drop System Locale setting from xLanguage?

**Comment by ld0614** [comment]
I wrote the language resource to be highly customisable (hence the size of the resource).  Each parameter is individually tested and if not currently configured is independently set.  This means that languages and locales can be set independently without requiring the other to be configured.  

The only limitation is the IsSingleInstance which means that if both locale and language require setting they must be done in the same resource config. 

The specific code for configuring the system locale is [here](https://github.com/ld0614/LanguageDsc/blob/b93bbf1af800efd7e5ce183a2366c2c72ccc07bd/DSCResources/MSFT_Language/MSFT_Language.psm1#L220)

**Comment by johlju** [comment]
@ld0614 Since there is consensus about moving LanguageDsc into ComputerManagementDsc (soon to be renamed - in PR), and there is an issue create for this https://github.com/PowerShell/xComputerManagement/issues/127, can we close this issue?

**Comment by johlju** [comment]
I'm closing this issue since there are a new issue opened in xComputerManagement (see previous comment). If you feel this shouldn't have been closed, then feel free to comment and reopen.
