### ISSUE TITLE
Request to transfer xDefender

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/DscResources#29]
I would like to transfer a new repo for managing Windows Defender to the PowerShell org.  This module is based on the PowerShell module 'Defender' and gets/sets preferences via the *-MPPreference commands.

The module has complete documentation and passes the tests included in the DSCResources.Tests repo.

https://github.com/mgreenegit/xDefender

Please confirm or suggest changes.  Thank you.

**Comment by tysonjhayes** [comment]
I realize there isn't much logic but I'd still like to see some pester tests, even if it just runs Test-xDSCResource and Test-xDSCSchema just to validate that any future changes have some kind of baseline to run against.

**Comment by mgreenegit** [comment]
That sounds like a reasonable plan.  I have added a verbose transcript of test-xdscresource, test-xdscschema, and invoke-pester.  Metadata removed.  Long term these three should merge.  I am willing to work on it, when time allows.
https://github.com/mgreenegit/xDefender/blob/master/test_transcript_verbose.txt

**Comment by mgreenegit** [comment]
I should also note that I would expect the transcript file to be removed after transfer.

**Comment by tysonjhayes** [comment]
:laughing: I guess that is what I asked for. I meant add the tests to your repro so anyone can run it every time.

I meant more something like this:
https://github.com/PowerShell/xWebAdministration/blob/dev/Tests/MSFT_xWebsite.Tests.ps1

**Comment by mgreenegit** [comment]
I agree with you.  I think the best option is to add those checks to the dscResource.tests script, so all resources are evaluated by the build service.

https://github.com/powerShell/dscResource.tests

**Comment by tysonjhayes** [comment]
Yup, already have an issue filed to run most of what I've pointed out. https://github.com/PowerShell/DscResource.Tests/issues/3

**Comment by mgreenegit** [comment]
The ReadMe file for this module has been updated to match the new template.  Confirm whether it is acceptable to transfer?

**Comment by KarolKaczmarek** [comment]
Thank you for transferring this! 

Overall it looks good, just a couple comments:
- This module contains single resource, but in readme release notes, I see:
```
0.1.0.0

Initial release with the following resources:
<and here list all properties of that resource>
```

- Can you clean up the commented out code?
```
# Get-TargetResource -Name DefenderPreferences -HighThreatDefaultAction Quarantine
```
If that's supposed to act as example of calls for each function, please move it to .EXAMPLE section in comment above that function
```
<#
    .SYNOPSIS <description>
    .PARAM
        parameter_name <description of parameter>
    .EXAMPLE
        <example>
#>
```
- Also, there are single letter variable names in quite a few places like $k or $v.
I'd recommend using verbose names for ease of understanding (https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md).
If you'd have few minutes to correct that, that's great, but if not I don't consider it blocking and we can refactor it later.

**Comment by mgreenegit** [comment]
I have resolved everything except the example text.  I want to discuss that change before we commit to it.  Transfer complete.  Thanks.

**Comment by KarolKaczmarek** [comment]
It's in: github.com/powershell/xdefender/
