### ISSUE TITLE
Adding contributors "Thank you" to each repositorys CHANGELOG.md

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#295]
To acknowledge the great work our contributors does in all the repositories I'm wondering if we shouldn't add a 'Thank You'-section prior to each release. That should list each user and what they contributed. 
That could be added to the release notes when released. The entries could be added by the contributor in each PR by them self, so they can choose to be listed or not.

I will be up to each repo-maintainer to make sure the contributors can get on the list if they want to.

Thinking of the same concept as the VS Code team does here:
https://code.visualstudio.com/updates/v1_12#_thank-you

**Comment by johlju** [comment]
Just a clarification. I don't see that maintainer contributions should be on that list. Only contributors that are not maintainers.

**Comment by PlagueHO** [comment]
Sounds like a great idea to me - and should definitely help to keep contributors coming back and contributing again :grin:

**Comment by johlju** [comment]
Suggestion how this could look like

------

- Changes to SomeResource
  - [FirstName LastName (@account)](https://github.com/johlju): Some awesome fix for the resource ([issue #1111](issue)).
- Changes to OtherResource
  - [FirstName LastName (@account)](https://github.com/johlju): Another awesome fix for the resource ([issue #2222](issue)).
------

**Comment by randomnote1** [comment]
Could the build process in AppVeyor add these references in automatically during the PR process?

**Comment by johlju** [comment]
That would be interesting if that could work, but not sure it would be possible to push a change to the contributors working branch, or the PR? Even if we could, maybe we shouldn't since a (new) contributor should sign the CLA before we can merge the changes, so we shouldn't change the contributors code at that point.
Although, if we built release notes on top of the change log, then that could be built automatically by the release pipeline.

If was thinking the simplest method is either that the contributor do it them self, or the maintainer does this throughout the change log before release.

**Comment by johlju** [comment]
I propose I try out my suggestion in https://github.com/PowerShell/DscResources/issues/295#issuecomment-373115320 for SqlServerDsc's CHANGELOG.md for this release. Any objections to that?

**Comment by johlju** [comment]
I added a PR https://github.com/PowerShell/SqlServerDsc/pull/1090 as a proposal for this. If I don't get any objections or review comments by Saturday I will merge it. 😄

**Comment by johlju** [comment]
I will merged this PR as soon as the tests passes. So closing this issue, and if another maintainer want to do this, there is example in SqlServerDsc's CHANGELOG.md.
