### ISSUE TITLE
For WMF5.1, does agentID is fixed value for a specified machine? Can agentID be changed? 

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#296]
As we known that in the WMF5.1, we can used the agentID rather than configurationID to register the DSC pull server; one quick question:  does agentID is fixed value for a specified machine? Can agentID be changed?  Any help is much appreciated.

**Comment by ArieHein** [comment]
AgentID is fixed for a machine from the point of view of the pull server.
As AgentID is a key in the resgistry, you can remove the key and upon initial re-registering the node, it will get a new AgentID.
Note that there used to be a bug in the Sysprep process that didnt remove this registry key, thus consequent images made all had the same AgentD which caused issues when several machines tried to register to a pull server using the same AgentID.
I haven't tried Sysprep on a server image for quite a long time, so this might have been fixed. Although a step to remove the key can always be added to the Sysprep process manually if they didnt fix this yet.

**Comment by ggoebel** [comment]
Where is AgentID stored in the registry?

**Comment by johlju** [comment]
@chancein007 Did you get your question answered?

**Comment by johlju** [comment]
I can't find any supported way of changing the AgentID. So most likely it is not meant to be changed once set by LCM.

**Comment by johlju** [comment]
I assume this issue has been resolved. If this was closed in error, please comment and reopen.
