### ISSUE TITLE
Offline Installation of xWebAdministration

### ISSUE THREAD

**Issue by gokhankocak** [PowerShell/DscResources#297]
Hello,

Most of our servers are not open to Internet.
How can I install xWebAdministration?

Regards,
// Gokhan

**Comment by PlagueHO** [comment]
Hi There @gokhankocak,

You will need to download a zip file containing the content of the module. Head over to the xWebAdministration releases page and download a zip file containing the version you want:
https://github.com/PowerShell/xWebAdministration/releases


Then unzip the downloaded zip file to the folder `c:\program files\windowspowershell\modules\`. This will create a new folder called `xWebAdministration-1.8.0.0.-PSGallery` - you can rename this folder to `xWebAdministration`.

HTH.

**Comment by johlju** [comment]
@gokhankocak did you get your question answered? Can we close this issue?

**Comment by johlju** [comment]
Closing this issue since it looks like it has been answered.
