### ISSUE TITLE
Missing System Center Components

### ISSUE THREAD

**Issue by flyboarder** [PowerShell/DscResources#30]
Hello,

My organization is working on PS DSC configurations over at @d9micromgmt i'd like to know if there are existing code bases for the missing system center dsc resources, such as config manager?

**Comment by jpritchard** [comment]
Hi @flyboarder. I'm also interested in ensuring the remaining System Center components have Resources.

In particular Orchestrator currently looks like an omission @kwirkykat do you have any info on this?

Perhaps we can all work together on this. Thank you.
Jonathan

**Comment by kwirkykat** [comment]
@jpritchard @flyboarder I don't have any more System Center resources other than what is already posted (xSCDPM, xSCOM, xSCSMA, xSCSPF, xSCSR, xSCVMM). But if you'd like to [submit a new module](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#submitting-a-new-resource-module), I would be glad to add more System Center resources to the DSC Resource Kit.

**Comment by jpritchard** [comment]
Thank you Katie. Good to know, just didn't want to duplicate work. I'll start looking into it. Not done anything like it before though :-)

-----Original Message-----

**Comment by johlju** [comment]
I suggest we close this issue since any new resource modules should be submission-ed to this repository if a resource module owner wants it added to the DSC Resource Kit.

**Comment by johlju** [comment]
Closing this as solved as per author comment and my previous comment.
