### ISSUE TITLE
Test Guideline is not consequent in how to write '| Should ...'

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#300]
The [Test Guideline](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) is not consequent on how to write `| Should Be`, '| Should Not Throw`. Some is written in lower-case letter.

I suggest we change the guideline to use upper-case for each Pester keyword after and including `Should`. Laso add some more example for throwing, which look like it is missing.

**Comment by ld0614** [comment]
is it not worth broadening the guidance to all PowerShell commands should be capitalized? I would also have said that the advice sits better under the style Guidelines rather than specific testing guidance.

**Comment by PlagueHO** [comment]
I tend to agree with @ld0614 - we should be enforcing correct capitalization for cmdlets and parameters.

I can also probably quite easily add a PSSA rule to support this guideline as well.

**Comment by ld0614** [comment]
I've had a quick go at making an updated guideline, https://github.com/ld0614/DscResources/blob/CapitalizationGuideline/StyleGuidelines.md#capitalized-cmdlets-function-names-and-pester-assertions

Wording: PowerShell cmdlets, Functions and Pester assertions should all start with capital letters. This makes code easier to read, especially when there are multiple nouns in the command name.

@PlagueHO A PSSA Rule sounds like a great idea

**Comment by johlju** [comment]
@ld0614 Looking good to me. Are you PR that in? 

Suggest changing
```
New-Function -Name $params
```
to
```
New-Function -Name $newFunctionParameters
```

So it's clear what kind of parameter that is (we try use descriptive names).

**Comment by PlagueHO** [comment]
@ld0614 - Cool, once the guideline is in place I can submit the new PSSA rule. I've got a few more I want to add in soon as well.
