### ISSUE TITLE
WMF 5.1 Naming configuration documents on the pull server.

### ISSUE THREAD

**Issue by madmikep** [PowerShell/DscResources#305]
I have Pull Server and a client server (DEV Server) both are Windows 2012 R2 running WMF 5.1.  I am using ConfigurationNames to apply 7 Configuration’s  which install IIS,  Dot3.5, Source files for 3 websites, Sets up ODBC connections, and sets up 3 Websites on the DEV server. I have created Hashtables for the some of the Configurations like the websites this all is working fine without any problems.  My problem is I now need to also create a (QA Server) using the same ConfiurationNames. To publish to MOF files on the Pull server I run the configuration example WebSiteA –ConfigurationData this creates the two server MOF files one for the DEV and one for QA server.  Now I cannot use localhost for the AllNodes because the websites do not have the same names example WebsiteA-Dev and WebSiteA-QA.  Plus some other changes like SQL database names.  WMF 5.1 says I can name my MOF files “ConfigurationName>.<NodeName>.mof” which would be good.   But when I try this WebsiteA.DEVServerName.MOF and try to update the DSC configuration I receive “Executing Get-Action on partial configuration ' WebsiteA' Failed. Please ensure the partial configuration and
 its checksum exist on the server. Check the DSC event logs for further details.”   This tells me that WMF 5.1 does not support “ConfigurationName>.<NodeName>.mof” format.    So my next question is how are we to deploy two or more MOF files for a Configuration that is using a hashtable short of create DSCLocalConfigurationManager configurations for each host.

**Comment by madmikep** [comment]
Correction WMF 5.1 says I can name my MOF files “ConfigurationName>.<ServerName>.mof”

**Comment by madmikep** [comment]
WMF 5.1 says I can name my MOF files ConfigurationName.servername.MOF

**Comment by johlju** [comment]
@madmikep are this still a problem or did you get past this problem?

**Comment by johlju** [comment]
Closing this issue as not fixed due to lack of response. Please reopen or comment if this was closed in error.

**Comment by madmikep** [comment]
As far as I know this was never fixed and I never received any information on how to make that work
________________________________________

**Comment by johlju** [comment]
@madmikep It sounds like you need to handle what each settings is suppose to be set to before the configuration is compiled.

**Comment by madmikep** [comment]
The main problem is you cannot name configuration files in this format
ConfigurationName.servername.MOF

https://docs.microsoft.com/en-us/powershell/dsc/partialconfigs
Naming configuration documents on the pull server in PowerShell 5.1

If you are pulling only one partial configuration from an individual pull server, the configuration document can have any name. If you are pulling more than one partial configuration from a pull server, the configuration document can be named either <ConfigurationName>.mof, where ConfigurationName is the name of the partial configuration, or <ConfigurationName>.<NodeName>.mof, where ConfigurationName is the name of the partial configuration, and NodeName is the name of the target node. This allows you to pull configurations from Azure Automation DSC pull server.

**Comment by johlju** [comment]
@madmikep If that is not possible to do in the next Current Branch release of Windows Server then I don't think that will be supported on Windows Server.

Below snippets are from [Windows Pull Server Planning Update – April 2018](https://blogs.msdn.microsoft.com/powershell/2018/04/19/windows-pull-server-planning-update-april-2018)

>In the next Current Branch release of Windows Server a new feature will be released to provide support for SQL Server as the database platform to support Windows Pull Server for DSC.
>...
>Following this release of Windows Pull Server, there are no additional plans to release new features to the pull service capability in Windows Server.
>...
>The focus for new features in DSC pull service will be delivered in Azure Automation DSC.

Please also see 'Community maintained solutions for pull service' in the same blog article.

**Comment by johlju** [comment]
Closing this issue as per previous comment. If this was closed in error please reopen or comment.

**Comment by sblasko4868** [comment]
I am having a similar issue. I have a pull server and am trying to set the ip addresses of multiple servers using NetworkingDsc. Here's my script to create the MOFs and checksums:
````powershell
Configuration ServerIP
{
    Import-DscResource -Module NetworkingDsc

    Node $AllNodes.NodeName
    {
        DhcpClient DisabledDhcpClient
        {
            State          = 'Disabled'
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPv4'
        }

        IPAddress IPv4Address
        {
            IPAddress      = $Node.IPAddresses
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPV4'
        }
    }
}

$config = @{
    AllNodes =
    @(
        @{
            NodeName = 'Server01'
            IPAddresses = @('10.0.0.1','10.0.0.2')
        },
        @{
            NodeName = 'Server02';
            IPAddresses = @('10.0.0.3','10.0.0.4')
        }
    )
}

ServerIP -ConfigurationData $config
New-DscChecksum
````
This creates Server01.mof and Server02.mof (and their checksum files) which I rename to ServerIP.Server01.mof and ServerIP.Server02.mof (along with the checksum files).  I add them to my pull server config directory and added the partial configuration to the LCM on Server01 and Server02. It ran successfully on Server02 the first time, but now I get an error when I run Update-DSCConfiguration on either of the servers:
`Please ensure the partial configuration and its checksum exist on the server. Check the DSC event logs for further details.`
When checking the logs after I ran the initial successful Update-DSCConfiguration on Server02 the first time there was a warning:
`Executing Get-Action with configuration 's checksum returned result status: Retry`

Am I missing something or do I have to create an individual config for each server and add different partial configurations to each server? Why can't I use ConfigurationName.ServerName.MOF as a naming convention?
