### ISSUE TITLE
When using the DSC file resource to update a directory and using any of the checksum algorithms (e.g. SHA-1, SHA-256,...) .PDB and .RPT files will not get updated

### ISSUE THREAD

**Issue by plraustin** [PowerShell/DscResources#306]
https://connectbeta.microsoft.com/PowerShell/feedback/details/2004030/dsc-file-resource-does-not-copy-pdb-files-when-using-a-checksum-algorithm

**Comment by loshurik** [comment]
cannot leave a comment at connectbeta.microsoft.com
I have the same issue with a *.zip file described as a file resource

**Comment by johlju** [comment]
@plraustin @loshurik the link does not work anymore, do either or both of you have an example of a configuration that could help to see where we can take this issue?

**Comment by johlju** [comment]
Closing this as not fixed due to lack of response. Please reopen or comment if this was closed in error.
