### ISSUE TITLE
HEAD for modules should always point to module's 'master' branch

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/DscResources#31]
[Trond Hindenes   (Tue, Jun 23 2015 3:14 PM)](http://blogs.msdn.com/b/powershell/archive/2015/06/23/10623502.aspx)

"Just a note regarding submodules in git: Remember that the parent repo points to a certain commit in the submodule. This means that whenever a submodule is updated, the parent repo must be updated with the updated commit id in order to reflect the HEAD of the submodule branch. For example, looking at the master branch of the xActiveDirectory resource, the parent repo points to a commit in there that's a couple of months old. If someone simply clones the parent repo with included submodules they'll be looking at fairly out-of-date code.

(it's pretty easy to script auto-updating the parent repo using git and powershell :-) )"

**Comment by tysonjhayes** [comment]
That explains quite a bit when I pulled it down the last time. Seriously this should point to HEAD.

**Comment by vors** [comment]
You can see that in [.gitmodules](.gitmodules) there is no particular commits. By default it points to `master` branch, that's it.

**Comment by vors** [comment]
Ah, I finally start understanding what is this comment about. We need to figure out, is it possible to make submodules to simply point to the HEAD of default branch in the repo.

**Comment by KarolKaczmarek** [comment]
As a temporary solution, I wrote a script to update all submodules and they are up to date (as of now). Ideally, we should have it updated automatically - will work on it.

**Comment by vors** [comment]
Maybe the right way would be simple get rid of submodules and replace them by markdown file with links to all repos.

**Comment by tysonjhayes** [comment]
@vors while that would work I really like being able to sync everything at once. Though I guess we could write some PowerShell to parse the file and update everything. :laughing:

**Comment by joeyaiello** [comment]
@KarolKaczmarek You wrote the automation for this already, right?

**Comment by KarolKaczmarek** [comment]
I have scripts which automate it, but they need to be kicked off manually (I usually do it during new release to PSGallery). To automate it completely would be nice, but there's few higher priority items right now. I was also discussing it with Nana and we concluded that current solution is OK - git pull is all you need to update your submodules and even if you don't do it, worst case scenario you end up with code which is few weeks obsolete.. 
Shall we close this issue?
