### ISSUE TITLE
Hash table returned from Get-TargetResource must contain all properties in the schema.mof

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#318]
I trying to figure out this question; Must the Get-TargetResource always return a hash table containing **_all_** the properties in the scheme.mof?

I think @kwirkykat might have mention this somewhere - but finding that is like a needle in a hay stack.

I can't find this in any guideline or common test. I can only find this text.

>In the Get-TargetResource ... This function must return a hash table that lists all the resource properties as keys and the actual values of these properties as the corresponding values.
https://docs.microsoft.com/en-us/powershell/dsc/authoringresourcemof#writing-the-resource-script

So if this is true, then we should have a common test for it. Because then I have this problem in many resources!

**Comment by johlju** [comment]
@kwirkykat @mbreakey3 (or anyone else) can you answer this question?

**Comment by scottleyg** [comment]
There is a semantic in powershell where the first object emitted to
pipeline defines the structure for all other objects.  It is best practice
to create a new psobject and populate all fields, even if the value is
$null.  To demonstrate, take an array of $a and $b where $a = new-object
PSObject -Property @{ A = 'a' } and $b has B = 'b'.  Take turns emitting $a
or $b first.  So if you have calls to a bunch of remote machines, they all
need to return the same shape or you lose data on the pipeline.
Sorry, I'm on phone or I would give better examples.
Scottley

**Comment by bgelens** [comment]
@johlju It's in the official DSC [docs ](https://docs.microsoft.com/en-us/powershell/dsc/authoringresourcemof)

>In the Get-TargetResource function implementation, use the key resource property values that are provided as parameters to check the status of the specified resource instance. This function must return a hash table that **lists all the resource properties** as keys and the actual values of these properties as the corresponding values.

**Comment by johlju** [comment]
Yes, thats the same paragraph I quoted in the initial issue comment. 
I just wanted to make sure that the text was accurate before changing the guidelines and before trying to writing a common test to warn about missing properties in the hash table. 
Too many resources have this problem to fail the tests, at least at this point.

**Comment by randomnote1** [comment]
@johlju, thanks for raising the question/issue. I was looking at this today and realized there currently isn't a common test for this.

**Comment by johlju** [comment]
@kwirkykat Is it okay that I add this to the best practices guideline and also write a common test for this (that will write warnings for the time being)?

**Comment by ld0614** [comment]
While I agree that in most situations the Get-TargetResource should return actual values I think its important that the guidance is clarified for resources which include Add and Remove Properties (Such as the Group Resource) and resources with specific Credential objects as these don't lend themselves to returning useful values.  

A simple way to handle with would be to allow test opt-outs for specific parameters against a known set of criteria in a similar way that `[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidGlobalVars", "global:DSCMachineStatus")]` is allowed for calling a reboot.

**Comment by johlju** [comment]
I suggest we move this issue to DscResource.Tests so that we can add a test for this.

**Comment by johlju** [comment]
I have created an issue in DscResource.Tests which referencing this issue. Closing this issue here, and suggest moving any further discussion to the issue https://github.com/PowerShell/DscResource.Tests/issues/220.

**Comment by johlju** [comment]
For reference, this error is output when trying to return a property that does not exist in the schema. Unfortunately there is apparently not the similiar check when the hash table is not returning all properties in the schema.

```
Get-DscConfiguration : The PowerShell DSC resource  returned results that are not valid from Get-TargetResource. The XYZ key is not a valid property in the corresponding DSC resource schema file. The results from 
Get-TargetResource must be in a Hashtable format. The keys in the Hashtable must be the same as the properties in the corresponding DSC resource schema file.
```
