### ISSUE TITLE
DSC Core Discussion: What does this mean for the DSC Resource Kit?

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#319]
As @grayzu has announced [the future of DSC with the new DSC Core](https://blogs.msdn.microsoft.com/powershell/2017/09/12/dsc-future-direction-update), I thought it might be good to understand what will be required for the DSC Resource Kit and other DSC Resources.

So I thought I'd open this issue to try and start discussion and hopefully as information comes to light we'll be able to assemble it.

My first and biggest question: Are DSC and DSC Core resources going to be compatible?

**Comment by ld0614** [comment]
It was interesting to note that there was no mention of class based resources in the announcement, is this because they will continue to share the same compatibility as MOF based ones?

**Comment by MathiasMagnus** [comment]
My first question would be: what is the timescale people can expect a beta release? I was hoping to play with it over the holidays on my test bed.
