### ISSUE TITLE
Pester 4.0.7 breaks tests because Assert-VerifiableMocks renamed to Assert-VerifiableMock

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#320]
As of Pester 4.0.7 the `Assert-VerifiableMocks` cmdlet is renamed to `Assert-VerifiableMock`.

See: https://github.com/pester/Pester/releases/tag/4.0.7

To resolve this issue, change all tests that use `Assert-VerifiableMocks` to `Assert-VerifiableMock`.

**Comment by johlju** [comment]
There are still resource modules that have this problem, but I guess that will be caught in the tests, and resolved. I suggest we close this issue now.

**Comment by PlagueHO** [comment]
Agreed - let's close it!
