### ISSUE TITLE
CLA singing BOT has changed

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#323]
It seems the CLA signing BOT has been changed (and improved). 

We need to change our documentation to reflect this. If the labels are no longer used.

![image](https://user-images.githubusercontent.com/7189721/30872942-f7f8e7be-a2eb-11e7-9249-c398b926c481.png)

See PR https://github.com/PowerShell/xSQLServer/pull/840

**Comment by johlju** [comment]
Seems all current PR's need to be closed and reopened to get the new CLA status.

**Comment by PlagueHO** [comment]
Ooooh - I hadn't noticed that.
