### ISSUE TITLE
Undeclared FunctionsToExport in manifest causes publishing of module to fail to local psgallery

### ISSUE THREAD

**Issue by ericjaystevens** [PowerShell/DscResources#325]
When attempting to upload this module to a private Powershell gallery using `Publish-Module -Name sharepointdsc -Repository PSPrivate -NuGetApiKey "XXXXXXXXXXXXXXXXX"` will 
fail with the following error. 
```
Publish-PSArtifactUtility : The property 'FunctionsToExport' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:853 char:17
+                 Publish-PSArtifactUtility -PSModuleInfo $moduleInfo `
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Publish-PSArtifactUtility], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Publish-PSArtifactUtility
```

This is the expected outcome given that FunctionsToExport is not declared in the module manifest. See [This One Get Issue](https://github.com/OneGet/oneget/issues/178).

Convention in other DSC resources seems to be to include `FunctionsToExport = '*'` in the module manifest. An example is [the xNetworking Manifest](https://github.com/PowerShell/xNetworking/blob/dev/Modules/xNetworking/xNetworking.psd1)

**Comment by BrianFarnhill** [comment]
Interesting - doing some reading up on this I think rather than just putting in the "ToExport" options (which from the looks of it, we should be putting in all of the ToExport options, not just the functions one) it will aid performance of loading the module if we put them in as empty arrays if we don't need to load anything. Now I know the default on all of them is to load "*", so we need to do a quick test to ensure that we won't miss anything if we set them to empty arrays - but all in all a good idea. I'll put it on the backlog, should be a simple enough change for us to include in a future update. 

Thanks for reporting

**Comment by PlagueHO** [comment]
@BrianFarnhill - to confirm, did your investigation indicate that it would be better to use `FunctionsToExport = @()` rather than `FunctionsToExport = '*'` in the module manifest? If that is the case might be a good idea for me to change over to this in xNetworking, xStorage etc.

**Comment by johlju** [comment]
@ericjaystevens Did you ever test if adding if the `https://github.com/PowerShell/SharePointDsc = @()` worked as a quick-fix for you? It seems that `FunctionsToExport` has still not been added to SharePointDsc module manifest so if this is still a problem for you, then I suggest you submit an issue in [SharePointDsc](https://github.com/PowerShell/SharePointDsc) to get this resolved.

@PlagueHO I found the following as @KevinMarquette blog

>In Powershell 6.0, the FunctionsToExport default is changing to an empty array @(). This is more in-line with best practices. You should either specify the functions to export or set the value to an empty array.
>https://kevinmarquette.github.io/2017-05-27-Powershell-module-building-basics/

**Comment by johlju** [comment]
I assume this issue has been resolved. If this was closed in error, please comment and reopen.
