### ISSUE TITLE
Migrate Pester test syntax from v3 -> v4 in test templates

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#327]
As of Pester v4 the syntax of the Should cmdlet has changed from Should Be to Should -Be.

There is a helpful script that can be used to easily perform the conversion:
https://gist.github.com/indented-automation/aeb14825e39dd8849beee44f681fbab3

This script should be used to correct the Pester syntax.

**Comment by johlju** [comment]
@mnewswanger While you are on a roll with xSQLServer and xFailOverCluster. Maybe you want to fix this issue in the templates in this repo as well? 😄 

https://github.com/PowerShell/DscResources/tree/master/Tests.Template

**Comment by mnewswanger** [comment]
Sure, I'll knock it out
