### ISSUE TITLE
Update guidelines to the New Pester syntax

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#330]
As of issue #327, the recently merged guideline should also change to reflect the new Pester syntax. 
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#capitalized-pester-assertions

Also the TestGuidelines.md should also be updated to be new Pester syntax. 

_Open this issue instead of adding on to issue #327 since that PR resolving has gone thru review and are about to be merged._

**Comment by PlagueHO** [comment]
@johlju - I've submitted a PR for this one (and to fix up the MD rule violations to `TestGuidelines.md`).

See https://github.com/PowerShell/DscResources/pull/336
