### ISSUE TITLE
Can we add a CODE_OF_CONDUCT.md to a repository

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#337]
To use the recommended community standards a CODE_OF_CONDUCT.md file should be present in the root of the repository. See https://github.com/PowerShell/DscResources/community.

I suggest we add a CODE_OF_CONDUCT.md with the same information as in the README.md. But is it okay to remove the code of conduct information from the README.md in favor of the CODE_OF_CONDUCT.md? Or, in the README.md point to the CODE_OF_CONDUCT.md?

Update: Change the link to point to this repository community page.

**Comment by johlju** [comment]
@zjalexander could you please look into this?

**Comment by zjalexander** [comment]
heads up, i do have to coordinate this with the microsoft oss team. they want us to be "consistent" "across repos" for some reason :) not sure if this is already part of their guidance or not, so a bit of investigation is needed on my end

**Comment by johlju** [comment]
@zjalexander Absolutely I guessed so much. But thought it would be more of a legal issue. But I will await your answer.

**Comment by johlju** [comment]
@zjalexander Did you have a chance to contact the Microsoft OSS team before the holidays?

**Comment by johlju** [comment]
@zjalexander any updates on this? Not sure you are working on Dsc Resource Kit any longer. If not, then maybe @kwirkykat can see if the above is "allowed" by the OSS Team?

**Comment by zjalexander** [comment]
@mgreenegit is the contact for the resource kit now, thanks for your patience on this issue

**Comment by johlju** [comment]
See PR https://github.com/PowerShell/SqlServerDsc/pull/940 - that proposes to move the Code of conduct from the README.md to a separate file CODE_OF_CONDUCT.md - this is to use the "GitHub standard" by adding a file for code of coduct. That resolves the check here; https://github.com/PowerShell/DscResources/community

I'm okay by both, keeping it in the README.md or moving it out to a separate file - but above Zachary lifted the question that maybe the Open Source team. I will lift the question to the Open Source team.

**Comment by johlju** [comment]
I talked to MS Open Source Team and they provided this link; https://opensource.microsoft.com/codeofconduct/faq/#howadopt. They also said they aren't enforcing a specific location of the text, and if we want the check mark to be green we could "improvise" (my word, not theirs). 

So I propose this, to be compliant with the previous link, and also get the green check mark I suggest we replace the text in the README.md with something like `This project has adopted [this code of conduct](\CODE_OF_CONDUCT.md).`.

Also suggest that this is up to the maintainers to decide if they want to do. We don't add a guideline for this. 

I leave this open and let Stale auto-close this one if there are not more comments.

**Comment by PlagueHO** [comment]
I think I'll look at adding this to the repos I maintain. It is fine with me if this isn't an enforced guideline.

**Comment by johlju** [comment]
Closing this issue at this time.
