### ISSUE TITLE
Is there any way to delay the DSC execution util the Window operation system restart completely? 

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#339]
Hello, Team,

We faced one issue in the DSC pull mode as below:
In the DSC pull mode, when the computer restarted,  the DSC will automatically execute the DSC resource even if the corresponding window operation system is not fully ready, for example, Applying Group policy Drive Maps policy.

Is there any way to delay the DSC execution until the Window operation system restart completely?  Thanks in advance

**Comment by chancein007** [comment]
Is there any update? Thanks in advance

**Comment by ArieHein** [comment]
Do you have drive mapping in the computer section ?
If its in the user section, why would DSC need to access a drive that is only available when a user logs in. what happen if there's no user logging in ?
Windows in itself will allow logging in to windows even if group policy didn't complete fully
A raw way to pass that is to add a script resource that runs a powershell command to just wait or count to 10000 or any action that causes delay and placing it as the first resource while all the others have a "DependsOn" on that scrip resource.

But you should ask yourself if you're using DSC for the right thing. One aspect will be to move some of the policies outside of GP/GPP and into a resource as considerably GP object just changes values in the registry. That said , not ones that are in the User section.

**Comment by johlju** [comment]
@chancein007 did you get you question answered?

**Comment by johlju** [comment]
Closing this question as answered. Please reopen or comment if this was closed in error.
