### ISSUE TITLE
DSC job ID changed after reboot?

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#340]
Hello, Team,

We used one MOF files to do some configuration for 200 windows server operation system in the pull mode； In this MOF file, we referred to more than 10 DSC resources, at the 5th DSC resource, the 5th DSC resource in the end will send signal to DSC client to restart itself. unfortunately, we found that the DSC job ID has been changed after the server that installed DSC client reboot.  In this case, it is a little difficult to trace all of the operation in the same MOF using the same Job Id since there will be 2 different DSC job ID after rebooting. Is the DSC bug or is there any configuration or setting that we can avoid this issue? 

Happy New year and any help is much appreciated!!!!

**Comment by chancein007** [comment]
Is there any update? Thanks in advance

**Comment by ArieHein** [comment]
Can you give an example of what you mean by JobID changed ?

I think you're facing one of the limitations of dsc and MOF file in general, that there's no orchestration tooling around it. You cant use one mof file to 'rule them all', what you might want to do is use 2 mof files, one the "before" and one "the after" and the way to use it will be to put the second mof file in the configuration folder and rename it pending.mof then when the server reboots, the lcm will start and 5-15 min later will use the pending.mof.
Not the most elegant way to do it but as said earlier there are no orchestration tools yet that I know of that can manage restarts etc

**Comment by johlju** [comment]
@chancein007 did you get your question answered?

**Comment by johlju** [comment]
Closing this issue as not fixed due to lack of response. Please reopen or comment if this was closed in error.
