### ISSUE TITLE
DSC Agent somestime doesn't write the job execution result to the Access Database

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#342]
Hello, Team,

We used the pull mode when using DSC server over https with Access Database, we found that sometimes, we can see the DSC agent Job information, however, in the DSC Report Access database, we didn't query the corresponding record with this specified jobID.  Is there DSC agent or DSC report server bug? Or is it due to wrong configuration in the DSC agent or DSC report server side? Any help is much appreciated.

**Comment by chancein007** [comment]
Is there any update? Thanks in advance

**Comment by chancein007** [comment]
Is there any update? Thanks in advance

**Comment by johlju** [comment]
@chancein007 Could you provide a more detailed explanation on what you trying to do?

**Comment by johlju** [comment]
Closing this as not fixed due to lack of response. Please reopen or comment if this was closed in error.
