### ISSUE TITLE
xActiveDirectoryDomainController - exclude DNS Server Install

### ISSUE THREAD

**Issue by my55tec** [PowerShell/DscResources#345]
Using xActiveDirectory module, specifically xActiveDirectoryDomainController ... we use external DNS, but merged w/Domain that had integrated DNS.  Upgrading the other domain to 2016, xADDC would install DNS server since it's integrated.  Found no option in xADDC that would allow me to exclude.

Note:  First issue submitted ... also solved the issue by updating xADDC and repackaging.  Plan to upload it here, having trouble figuring out how to do so.

**Comment by johlju** [comment]
@my55tec sorry that you haven't got an answer until now. But we are happy to have you here! If you create an issue in the repository https://github.com/PowerShell/xActiveDirectory and then you can add you changes as a pull request. If you don't know how to do so, please ask for help in that issue in the xActiveDirectory repository and I will help you over there!

**Comment by johlju** [comment]
@my55tec Please see previous comment. I'm closing this issue at this time. But I hope I will be seeing you over at [xActiveDirectory](https://github.com/PowerShell/xActiveDirectory) where I will help you getting your changes sent in as a PR. Thanks!
