### ISSUE TITLE
StyleGuide: Function Params

### ISSUE THREAD

**Issue by VertigoRay** [PowerShell/DscResources#353]
This is more of a discussion. I definitely appreciate the work done on the style guide. I've adapted my coding style to align with it; even when my personal preference has always been against it. I prefer to be inline with the community agreed upon standards.

There is one style that I do not agree with, and for good reason. The style for [*Parameters Separated by One Line*](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameters-separated-by-one-line) is the one I'm talking about. While I do agree that an *empty line* needs to be between parameters to improve readability, I disagree that the *empty line* needs to be completely empty. I prefer the comma to be on a line by itself as a separator; such as:

```powershell
[Parameter(Mandatory=$true)]
[string[]]
$Param1
,
[Parameter()]
[string[]]
$Param2
```

The reason for my preference is: 
- The comma goes between parameters, and cannot go after every single parameter.
- When the comma is on the same line as the parameter declaration, I typically cause a syntax error and have to go back and find the place I messed up. When it's a very large function, this takes a min of skimming.
- Since I started doing it as shown above, I've not caused anymore syntax issues. It seems to be more fluid for me, and improves readability.

I hope this can be considered for a community agreed upon standard. Thoughts?

**Comment by johlju** [comment]
Personally I feel the comma between the parameters make it harder to see where one parameter starts and end, but it is probably because I'm used to

**Comment by johlju** [comment]
I suggest that we wait another week for more comments on this proposal, and if there has been no more comments, we close this issue and conclude that we should keep the style guideline as is for the moment.

**Comment by VertigoRay** [comment]
Link to the *VSCode PowerShell extension* that you're using, please?

**Comment by johlju** [comment]
Easiest is to search for PowerShell among the extensions directly in VSCode, there are only one from Microsoft. But here is the link https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell.

**Comment by VertigoRay** [comment]
For the record, [here's the VSCode PowerShell extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell) that runs Script Analyzer on code change.

**Comment by gitsauce** [comment]
I prefer using the commas between parameter declarations too, but don't have technical reasons to contribute. Using just a space makes the parameters feel like they're floating, while a comma creates a definitive bond between them, so it's easier for my brain to understand the relationship of the list.

**Comment by johlju** [comment]
There are different variations to writing these parameters, another example I have saw this weekend is in the snippet below. Thank you for make a suggestion to change the guideline, but I don't think this suggestion has gotten the traction needed to change the style guideline. 

I'm closing this issue at this time. If more people think that this should be the standard, then we can open up the suggestion again. 

@VertigoRay thank you again for your contribution trying to improve DSC Resource Kit!

```
param 
(
    [Parameter(Mandatory = $true)]
    [System.String]
    $Parameter1

  , [Parameter()]
    [System.String]
    $Parameter2

  , [Parameter()]
    [System.String]
    $Parameter3
)
```
