### ISSUE TITLE
xDefender: Exclusion* param values don't get evaluted correctly inside Test-TargetResource

### ISSUE THREAD

**Issue by Vineshp11** [PowerShell/DscResources#366]
Below params which are of array types don't get properly evaluated to determine if configuration is in desired. Test-DSCConfiguration determines they not in desired state even though they are.

        $ExclusionPath,
       $ExclusionExtension,
       $ExclusionProcess,

**Comment by johlju** [comment]
@Vineshp11 The resource module xDefender has been deprecated, see notice in https://github.com/PowerShell/xDefender.
