### ISSUE TITLE
Submodules not completely removed

### ISSUE THREAD

**Issue by jpogran** [PowerShell/DscResources#369]
Performing a fresh clone and submodule update fails:

```
> git clone https://github.com/PowerShell/DscResources
> git submodule update --init
fatal: No url found for submodule path 'xDscResources/xAdcsDeployment' in .gitmodules
```
This occurs because several submodules were removed from `.gitmodules` but not removed from the cache. The following references need to be removed:

- xDscResources/xAdcsDeployment
- xDscResources/xCertificate
- xDscResources/xComputerManagement
- xDscResources/xDFS
- xDscResources/xSharePoint

**Comment by johlju** [comment]
Thank you for reporting and fixing this!
