### ISSUE TITLE
Style Guideline for Reserved Keywords

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#404]
I've just noticed that I've been enforcing the use of all lower case for keywords like `param`, `if`, `foreach`, `for`, `switch`, `try`, `catch`, `return` etc in my code reviews, but have just realized there is no actual style guideline (except for the param block - which is also tested for in DSCResource.Tests).

What is the general feeling on this? Should there be a guideline or should I stop worrying about it (:grin:)? It's pretty minor in the scheme of things, but if we did want to make it a guideline it would save me a lot of review time if I could add some automated tests for it.

**Comment by ld0614** [comment]
Personally I think that if, foreach, switch etc should be lowercase, Param I just defaulted to uppercase as I think it fits better with the Parameter attribute.  Having tests either way would definitely  help keep code aligned and covered without manual and potential inconsistent code reviews

**Comment by johlju** [comment]
I also always enforced lower-case on those too 😄 Probably because both style guideline and best practices are written like that. I like to see tests for these, since I think most code is written like this. Also a test for the space after the keyword (which is in the guideline today).
