### ISSUE TITLE
How many agent servers that PowerShell DSC 5.1 can manage?

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#419]
So far, we found that after we registered more than 2000 DSC agent servers on one DSC agent report server and later we can't register new DSC agent. 
Any suggestion is appreciated.
How many agent servers that PowerShell DSC 5.1 can manage?

**Comment by johlju** [comment]
What error message are you seeing?

I guess you are using the Windows Server [Pull Server](https://docs.microsoft.com/en-us/powershell/dsc/pullserver)? Just to understand, you have more than 2000 nodes getting the configuration from a pull server and sending reports to the pull server?
Not aware that there are a hard limit on number of nodes, but there could be that be other factors that limit, for example the underlying database might be a limit.

**Comment by chancein007** [comment]
Much appreciated for your quick response. 

Yes, we used the Window pull server.  before last week, the pull server can work well but in last weekend,  our pull server  went down for 3 days. On this Monday, we restarted our load balance servers(1 nginx +2 DSC report server + SQL Server ( using data bridge from Access to SQL Server ).  After few minutes, the Nginx server went down again.
In this case, we un-registered the DSC agent for all 2000 servers and registered again(without uninstalling the DSC pull server), however, we couldn't register again. 

The error we found in DSC Windows operation log as below:
"The configured upper limit was set to 10000."

Meanwhile, the PowerShell Console showed up the below error message: 

"Failed to register DSC agent with AgentID: xxxx-xxx-xxx-xxxx " which was threw by RegisterDSCAgentCommandFailed,Microsoft.PowerShell.DesiredStateConfiguration.command.registerDSCAgentCommand. 

Any help is much appreciated.

**Comment by johlju** [comment]
@chancein007 Would you mind opening a new issue in xPSDesiredStateConfiguration for this? It is the module where the Pull Server resides in, and there are potentially more community members there that can help you with this.

**Comment by johlju** [comment]
@chancein007 I would also suggest you open a case with Microsoft (Premier) Support so you can get more help narrowing the problem down.

>Support for Windows Pull Server in production environments will continue following the Windows Server support lifecycle.
>https://blogs.msdn.microsoft.com/powershell/2018/04/19/windows-pull-server-planning-update-april-2018/

**Comment by chancein007** [comment]
@johlju  much appreciated for your help.

**Comment by johlju** [comment]
Closing this issue since a new issue was opened in issue https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/434.
