### ISSUE TITLE
Enable branch protection on repositories

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#435]
On the repository xPSDesiredStateConfiguration there are branch protections for both master and dev.

![image](https://user-images.githubusercontent.com/7189721/44104287-c7826ac8-9fee-11e8-9cae-9924a1fe2a2a.png)

I suggest we at least add the status *licens/cla* as required before merging. 

Does anyone has any suggestion around this?

**Comment by johlju** [comment]
I have added branch protection to xExchange as a first test before we add it to the others. There was a PR needing CLA to be signed in that repo, so it was a good repo to start with.

/cc @mhendric

**Comment by johlju** [comment]
All repoistories under https://github.com/PowerShell/DscResources/tree/master/DscResources (those under the PowerShell account) now have protected branchs for dev and master. Let me know of any problems.

**Comment by PlagueHO** [comment]
Nice!!!!!

**Comment by johlju** [comment]
And now all repositories under https://github.com/PowerShell/DscResources/tree/master/xDscResources now have protected branches for dev and master.
