### ISSUE TITLE
Issue with composite resource using a configuration with parameters

### ISSUE THREAD

**Issue by Teutenberg** [PowerShell/DscResources#437]
I was following this document to create a composite resource: https://docs.microsoft.com/en-us/powershell/dsc/authoringresourcecomposite

I created a composite resource but it wouldn't show up with Get-DscResource. If it was a blank configuration it would show up with Get-DscResource, but every time I put my parameters in it would vanish again. Turns out one of my parameter names was to blame. I had a parameter called $InstanceName, and every time I added this parameter it would vanish and I'd get the below error message. So I guess $InstanceName is a reserved keyword or something? Now that I've change my parameter name to $SQLInstanceName it works as expected. 

```
PS C:\Users\waynet> Get-DscResource -Name SetupApollo -Syntax
CheckResourceFound : The term 'SetupApollo' is not recognized as the name of a Resource.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4196 char:13
+             CheckResourceFound $Name $Resources
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,CheckResourceFound
```

**Comment by johlju** [comment]
Yes, `InstanceName`, `DependsOn`, `PsDscRunAsCredential`, `OutputPath` and `ConfigurationData` is reserved parameters that are automatically added by the keyword `Configuration`. 

```
PS > configuration Example {}
PS > Example -In[Tab]

gives 

PS > Example -InstanceName
````

**Comment by johlju** [comment]
Closing this issue as answered. if that is not the case, then please reopen or comment.
