### ISSUE TITLE
StyleGuidelines.md: Line Character Limit?

### ISSUE THREAD

**Issue by mhendric** [PowerShell/DscResources#444]
Within the 'StyleGuidelines.md' file in the 'Correct Format for Arrays' section, it states: "Arrays should be written on one line unless they exceed the line character limit". However, I can't find anywhere in the style guidelines that actually say what the line character limit is. Can this be clarified in the documentation? I'm not sure if this is referring to a hard character limit for files, or if this is a style limit that should be followed. Thanks.

**Comment by johlju** [comment]
> Arrays should be written on one line unless they exceed the line character limit"
> [Correct Format for Arrays](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-arrays)

@mhendric thanks for pointing out that. A while back there was a line length limit, but that guideline was removed. That text should be removed.

Also, I think we should allow two more variants of writing arrays.

```powershell
$myArray = @(
   'Item1',
   'Item2'
)
```

```powershell
$myArray = @(
   'Item1'
   'Item2'
)
```

I will send in a PR to propose this.
