### ISSUE TITLE
Combine StyleGuidelines and BestPractices into a single document

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#448]
It is a problem that two different documents need to be searched to see if there is a guideline or best practice relating to a topic.

Therefore it might be a good idea to combine the StyleGuidelines and BestPractices together under two different sections in the same document, noting that Style Guidelines are mandatory and Best Practices are only required for HQRM modules but should be used if possible.

See #447

**Comment by johlju** [comment]
Thanks for submitting an issue for this! 😃 👍

**Comment by PlagueHO** [comment]
Doh! Totally forgot I was going to do this. Onto it now :)
