### ISSUE TITLE
Request for transfer xInternetSettings

### ISSUE THREAD

**Issue by SimonWahlin** [PowerShell/DscResources#45]
I would like to transfer a new repo for managing Zones in InternetSettings to the PowerShell org.

https://github.com/SimonWahlin/xInternetSettings

The module is passing all tests and should comply to all contribution guidelines.

The module includes one MOF-based resource (compatible with PS/WMF 4.0 and 5.0+)

**Comment by tysonjhayes** [comment]
At first blush my only gripe is that you don't use verb-noun formatting for your private functions. Otherwise it looks pretty good to me, though I'll need a bit more time to dive into the specific chunks of it.

**Comment by SimonWahlin** [comment]
Oh, I'm sory, I'll fix that.

Since a lot of other resources do the same, I got the impression that this was an accepted and easy way to recognize private functions.

**Comment by tysonjhayes** [comment]
@SimonWahlin It's a personal pet peeve of mine, most of the time the export module doesn't get specified so you'll get a warning about non-verb-noun functions which just annoys me. :grinning:

**Comment by SimonWahlin** [comment]
@tysonjhayes That is a good point. The private functions has been renamed and I also added a little more test coverage.

**Comment by KarolKaczmarek** [comment]
Thanks @SimonWahlin 
It looks good, feel free to transfer the ownership.

**Comment by SimonWahlin** [comment]
Thanks @KarolKaczmarek !

Unforturnately I get an error stating that I do not have Admin rights to 'PowerShell' organization.
ref: https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization

How do we go about that?

**Comment by KarolKaczmarek** [comment]
Can you drop me an email please? MyGitHubUsername @microsoft.com 
Thanks

**Comment by kwirkykat** [comment]
@KarolKaczmarek What's happening with this?

**Comment by kwirkykat** [comment]
Talked with @KarolKaczmarek offline. This has already been added directly to PSGallery [here](http://www.powershellgallery.com/packages/InternetSettings/1.1.0).
