### ISSUE TITLE
Links in CommunityAgenda are not valid and returning 404s

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/DscResources#466]
Most recent `Community Calls` links all return 404 not found in

https://github.com/PowerShell/DscResources/blob/master/CommunityAgenda.md

**Comment by PlagueHO** [comment]
Thanks for picking this up @SteveL-MSFT - @kwirkykat - I'm happy to submit a PR to fix this one if you like?

**Comment by mhendric** [comment]
All the community call links are still busted. Is anyone working on a fix for this? It would be good to have valid links posted prior to the 11/21 community call. Also @PlagueHO , it sounds like you know what's wrong. Is there a workaround for this? How would I modify this link to get it to work?

https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/11-21-2018

**Comment by SteveL-MSFT** [comment]
cc @mgreenegit @nitinbps

**Comment by PlagueHO** [comment]
@mhendric - I'll raise this at the community call today...I think it's today - I haven't myself been able to track down an updated ICS :grin: @mgreenegit , @kwirkykat ?

**Comment by mhendric** [comment]
@PlagueHO, @mgreenegit, @kwirkykat, do you have a link to join today's call that you can share? I'm still not sure how any of us are supposed to join it if all the links are busted.

**Comment by PlagueHO** [comment]
@mhendric - this ICS does work: https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/DSC%20Resource%20Kit%20Community%20Call%20ICS.zip

But you have to adjust last week's call to be today. It contains all the Skype details.

**Comment by mhendric** [comment]
Thanks @PlagueHO . Looks like @mgreenegit has the direct join link listed in this: https://github.com/PowerShell/DscResources/pull/468. That being said, I wonder if this join information should just be added directly to https://github.com/PowerShell/DscResources/blob/master/CommunityAgenda.md so we don't have to keep repeating it elsewhere.

## How to Join

#### Skype for Business

[Join Skype Meeting](https://meet.lync.com/microsoft/zachal/QY5QHM2Z)  
Trouble Joining? [Try Skype Web App](https://meet.lync.com/microsoft/zachal/QY5QHM2Z?sl=1)

#### Phone

Toll-free number: +1 (866) 641-7188 
Toll number: +1 (773) 917-4061 
Conference ID: 596307    (Dial-in Number)  
[Find a local number](https://dialin.lync.com/48b4c613-cc67-4825-8175-29628d9715e5)  
Conference ID: 596307   (same as access code above)
[Help](http://go.microsoft.com/fwlink/?LinkId=389737)  

Participants using the Join by Phone option must dial the full number for call access.

**Comment by mhendric** [comment]
Looks like the Join link doesn't work. Sigh...

**Comment by PlagueHO** [comment]
Yep - just found the same thing. Phone number either:
https://twitter.com/dscottraynsford/status/1067870664281878529

**Comment by PlagueHO** [comment]
@SteveL-MSFT, @mgreenegit, @kwirkykat  - I'm keen to refactor and clean this up. Who is currently looking after this repo - it has been a bit quiet lately?

**Comment by SteveL-MSFT** [comment]
@PlagueHO I'll ping @mgreenegit and @nitinbps internally so they are aware of this.  However, given the holidays don't expect anything until after the new year.  If you're willing to clean it up, I'm sure they will happily review a PR :)

**Comment by PlagueHO** [comment]
Cool! Thanks @SteveL-MSFT - I'll get the PR sorted for when they're back from the holidays!

**Comment by mgreenegit** [comment]
@plagueho this PR should fix the issue.  I don’t have permission to merge.  I’d like to get this through and then make an update to switch the time format.

https://github.com/PowerShell/DscResources/pull/468

**Comment by PlagueHO** [comment]
Thanks @mgreenegit. Cool with me to separate the change to the date formats. I'm happy to review your PR but don't have merge rights either. I think there is a merge conflict though that needs to be resolved.

**Comment by SteveL-MSFT** [comment]
@mgreenegit I think the DSC team should either fix the links so they don't get 404s or at least remove them as those links aren't valid

**Comment by PlagueHO** [comment]
@SteveL-MSFT - I have a proposal (and a branch) to correct all these. I'll get it actioned - we just didn't have anyone active in this repo who had merge permissions.  But as @gaelcolas does now (I think) then I'll submit my PR to correct these.

My suggestion is that we adopt ISO 8601 for date formats in folder names.

**Comment by gaelcolas** [comment]
Merged in. We'll improve the content too. Thanks @PlagueHO.
