### ISSUE TITLE
Multiple DSC Class Resources in One Module

### ISSUE THREAD

**Issue by SimeonGerginov** [PowerShell/DscResources#467]
Is it possible to have multiple DSC Class Resources in One Module, where each Resource is in a separate file? I have tried to implement each resource in a separate module and then have a wrapper module that exposes all DSC Class Resources (In the wrapper module manifest file I pass all resources modules to the nested modules array and all resources names to the DscResourcesToExport array). The problem with my approach is that the generated schema mof files in ```C:\WINDOWS\system32\config\systemprofile\AppData\Local\dsc\``` have wrong names. The file has the name ```WrapperModule.VersionOfModule.ResourceName.schema.mof``` but when I try to run some configuration it throws an error with the following message: ```Could not find the generate schema file``` 
```C:\WINDOWS\system32\config\systemprofile\AppData\Local\dsc\ResourceName.1.0.ResourceName.schema.mof.
    + CategoryInfo          : InvalidData: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderSchemaNotFound
    + PSComputerName        : localhost
```
The reason seems to be the resources are exposed by the parent module ```WrapperModule``` and generated mof file for a resource contains the parent module name, which during configuration searches for resource's module.

Is there some workaround about the problem ?

**Comment by craig-martin** [comment]
the example (DockerDsc repository) only has one resource.  Is there another example or workaround?

**Comment by PlagueHO** [comment]
I haven't tried, but I'd think there wasn't much more involved than creating a new folder in DSCClassResources with the name of the resource and adding the resource manifest and psm1. And then adding the DSC Resource name to the manifest in the root folder. I could be wrong though. Maybe @bgelens could share his thoughts?

**Comment by craig-martin** [comment]
Got it figured out and created a test module to validate it:
https://github.com/craig-martin/TestModule

**Comment by SimeonGerginov** [comment]
@craig-martin so the generated ```schema.mof``` files have the correct names ?

**Comment by craig-martin** [comment]
The names look OK to me. You can run the test in that repo to try for yourself
https://github.com/craig-martin/TestModule/blob/master/Tests/TestModule.tests.ps1

```
/*
@TargetNode='cmartbook'
@GeneratedBy=cmart
@GenerationDate=03/09/2019 10:58:16
@GenerationHost=CMARTBOOK
*/

instance of SecondTestClassDscResource as $SecondTestClassDscResource1ref
{
ResourceID = "[SecondTestClassDscResource]sampleSecondTestClassDscResource";
 SomeString = "scripted";
 Key = "foo";
 Ensure = "Present";
 SourceInfo = "::7::17::SecondTestClassDscResource";
 ModuleName = "TestModule";
 ModuleVersion = "0.0.1";

 ConfigurationName = "ConfigUsingSecondTestClassDscResource";

};
instance of OMI_ConfigurationDocument


                    {
 Version="2.0.0";
 

                        MinimumCompatibleVersion = "1.0.0";
 

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
 

                        Author="cmart";
 

                        GenerationDate="03/09/2019 10:58:16";
 

                        GenerationHost="CMARTBOOK";
 

                        Name="ConfigUsingSecondTestClassDscResource";


                    };

```

**Comment by gaelcolas** [comment]
Since you got your answer I'm going to close this one.
I did open an issue in the [template repository](https://github.com/PowerShell/DscResource.Template/issues/11) to follow up and see if we can document this better.

**Comment by SimeonGerginov** [comment]
The solution @craig-martin provided works for resources that do not have common things between them. However, if you have a base class with common logic and two resources that inherit from it the provided solution would not work. For example:

```powershell
 class BaseClass {
     [DscProperty(Key)]
     [string] $SomeProperty
 }
```

```powershell
 [DscResource()]
 class A : BaseClass {
 }
```

```powershell
 [DscResource()]
 class B : BaseClass {
 }
```

The only way I found is to define the ```BaseClass``` in a separate module and use the following construction to import it:

```
 Using module <Module of Base Class>
```

However when using the ```Get-DscResource``` cmdlet the following error is thrown:
```
 Exception calling "ImportClassResourcesFromModule" with "3" argument(s): "Class feature already 
 defined.
```

So at the moment I am not sure that having Multiple DSC Class Resources in one module is possible when having to reuse some logic.
