### ISSUE TITLE
nupkg includes .git .github .vscode etc

### ISSUE THREAD

**Issue by mhendric** [PowerShell/DscResources#469]
It looks like many, if not all, of the recent DSC module packages include files they shouldn't (nupkg includes .git .github .vscode). Current known modules with this problem are xExchange, xWebAdministration, and xBitlocker. @kwirkykat , can you take a look at this?

Related Issues:
https://github.com/PowerShell/xExchange/issues/342
https://github.com/PowerShell/xWebAdministration/issues/406

**Comment by PlagueHO** [comment]
I've dropped an e-mail to the @mgreenegit as well just in case @kwirkykat isn't about.

**Comment by PlagueHO** [comment]
@mhendric - I'm told @kwirkykat is looking into it and the team are aware of the issue.

**Comment by PlagueHO** [comment]
@mgreenegit , @kwirkykat - any update on this one?

**Comment by PlagueHO** [comment]
Just so we have a link to the root cause:
https://github.com/PowerShell/PowerShellGet/issues/378

This should now be resolved - the new ones don't have the hidden files included.
