### ISSUE TITLE
Seems like all xDscResources are shipping with .git and .vscode

### ISSUE THREAD

**Issue by csharmath** [PowerShell/DscResources#470]
I've noticed this with xWebAdministration first
https://github.com/PowerShell/xWebAdministration/issues/406

Then saw it with xExchange
https://github.com/PowerShell/xExchange/issues/342

Then checked a couple of the xDSC resources and all of them are shipping with .git and .vscode, etc.
So something is missed on the deployment pipeline and I thought that it's more appropriate to file the issue here.

**Comment by PlagueHO** [comment]
@kwirkykat - this does seem to be the case with some of the resources that went out in the most recent resource kit release.

The following resources have been affected:
- AuditPolicyDsc
- DFSDsc
- SecurityPolicyDsc
- xBitlocker
- xExchange
- xHyper-V

The following resources that were released in Nov are not affected:
- NetworkingDsc
- SharePointDsc

xWebAdministration is affected but did not get deployed in the Nov DSC resource kit release. So this might have been occurring for a while.

**Comment by PlagueHO** [comment]
@mgreenegit , @kwirkykat - any update on this one?

**Comment by PlagueHO** [comment]
Just so we have a link to the root cause:
https://github.com/PowerShell/PowerShellGet/issues/378

**Comment by PlagueHO** [comment]
It does look like the recent release that went out has not included the problem files. Should we close this one?

**Comment by csharmath** [comment]
This is getting resolved with https://github.com/PowerShell/PowerShellGet/pull/395
