### ISSUE TITLE
Add Best Practice around Pester Parameters for It and Context

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#473]
We should add guidelines around "It" and "Context" blocks. This could be an best practice as I know many repos don't do this (many of mine don't). 

`It` description should begin with 'Should'. E.g. ```It 'Should return $true'```

`Context` description should begin with 'When'. E.g. ```Context 'When the website exists'```

@johlju - your thoughts? I'm happy to submit if the community agrees.

**Comment by johlju** [comment]
Kicking the stale bot as this is something we should add.

**Comment by PlagueHO** [comment]
I'll get onto this.
