### ISSUE TITLE
Add *.exe as binary to .gitattributes in Template

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#477]
This is to ensure Git knows to treat *.exe files as binaries:
```
* text eol=crlf
*.exe binary
```

**Comment by PlagueHO** [comment]
Bump. Still on my plate.

**Comment by gaelcolas** [comment]
That one should probably be transferred to DscResource.Template?

**Comment by PlagueHO** [comment]
Done: https://github.com/PowerShell/DscResource.Template/issues/12
