### ISSUE TITLE
AD DS and AD WS won't start 

### ISSUE THREAD

**Issue by kenazk** [PowerShell/DscResources#53]
Using the 2.2 extension, the AD will not start the service. This results in failure when querying or adding another machine to the domain. 

![adds](https://cloud.githubusercontent.com/assets/1482985/9418892/3bfd26b0-480c-11e5-83ef-df95d1095577.png)

**Comment by KarolKaczmarek** [comment]
Hi @kenazk 
This seems to be xActiveDirectory specific. Can you please open issue here: https://github.com/powershell/xactiveDirectory/ and close this one?
Thanks

**Comment by kenazk** [comment]
Closing. 

https://github.com/PowerShell/xActiveDirectory/issues/29
