### ISSUE TITLE
DSC Resource for ngen.exe /executeQueuedItems

### ISSUE THREAD

**Issue by qmfrederik** [PowerShell/DscResources#54]
After installing a new version of .NET, the  .NET Framework Optimization Service (`mscorsvw.exe`) kicks in and will start to generate native images of the .NET assemblies available on the PC. It does so in a background service. See [http://blogs.msdn.com/b/dotnet/archive/2013/08/06/wondering-why-mscorsvw-exe-has-high-cpu-usage-you-can-speed-it-up.aspx] for some more information.

When automating the deployment of .NET as part of a DSC Configuration, you may want to force the generation of native images. You do so by running `ngen.exe /executeQueuedItems` for each version of ngen installed on your PC (one per .NET version)

I've generated a DSC Resource that allows you to trigger the the `ngen` command, and would like to contribute it as a general DSC Resource.

You can find the current version at [https://github.com/quamotion/powershell-dsc/tree/master/vso-agent/NGen].

I would like to understand whether the PowerShell is interested in such a module. If yes, I'd be happy to go through the work to adapt the current module according to the PowerShell coding guidelines.

**Comment by KarolKaczmarek** [comment]
@nanalakshmanan Thoughts?

**Comment by johlju** [comment]
@qmfrederik sorry for the extreme delay in responding to your query. I can't find the resource that you link to above, and it has gone almost three years so that is understandable. I just want you to know that if you created a DSC resource module and you want to added to the DSC Resource Kit, I would be happy to help you in that process.

**Comment by qmfrederik** [comment]
@johlju Yup, things can change in 2,5 years 😄 . We've since moved to .NET Core, so this issue is no longer relevant to us.

It looks like we've also deleted the powershell-dsc repository as a side-effect.

Since the original repo has been deleted, and this is no longer an issue for us, I'll go ahead & close this issue for now.
