### ISSUE TITLE
DSCCore

### ISSUE THREAD

**Issue by steskalja** [PowerShell/DscResources#544]
Has there been any official update or plan for DSCCore now that Powershell v7 is out? Many people have on-prem requirements and cannot use Azure DSC.

**Comment by gaelcolas** [comment]
If you call it DSC core that means you might have missed the last "DSC Planning update".
Here's the link: https://devblogs.microsoft.com/powershell/dsc-planning-update-june-2019/
Look at Azure Arc and Azure Policy Guest Configurations that lets you manage on-prem VMs with an Azure Control plane.
Look into Invoke-DscResource for PS7.

And keep an eye on PSConf.EU videos and chat to discuss in more details.
