### ISSUE TITLE
Support statement should be added to readme(s)

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/DscResources#56]
Support statement from technet on [DSC Resource Kit (All Modules)](https://gallery.technet.microsoft.com/scriptcenter/DSC-Resource-Kit-All-c449312d), in second paragraph on introduction was not ported to github.

**Comment by KarolKaczmarek** [comment]
From what I know that was made on purpose, similarly there's no "support statement" on any module's repository readme. 
Also, there are still plans to get rid of "x" convention: https://github.com/PowerShell/DscResources/issues/27 

@nanalakshmanan , @HemantMahawar Should we be still adding:
```
All of the resources and examples in the DSC Resource Kit are provided AS IS, and are not supported through any Microsoft standard support program or service. The "x" prefix on each module and resource stands for experimental , which means that these resources may be maintained and monitored by the module owner(s) moving forward.
```
to DscResources/specific resources repo readme?

**Comment by johlju** [comment]
I suggest we close this issue since there is a new and updated support statement in the [Supportability.md](https://github.com/PowerShell/DscResources/blob/master/Supportability.md).

**Comment by johlju** [comment]
Closing this as solved as per previous comment. Please reopen or comment if this was closed in error.
