### ISSUE TITLE
New DSC Resource, xPfxImport for existing xCertificate module

### ISSUE THREAD

**Issue by briantist** [PowerShell/DscResources#58]
> What system will your DSC resources be managing?

Public Key Infrastructure (PKI)

> Will your module include MOF-based resources (compatible with PS/WMF 4.0 and 5.0+) or class-based resources (only compatible with PS/WMF 5.0+)

MOF-based

This is code I've been using for over a year internally. Currently the only resource is `xPfxImport` which is used to import a certificate and/or key to the cert store from a PFX file. It makes use of DSC's ability to encrypt credentials to keep the PFX extraction password safe.

I use this to distribute commercial SSL certificates to web servers (the existing IIS resources can be used to set the bindings after that).

**Comment by briantist** [comment]
I've gone ahead and put up what I've got. The only thing I can't figure out is how to get my AppVeyor badge. I assume I have to actually sign up for it?

https://github.com/briantist/xPKI

**Comment by mgreenegit** [comment]
Very cool.  Should it be part of xCertificate?

**Comment by briantist** [comment]
@mgreenegit I think you might be right. I'll restructure and submit a PR that adds `xPfxImport` to the `xCertificate` module. Thanks!

**Comment by briantist** [comment]
@mgreenegit is there anything else I need to do here? If I've missed something I'm glad to correct it.
