### ISSUE TITLE
Request to submit xCertificate module to Resource Kit

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/DscResources#6]
https://github.com/mgreenegit/xCertificate

**Comment by mgreenegit** [comment]
I believe this module is ready for transfer.

**Comment by vors** [comment]
You should be able to [transfer](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#contributing-a-new-dsc-resource-module) it to PowerShell org from project settings. Feel free to do it with other projects as well. @KarolKaczmarek is working on a batch release and release process right now. We can include your modules in it.

**Comment by KarolKaczmarek** [comment]
Module has been transferred PowerShell org and version 1.0.0.0 released to PowerShell Gallery http://www.powershellgallery.com/packages/xCertificate
