### ISSUE TITLE
Many problems with style guide.

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/DscResources#65]
1. Windows doesn't care about newlines. Only notepad.exe does. PowerShell doesn't care about CR+LF vs CR.
2. Line length is too hard to do in ISE https://github.com/PoshCode/PowerShellPracticeAndStyle/issues/30
3. Variable name case rules are relics from languages that have **both* case-sensitive and un-prefixed variables, where you can't tell a variable from a property in codes. In PowerShell you can tell a variable from a property because it has a `$` in front of it -- there's no real reason why anyone should care about variables being camelCase while functions are PascalCase.

Oh, and I don't like your brace guidelines :-p and neither do _most_ PowerShell power users :stuck_out_tongue: https://github.com/PoshCode/PowerShellPracticeAndStyle/issues/24

**Comment by Jaykul** [comment]
For what it's worth, obviously every repository owner is entitled to have their own style guidelines, and enforce them, but because this is owned by "PowerShell," I think you need to state that very clearly. Your StyleGuide is already being cited in issues filed against PSScriptAnalyzer...

**Comment by KarolKaczmarek** [comment]
Hi @Jaykul, thanks for bringing this up.

As with any style conventions, it's a matter of preference and not everyone will be of the same opinion.
Every programmer has own habits and preferences but I think we can all agree that following consistent guidelines makes the code cleaner, easier to read and understand for other contributors. 
More important than what rules we follow, is that we are consistent with it.

I don't think not having editor support for enforcing them (like line length) or technical restrictions(PowerShell being case-insensitive) should be reason to ditch them. However, if you think that some of the rules do not make sense or don't give any benefit, I'm open to discussing it and don't have and would be happy to modify the guidelines.

Regarding CR+LF vs CR line endings... perhaps @vors could give more context on why he introduced it? Was there any particular issue you were facing when using CR+LF?

**Comment by vors** [comment]
Consistency in line endings is on the list to avoid meaningless git diffs introduced by line end changes. Since we target windows, we use CR+LF everywhere.

**Comment by Jaykul** [comment]
Like I said in my follow-up comment, I should have been clear at the beginning -- the only problem is that this particular style guide is in an official Microsoft PowerShell repository, and (apparently, based on comments and issues filed _in other repositories_) it's being seen by some people as an official Microsoft position about style of PowerShell code in general.

I guess my request is for you to preface the document with a statement that these are contributor guidelines for this project/repository, rather than general style guidelines.

**Comment by KarolKaczmarek** [comment]
No problem, I've sent the PR with comment about it. Please review

**Comment by Jaykul** [comment]
Thanks :-)
