### ISSUE TITLE
Not all of the Modules that contain DSC Resources have a DSC Tag

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/DscResources#68]
Some of the modules that contain DSC resources do not have a DSC tag applied to them as can be found out using the below

```powershell
find-module x* | Select-object Name,Author,Tags | Where-Object {($_.Tags -notcontains 'DSC') -and ($_.Name -notlike 'xb*') }
```
The $_.Name -notlike 'xb*' is to not find 2 Xbox related modules

**Comment by kilasuit** [comment]
@KarolKaczmarek This is very much likely related to the issue I raised in the xSharePoint Repo. https://github.com/PowerShell/xSharePoint/issues/153

**Comment by kilasuit** [comment]
@KarolKaczmarek do you happen to have any further updates on this at all?

**Comment by KarolKaczmarek** [comment]
I've updated the manifests for all modules with information about ProjectUri, LicenseUri and Tags which will workaround the issue with Publish-Module cmdlet (which didn't took those parameters into consideration unless they were also present in the manifest).

The newly released modules have tags and Uris correctly populated.
http://www.powershellgallery.com/packages/xSharePoint/0.11.0.0 

I think this can be closed now.
Thanks for reporting this issue.
