### ISSUE TITLE
Request to submit xDiskImage to Resource Kit

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/DscResources#7]
https://github.com/mgreenegit/xDiskImage

**Comment by vors** [comment]
Should it be part of https://github.com/powershell/xDisk ?

**Comment by mgreenegit** [comment]
The right think to do will be to move this and xDisk in to a new module named xStorage.  I will work on it.

**Comment by mgreenegit** [comment]
FYI, I have created a new repo named xStorage with a merger of xDisk and xDiskImage, and submitted a request to transfer the repo to the PowerShell org.

**Comment by KarolKaczmarek** [comment]
Module has been transferred to PowerShell org and version 1.0.0.0 released to PowerShell gallery http://www.powershellgallery.com/packages/xStorage/

xDisk module has been deprecated.
