### ISSUE TITLE
DSC Resource for managing W2K12+ File Server Resource Manager (FSRM)

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#70]
I have created a DSC Resource Module for managing Windows Server 2012+ File Server Resource Manager (FSRM): https://github.com/PlagueHO/cFSRM

It contains MOF based resources for the following:
- _cFSRMSettings_ configures FSRM settings.
- _cFSRMClassification_ configures FSRM Classification settings.
- _cFSRMClassificationProperty_ configures FSRM Classification Property Definitions.
- _cFSRMClassificationPropertyValue_ configures FSRM Classification Property Definition Values. This resource only needs to be used if the Description of a Classification Property Definition Value must be set.
- _cFSRMClassificationRule_ configures FSRM Classification Rules.
- _cFSRMFileScreen_ configures FSRM File Screen.
- _cFSRMFileScreenAction_ configures FSRM File Screen Actions for File Screens.
- _cFSRMFileScreenTemplate_ configures FSRM File Screen Templates.
- _cFSRMFileScreenTemplateAction_ configures FSRM File Screen Template Actions for File Screen Templates.
- _cFSRMFileScreenExclusion_ configures FSRM File Screen Exclusions.
- _cFSRMFileGroup_ configures FSRM File Groups.
- _cFSRMQuota_ configures FSRM Quotas.
- _cFSRMQuotaAction_ configures FSRM Quota Actions for Quotas.
- _cFSRMQuotaTemplate_ configures FSRM Quota Templates.
- _cFSRMQuotaTemplateAction_ configures FSRM Quota Template Actions for Quota Templates.
- _cFSRMAutoQuota_ configures FSRM Auto Quotas.

It contains Unit and Integration tests for all resources, using the DSCResource.Test\TestHelper.psm1 functions.

Note about tests: Tests require Windows Server 2012 (or above) to pass because required File Server Resource Manager feature to be installed. Tests pass on AppVeyor because AppVeyor.yml is configured to ensure the FSRM feature is installed before invoking pester.

The module doesn't have resources for managing File Tasks and File Reports, but I do plan on getting to those at some point when I have more time.

Would there be interest in moving this module over to the community module library here?

If so, I'd need to convert the resources over from BMD_ to MSFT_ and other updates to the .PSD1,AppVeyor.yml etc before transferring the repo.

Thanks!

**Comment by KarolKaczmarek** [comment]
That would be great@PlagueHO! 
I briefly went over that module and it looks great. Let me know when all tasks on your side are ready and we will start our review process to bring it under PowerShell org.

**Comment by PlagueHO** [comment]
Awesome! I'll get it done and let you know when it's ready to transfer and you can eyeball it before I transfer. :+1:

**Comment by PlagueHO** [comment]
All changes done and ready to transfer over. Module is now currently available in this repo:
https://github.com/PlagueHO/xFSRM

Just take a look whenever - there is no rush at all on this. Just let me know if you're happy with it and I'll transfer it over.

Cheers and have a great Chrismas/New Year.

**Comment by PlagueHO** [comment]
@KarolKaczmarek: Just want to confirm you're not waiting on anything from me on this one?

**Comment by KarolKaczmarek** [comment]
No, sorry for the delay, I was trying to get someone to review it, but the whole team is pretty swamped with work right now and it's pretty large module. We will get to it though, thank you for your patience!

**Comment by PlagueHO** [comment]
@KarolKaczmarek: Oh no problem at all - completely understand. :smile:

**Comment by PlagueHO** [comment]
@kwirkykat - these are the DSC resource modules I was meaning when I asked the status of the reviews :smile:

There are a few others from myself and a few more from other contributors. I've also got a few more in the pipeline but I don't want to overload your team even more!

**Comment by kwirkykat** [comment]
@PlagueHO I just posted a [new guide](https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md) on submitting new resource modules.

Can you please open a PR to an empty branch in your repo so that reviewers can make comments?

This module looks good to me so far :+1:

**Comment by PlagueHO** [comment]
Thanks @kwirkykat - Should I convert the naming of this DSC Reosurce over to the HQRM naming scheme or leave it as xFSRM?

**Comment by kwirkykat** [comment]
@PlagueHO Yes. Convert to ____Dsc Format please.

**Comment by PlagueHO** [comment]
@kwirkykat  - I've finished updating this module to HQRM format:
https://github.com/PlagueHO/FSRMDsc

Once I've worked out how to perform steps 4 and 5 of the new guide I'll link the PR to the empty branch.

Thanks!

**Comment by PlagueHO** [comment]
This PR is ready for full review:

https://github.com/PlagueHO/FSRMDsc/pull/2

**Comment by kwirkykat** [comment]
Module submission progess:
- [x] 1. Separate public repository created
- [x] 2. Review pull request open
- [ ] 3. 1st reviewer approved (Katie)
- [ ] 4. 2nd reviewer approved
- [ ] 5. 3rd reviewer approved
- [ ] 6. Tests passing
- [ ] 7. Repository transferred
- [ ] 8. Module released

**Comment by PlagueHO** [comment]
Closing this one! :grin:
