### ISSUE TITLE
DSC Resource for managing W2K12+ iSCSI VHDs/Targets and Initiators

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#74]
have created a DSC Resource Module for managing iSCSI Virtual Disks and iSCSI Targets on Windows Server 2012+ as well as connecting iSCSI Initiators to iSCSI Targets on Windows Server 2012+: https://github.com/PlagueHO/ciSCSI

It contains MOF based resources for the following:
- ciSCSIVirtualDisk - creates/removes iSCSI Virtual Hard disks.
- ciSCSITarget - creates/removed iSCSI Targets using iSCSI Virtual Hard Disks.
- ciSCSIInitiator - configured iSCSI Target Portals and manages connections/sessions to iSCSI Targets.

It contains Unit and Integration tests for all resources, using the DSCResource.Test\TestHelper.psm1 functions. **However, the integration tests for iSCSI Initiators are currently disabled because although the documentation for MS iSCSI Initiators states that Loopback connections are supported, the documentation doesn't show how and I couldn't get it to work. Loopback is required for Integration tests. I have left the Integration test code there in case someone can find the documentation for iSCSI Loopback and get it working.**

Note about tests: Tests require Windows Server 2012 (or above) to pass because required iSCSI Server feature to be installed. Tests pass on AppVeyor because AppVeyor.yml is configured to ensure the iSCSI Server is installed and the iSCSI Initiator service is started before invoking pester.

Would there be interest in moving this module over to the community module library here?

If so, I'd need to convert the resources over from BMD_ to MSFT_ and other updates to the .PSD1,AppVeyor.yml etc before transferring the repo.

Thanks!

**Comment by PlagueHO** [comment]
Hi @kwirkykat  - This is actually a new module submission - not a proposal. The module is complete. I just haven't converted it over to the MSFT/HQRM model yet. I was waiting to hear back if it was wanted. Is this a module the PowerShell team would be interested in including?

If it is wanted then I'll convert it over to HQRM and following the new guide for submitting it.

**Comment by kwirkykat** [comment]
@PlagueHO Sure. We would love to have this in the Resource Kit! Just let me know when it's ready to go and I'll add the ```needs review``` label

**Comment by PlagueHO** [comment]
Thanks @kwirkykat.

All ready for review. The full review PR is here:
https://github.com/PlagueHO/iSCSIDsc/pull/16

**Comment by mgreenegit** [comment]
For comparison or possible merge:
https://github.com/robwi/xiSCSIServer
https://github.com/robwi/xiSCSIInitiator

**Comment by PlagueHO** [comment]
Cool! Thanks @mgreenit. I'll take a look.

**Comment by kwirkykat** [comment]
Module submission progess:
- [x] 1. Separate public repository created
- [x] 2. Review pull request open
- [ ] 3. 1st reviewer approved (Katie)
- [ ] 4. 2nd reviewer approved
- [ ] 5. 3rd reviewer approved
- [ ] 6. Tests passing
- [ ] 7. Repository transferred
- [ ] 8. Module released

**Comment by PlagueHO** [comment]
I'm going to close this one because the resource will remain maintained by me.
