### ISSUE TITLE
DSC Resource for managing W2K12+ WS-Management HTTP/HTTPS Listeners

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#75]
I have created a DSC Resource Module for managing HTTP and HTTPS WS-Management Listeners on Windows Server 2012+:

https://github.com/PlagueHO/cWSMan

It contains MOF based resources for the following:

```
cWSManListener - creates/removes HTTP or HTTPS WS-Management Listeners.
```

It contains Unit and Integration tests for all resources, using the DSCResource.Test\TestHelper.psm1 functions.

Would there be interest in moving this module over to the community module library here?

**If so, I'd need to convert the resources over from BMD_ to MSFT_ and other updates to the .PSD1,AppVeyor.yml etc before transferring the repo. Just let me know and I'll make the applicable changes and then report and it the repo can be reviewed before transfer over.**

Thanks!

**Comment by PlagueHO** [comment]
Bump! :smile:

Any word on reviews of these modules? :smile: Sorry for the nagging.

**Comment by kwirkykat** [comment]
@PlagueHO Working on them :+1:

**Comment by PlagueHO** [comment]
Thanks @kwirkykat  - sorry to be a pain :smile:

Shall I rename this module to WSManDsc and convert it over to all the MSFT stuff (e.g. license info, manifest info yada yada)?

**Comment by PlagueHO** [comment]
Hi @kwirkykat - I renamed this Module to WSManDsc and updated it with the latest test headers and methods.

The new location is here:
https://github.com/PlagueHO/WSManDsc

I'll also be adding WSManServiceConfig to this Resource Module as well this weekend - as per https://github.com/PowerShell/DscResources/issues/156

**Comment by kwirkykat** [comment]
@PlagueHO Thanks! Will look at it as soon as I can

**Comment by PlagueHO** [comment]
@kwirkykat  - thank you! Appreciate all the time you put into reviewing all this stuff!

I should have the WSManServiceConfig added to this module in the next day too.

Thanks

**Comment by kwirkykat** [comment]
@PlagueHO  I just posted a [new guide](https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md) for submitting a new resource module.

Can you please open a PR to an empty branch in your repo so that reviewers can make comments?

No red flags on this module right off the bat :+1:

**Comment by PlagueHO** [comment]
Awesome! Thanks @kwirkykat  - I'll get this over tonight. I've just about finished the new Resource I'm adding (just need to make sure the Integration tests are non-destructive). Thanks again!

**Comment by PlagueHO** [comment]
I have reworked this resource to be called WSManDSC. It now contains two resources:
WSManListener - for configuring WS-Man Listeners (HTTP or HTTPS)
WSManServiceConfig - for configuring the WS-Man Service

I haven't yet figured out how to do step 4 and 5 properly of the [new guide](https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md) however.

**Comment by PlagueHO** [comment]
@kwirkykat - the updated instructions worked flawlessly. Thanks!

Module is ready for review:
https://github.com/PlagueHO/WSManDsc/pull/1

**Comment by kwirkykat** [comment]
Module submission progess:
- [x] 1. Separate public repository created
- [x] 2. Review pull request open
- [ ] 3. 1st reviewer approved (Katie)
- [ ] 4. 2nd reviewer approved
- [ ] 5. 3rd reviewer approved
- [ ] 6. Tests passing
- [ ] 7. Repository transferred
- [ ] 8. Module released

**Comment by PlagueHO** [comment]
I'm closing this one because I've released it to the PSGallery. Still keen to have this linked as a "community owned" resource or whatever it'll be called @zjalexander . But I'll just wait till the process is nailed down.
