### ISSUE TITLE
Add a recommended design pattern for single Instance resources to documentation

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#80]
For single instance resources it isn't clear what the recommended design pattern for implementing them is. It might be worth adding this design pattern to either the contributing.md or some other document in this repo so that it can be found more easily.

The recommended method is documented by @TravisEz13 [here](http://blogs.msdn.com/b/powershell/archive/2015/06/23/want-to-write-a-dsc-resource-where-only-a-single-instance-can-be-configured.aspx).

**Comment by KarolKaczmarek** [comment]
Hi @PlagueHO,

I think the right place to add it would be the DSC documentation here: https://msdn.microsoft.com/powershell/dsc/overview

You can contribute through this repository: https://github.com/PowerShell/PowerShell-Docs 

Thanks,
Karol

**Comment by PlagueHO** [comment]
Excellent! Thanks @KarolKaczmarek - I'll close this issue.
