### ISSUE TITLE
Remove Default x and MSFT_ from Unit/Integration Test templates

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#82]
The Unit/Integration test templates are all configured to default to MSFT as the organization(?) code of the resource being tested (see https://github.com/PowerShell/DscResources/blob/master/Tests.Template/integration_config_template.ps1#L14).

They also default the module code to 'x' as well (see https://github.com/PowerShell/DscResources/blob/master/Tests.Template/integration_template.ps1#L16).

I think to make them more generic and usable for non-MSFT resources these codes should be removed from the defaults of these files.

The examples however should be left showing MSFT_ and x where appropriate (see https://github.com/PowerShell/DscResources/blob/master/Tests.Template/integration_template.ps1#L17).

**Comment by PlagueHO** [comment]
Any thoughts/objections to this one? It makes it clear that these templates can/should be used for any resources, not just the MSFT community ones.

**Comment by KarolKaczmarek** [comment]
Sorry, saw this issue and I agree, but forgot to reply.
Feel free to go ahead and implement those changes

**Comment by Justin-DynamicD** [comment]
It only makes sense to me as well.
