### ISSUE TITLE
New resource module : SecurityPolicyDsc

### ISSUE THREAD

**Issue by jcwalker** [PowerShell/DscResources#88]
What system will your DSC resource be managing?
Windows Local Security Policy

xSecedit is a wrapper around secedit.exe
- [ ] xUserRightsAssignment to manage User Rights Assignment.

**Comment by KarolKaczmarek** [comment]
repo link: https://github.com/jcwalker/xSecedit.git

**Comment by zjalexander** [comment]
Hey @jcwalker , just wanted to let you know about https://blogs.msdn.microsoft.com/powershell/2016/05/09/new-security-cmdlets-in-nano-server/

It might take some of that logic out of your existing code? We should chat. 
cc @neemas to follow up while I'm out

**Comment by jcwalker** [comment]
Hey Zach,  I was aware of that blog post and I would be happy to chat or help out anyway I can.  Ping me whenever. Alias is 'jwalker'.Date: Fri, 20 May 2016 15:51:19 -0700

**Comment by kwirkykat** [comment]
@jcwalker I just posted a [new guide](https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md) for submitting a new resource module.

Can you please open a PR to an empty branch in your repo so that reviewers can make comments?

**Comment by jcwalker** [comment]
@kwirkykat I followed the instructions for creating an empty branch.

**Comment by BrianFarnhill** [comment]
Random question - would this be something that would get wrapped up in xSystemSecurity as opposed to being its own module? Would make a bit of sense to keep security related things in the one module I would think, but happy to be told otherwise. Just wanted to put it out there for consideration.

**Comment by kwirkykat** [comment]
@zjalexander ^Any insight on whether this should be a separate module or part of xSystemSecurity?

**Comment by zjalexander** [comment]
I would prefer this be separate from xSystemSecurity, because I am trying to get this specific module to be supported by the secEdit team and they don't own the other functionality in xSystemSecurity. It would be very confusing to users to have half the resources in a module supported :)

**Comment by kwirkykat** [comment]
Module submission progess:
- [x] 1. Separate public repository created
- [x] 2. Review pull request open
- [ ] 3. 1st reviewer approved (Katie)
- [ ] 4. 2nd reviewer approved
- [ ] 5. 3rd reviewer approved
- [ ] 6. Tests passing
- [ ] 7. Repository transferred
- [ ] 8. Module released

**Comment by kwirkykat** [comment]
PR is here: https://github.com/jcwalker/SeceditDsc/pull/3

**Comment by zjalexander** [comment]
I believe we can close this issue now :) @kwirkykat
