### ISSUE TITLE
Enable Integration_tests.ps1 template to allow credentials to be used in Integration_config_tests.ps1

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#89]
Currently the integration tests template (Integration_tests.ps1) will not support credentials to be used in the integration test config file (integration_config_tests.ps1) because they would need to be encrypted (or allowed to be stored unencrypted).

Although most integration tests do not require the use of credentials (specifically the PSDSCRunAsCredential parameter) there are some that do (e.g. resources that will need to connect to an AD domain). This of course isn't applicable to any Integration tests that should be run in AppVeyor, however I do create many integration tests that can be run manually on a local users machine or non-cloud CI that do require credentials to be configured.

To support this I would propose that the Integration test template be changed so that a -ConfigurationData parameter is always passed to the Integration_test_config.ps1 when it is compiled.

E.g. Change
https://github.com/PowerShell/DscResources/blob/master/Tests.Template/integration_template.ps1#L51

Should be changed to:

``` powershell
                $ConfigData = @{
                    AllNodes = @(
                        @{
                            NodeName = 'localhost'
                            PSDscAllowPlainTextPassword = $true
                        }
                    )
                }
                Invoke-Expression -Command "$($Global:DSCResourceName)_Config -OutputPath `$TestEnvironment.WorkingFolder -ConfigurationData `$ConfigData"
```

The above code would allow unencrypted credentials to be used.

It would probably be possible to automatically create a self-signed certificate on the test machine of course and use that to encrypt the credentials as well - is it worth looking at automating credential encryption in the integration tests instead?

Does anyone have any thoughts on doing this?

Thanks!

**Comment by PlagueHO** [comment]
Further to this:
To enable self-signed certificates to be used for credential encryption in Integration tests the following process would have to happen in the Integration scripts:
1. [This script](https://gallery.technet.microsoft.com/scriptcenter/Self-signed-certificate-5920a7c6) would need to be downloaded and unzipped to a temporary location.
2. The script would be used to create a new self-signed certificate.
3. The certificate thumbprint would be loaded into the ```$configData``` object (as above).
4. The integration tests would be performed.
5. The certificate that was created in step 2 should be deleted.

*Note: the built in New-SelfSignedCertificate cmdlet can't be used to generate DSC compatible certificates in Windows Server 2012 R2. It has been improved in Windows Server 2016 TP which may allow using this cmdlet for DSC certs, but that isn't much good unless these changes are back ported to Windows Server 2012 R2.*

If the above process were to be implemented, my recommendation would be to place steps 1, 2 and 3 into the [DSCResource.Tests\TestHelper.psm1](https://github.com/Powershell/DscResource.Tests/blob/master/TestHelper.psm1) function **Initialize-TestEnvironment**. Step 5 would be added to function **Restore-TestEnvironment** in [DSCResource.Tests\TestHelper.psm1](https://github.com/Powershell/DscResource.Tests/blob/master/TestHelper.psm1).

I won't go any further forward with this idea until I get feed back from some of you guys - @tysonjhayes, @TravisEz13 and @KarolKaczmarek. But as I said, I have several DSC resources that do require this and I'd rather come up with a standardized solution.

This relates to Issue #87 as well as I think the integration tests should implement this in the "Best Practice" way.

**Comment by PlagueHO** [comment]
One further extension to this issue:
To minimize the risk of real credentials being commited back to GitHub repos I'd suggest that the **integration_template_config.ps1** be altered to always attempt to read any site specific parameters from an external config file (e.g. JSON format?).

For example add this to integration_template_config.ps1:
```powershell
# If there is a .config.json file for these tests, read the test parameters from it.
$ConfigFile = [System.IO.Path]::ChangeExtension($MyInvocation.MyCommand.Path,'json')
if (Test-Path -Path $ConfigFile)
{
     $TestConfig = Get-Content -Path $ConfigFile | ConvertFrom-Json
}
else
{
    # Example config parameters.
    $TestConfig = @{
        Username = 'CONTOSO.COM\Administrator'
        Password = 'MyP@ssw0rd!1'
        Members = @('Server1','Server1')
        Folders = @('TestFolder1','TestFolder2')
    }
}
```
I also modified the integration.tests.ps1 script to not run the integration tests if this config file was not available. 

*.config.json is in the .gitignore for this repo so that it can't be commited back to the repo as it contains site specific credentials and other test settings.

I have implemented this already in one of my [DSC resources integration tests](https://github.com/PlagueHO/cDFS/blob/dev/Tests/Integration/BMD_cDFSRepGroup.config.ps1) so that I can test it locally without requiring me to change anything in the code and minimizing the risk I might accidentally push credentials into GitHub.

Sorry about the length of this *issue*.

**Comment by johlju** [comment]
I am all for this enhancement to the integration test template. The integration tests need to have `PSDscAllowPlainTextPassword` to work around this. Was your thought that the self-signed certificate is created by the test framework, so each integration test doesn't need to have code to create it?

**Comment by johlju** [comment]
PR https://github.com/PowerShell/DscResource.Tests/pull/241 resolves using a self-signed certificate to compile configurations, so I think it's just one remaining task and that is to update the integration tests template according to https://github.com/PowerShell/DscResources/issues/89#issuecomment-177678218.
