### ISSUE TITLE
 DSC Resource for managing W2K12+ Distributed File System (DFS) Namespaces and Replication

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#90]
I have created a DSC Resource Module for managing Distributed File System (DFS) Namespaces and Replication on Windows Server 2012+: https://github.com/PlagueHO/cDFS

It contains MOF based resources for the following:
* **cDFSRepGroup** - This resource is used to create, edit or remove DFS Replication Groups. If used to create a Replcation Group it should be combined with the cDFSRepGroupMembership resources.
* **cDFSRepGroupConnection** - This resource is used to create, edit and remove DFS Replication Group connections. This resource should ONLY be used if the Topology parameter in the Resource Group is set to Manual.
* **cDFSRepGroupFolder** - This resource is used to configure DFS Replication Group folders. This is an optional resource, and only needs to be used if the folder Description, FilenameToExclude or DirectoryNameToExclude fields need to be set. In most cases just setting the Folders property in the cDFSRepGroup resource will be acceptable.
* **cDFSRepGroupMembership** - This resource is used to configure Replication Group Folder Membership. It is usually used to set the **ContentPath** for each Replication Group folder on each Member computer. It can also be used to set additional properties of the Membership. This resource shouldn't be used for folders where the Content Path is set in the cDFSRepGroup.
* **cDFSNamespaceRoot** - This resource is used to create, edit or remove standalone or domain based DFS namespaces.  When the server is the last server in the namespace, the namespace itself will be removed.
* **cDFSNamespaceFolder** - This resource is used to create, edit or remove folders from DFS namespaces.  When a target is the last target in a namespace folder, the namespace folder itself will be removed.

* **cDFSNameSpace** - _This resource is now deprecated. Use cDFSNamespaceRoot and cDFSNamespaceFolder instead. It will be removed from future versions._

It contains Unit and Integration tests for all resources, using the DSCResource.Test\TestHelper.psm1 functions. However, the integration tests for the DFS Replication require an Active Director domain and at least two servers with DFS installed.

Note about tests: Tests require Windows Server 2012 (or above) to pass because required DFS Namespace and DFS Replication features to be installed. Tests pass on AppVeyor because AppVeyor.yml is configured to ensure the required features are installed.

Would there be interest in moving this module over to the community module library here? 

If so, I'd need to convert the resources over from BMD_ to MSFT_ and other updates to the .PSD1,AppVeyor.yml etc before transferring the repo.

Thanks!

**Comment by Zuldan** [comment]
PlagueHO, I think this is a great idea. I use this resource on 27 servers in production. It would be a great addition to the community module library.

**Comment by PlagueHO** [comment]
@Zuldan, thanks! That is excellent to know this is getting some use out there in the world :smile:

@KarolKaczmarek - if you are OK with adding this resource to the community ones, let me know and I'll make the necessary name changes (MSFT_/x/appVeyor.yml etc) and let you know once they are complete.

Then all someone (@tysonjhayes, @TravisEz13? :smile:) needs to do is a code review and give me the :+1: to transfer the repo.

Thanks!

**Comment by KarolKaczmarek** [comment]
Yes, it would definitely be good to have them here!

**Comment by PlagueHO** [comment]
@KarolKaczmarek - Great! I'll convert the repo over to MSFT and x and then post a comment here when it is ready to be reviewed.

**Comment by PlagueHO** [comment]
All changes done and ready to transfer over. Module is now currently available in this repo:
https://github.com/PlagueHO/xDFS

Once the review has been done, let me know and I'll transfer it over.

Thanks!

**Comment by TravisEz13** [comment]
https://github.com/PlagueHO/xDFS/blob/dev/DSCResources/MSFT_xDFSNamespaceFolder/MSFT_xDFSNamespaceFolder.schema.mof , ensure should be a key

**Comment by PlagueHO** [comment]
Awesome! Thanks @TravisEz13 for looking at this for me :+1: 

Regarding making Ensure a key; wouldn't this then mean that a single namespace (or any of the other resources) could be made both Present and Absent in the same config? For example, it would allow a config like this:
```powershell
        xDFSNamespaceFolder DFSNamespaceFolder_Domain_Finance_Present
        {
            Path                 = '\\contoso.com\departments\finance' 
            TargetPath           = '\\fs_3\Finance'
            Ensure               = 'present'
            PsDscRunAsCredential = $Credential
        } # End of xDFSNamespaceFolder Resource
        xDFSNamespaceFolder DFSNamespaceFolder_Domain_Finance_Absent
        {
            Path                 = '\\contoso.com\departments\finance' 
            TargetPath           = '\\fs_3\Finance'
            Ensure               = 'absent'
            PsDscRunAsCredential = $Credential
        } # End of xDFSNamespaceFolder Resource
```

This would then constantly add and remove this DFS folder over and over - which would be quite bad. I could be quite wrong though.

I'll get the other stuff done ASAP. I'll also change this to v3.0.0.0 so that it is clear that there are some structural changes to the resources.

**Comment by TravisEz13** [comment]
@PlagueHO No, you are correct, ensure should not be a key...

**Comment by PlagueHO** [comment]
@TravisEz13 - I'll rename all "Rep" to "Replication". I think it'll be best if everything is the same (would be confusing if some things were Rep and others Replication).

I'll get this change made this week! Thanks again for reviewing this :+1:

**Comment by TravisEz13** [comment]
Sounds good

**Comment by PlagueHO** [comment]
@TravisEz13 - All changes finished now. Hopefully ready to go.

Cheers

**Comment by TravisEz13** [comment]
There are some passwords hard coded in the samples otherwise look pretty good to me.

**Comment by PlagueHO** [comment]
Good call - I'll change the passwords in the samples to come in via parameters.

**Comment by PlagueHO** [comment]
@TravisEz13 - Done. All samples now use ```Read-Host``` and/or ```Get-Credential``` to read in the info. This eliminates the PSSA errors.

**Comment by TravisEz13** [comment]
@KarolKaczmarek This look good to me

**Comment by PlagueHO** [comment]
Cool. I can transfer this to PowerShell as soon as @KarolKaczmarek gives the OK. Thanks for reviewing this @TravisEz13

**Comment by KarolKaczmarek** [comment]
Thanks @PlagueHO 
You can go ahead and transfer it.

**Comment by PlagueHO** [comment]
@KarolKaczmarek  - thank you! @TravisEz13  - I've transferred it over to PowerShell now. Not sure if there is anything more I need to do here?

Once you've released a version of this as xDFS, I'll remove cDFS off PSGallery.

**Comment by PlagueHO** [comment]
@KarolKaczmarek, @TravisEz13 - I thought I had transferred this, but I hadn't - because I don't have rights to transfer to the PowerShell org:
![2016-05-10_10-24-58](https://cloud.githubusercontent.com/assets/7589164/15129988/8059bc72-1699-11e6-9e9d-3af7f2325711.png)

One solution is I could transfer the repo to one of you and you could then transfer it into the PowerShell org.

Here is a document covering transfers that I was using:

https://help.github.com/articles/transferring-a-repository/

**Comment by KarolKaczmarek** [comment]
Sure, feel free to transfer it to me and I'll move it to PS org

**Comment by PlagueHO** [comment]
@KarolKaczmarek - cool. Done. Thank you!

**Comment by KarolKaczmarek** [comment]
Thanks, I've transferred it to our org, onboarded to our appveyor and waffle.io accounts and added as a submodule to DscResources. There were small updates needed to psd1 file, but otherwise it was ready to publish, so it's here: http://www.powershellgallery.com/packages/xdfs/3.0.0.0 

Thanks for contributing and congrats on "surviving" our onboarding process :) I know it's not the easiest, but we try to keep the quality of contributions high, so once again thank you for doing this!

Let me know when you unpublish cDFS from PSGallery and we can close this issue.

**Comment by PlagueHO** [comment]
Awesome! Thanks @KarolKaczmarek . It is a pleasure contributing and really wasn't a difficult process. This was the smallest of my modules I'm onboarding with the PowerShell team, so I feel sorry for your reviewers (thanks @TravisEz13 :smile: ). The cFSRM module has twice the number of resources as this one.

cDFS has been unlisted from the Gallery now so I'll close this.

Cheers to you and your team :+1:

**Comment by Zuldan** [comment]
@PlagueHO, well done mate. Impressive stuff.

Now onto to next resource! ;-)

**Comment by PlagueHO** [comment]
Cheers @Zuldan :+1: cISCSI next perhaps?

**Comment by Zuldan** [comment]
@PlagueHO reading my mind :)
