### ISSUE TITLE
Submodules in this repo have not been updated in months

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/DscResources#92]
However this isnt actually correct as I believe that they have all been updated.

Could there be a daily/weekly update along the lines of 
```
git submodule foreach git pull origin master
```
that ensures that this repo can be pulled from with all the latest updates (if it was so required by an organisation)

**Comment by KarolKaczmarek** [comment]
Hi @kilasuit 
This is related to: https://github.com/PowerShell/DscResources/issues/31 

We are currently updating the submodules' pointers whenever we release Resource Kit (every few weeks), but I think I could schedule it to run weekly as you suggested.

**Comment by KarolKaczmarek** [comment]
Scheduled script to update submodules every Friday
