### ISSUE TITLE
We should have guidance on using Set-StrictMode -Version latest

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/DscResources#96]
I believe this should be the guidance and at least new modules it should be required.

**Comment by johlju** [comment]
Not sure about this one. I would rather see that this is the default of the support PowerShell version of the resource module. Is that the most relaxed, then so be it, then it's code for that PowerShell version. If we add this as a requirement then we must enforce this using common test as well. 
Using `Set-StrictMode -Version latest` this will most likely break resource modules. I suggest we leave this up to the maintainer of a resource module.

@kwirkykat @PlagueHO @NikCharlebois what are your thoughts on this?

**Comment by johlju** [comment]
Due to lack of response I will closing this as not fixed. If anyone thinks this is something we should have, then please comment and we reopen and discuss it further.
