### ISSUE TITLE
Most DSC Resources have no Release Notes in PSGallery

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/DscResources#97]
Not only is this a bad practise but this makes discoverability and understanding why there is a need to update more difficult to the end IT Admin.

So I Propose for all DSCResources linked from this Repo that release notes are enforced into the Upload into the PSGallery - otherwise what is the point in having the Property available in the first place?

**Comment by KarolKaczmarek** [comment]
The release notes are available in readme.md for each module, e.g.
https://github.com/powershell/xwebadministration/#versions
- Is this sufficient or would you need to have this available in the ReleaseNotes property as well? 
- Is the information we currently provide in readme.md something you would like to see in ReleaseNotes property?

We could certainly be adding release notes into the property as well, but would like to gather more feedback before implementing this.

**Comment by kilasuit** [comment]
Ideally it makes most sense for them to be in the release notes property as well. That way I could do this

```powershell
Find-Module <DSC Module Name> -AllVersions | Select-Object Version,ReleaseNotes
```
That gives me a quick overview that I can get without reaching out to the readme files and from a UX point of view is less hassle to work around and I can then look at individual Versions in more detail with the below

```powershell
Find-Module <DSC Module Name> -RequiredVersion <Version Number> | Select-Object -ExpandProperty ReleaseNotes
```

The question then becomes " Why shouldn't we be getting this information in this way?"

**Comment by KarolKaczmarek** [comment]
@kwirkykat could you update our publishing scripts to include release notes as well?

**Comment by kwirkykat** [comment]
Sure

**Comment by kwirkykat** [comment]
This is done. Release notes now go out when a module is released.

**Comment by kilasuit** [comment]
Awesome - Thanks :-)
