### ISSUE TITLE
Add a guideline that recommends against using Positional Parameters in cmdlets

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#98]
Using positional parameters instead of named parameters in most cases reduces code readability and is recommended against in most cases (e.g. https://blogs.technet.microsoft.com/heyscriptingguy/2012/04/22/the-problem-with-powershell-positional-parameters/).

I did not see a policy in the StyleGuidelines.md document against using positional parameters, but I think there should be one - e.g. don't use positional parameters (always use named parameters). PSScriptAnalyzer will also throw warnings against against this as well.

**Comment by tysonjhayes** [comment]
:+1: - Maybe add something to PSScriptAnalyzer as a warning or informational or something?

**Comment by PlagueHO** [comment]
That is a good idea. I know there is a PSSCriptAnalyzer informational rule for this already, but at the moment the meta.tests.ps1 is configured to only run Error rules.

**Comment by tysonjhayes** [comment]
I'd thought there was some proposal to have meta.tests.ps1 run to fail warnings as well? Could be mis-remembering something.

**Comment by PlagueHO** [comment]
Oh, you might well be right. I think I recall it being mentioned as well. Perhaps it is something worth logging?

Slightly off topic: I did a quick (well, it takes about 20 minutes) PSSCriptAnalyzer run with warning level output on the xNetworking repo to see what currently comes up and there are a lot of things showing up. We'll want to do a few tests on existing resource modules before going to far down that path.

**Comment by KarolKaczmarek** [comment]
The plan is to enable warnings for PSSA as well, so this will be covered, but we need to resolve them first as enabling now would cause most of test passes to fail. 

Regarding temporary solution, please add the rule to StyleGuidelines.md

**Comment by tysonjhayes** [comment]
I figured. :grin: Unfortunately I don't have WMF 5.0 on my normal workstation so I haven't had time to dive that far into PSScriptAnyalzer.

**Comment by kilasuit** [comment]
@tysonjhayes PSScriptAnalyzer is supported from v3 as from the latest release (in case you didn't know)

You can install from Github or you can install the PackageManagement modules - details are in this blog post http://bit.ly/PSPackManBlog which includes a 1 liner to actually install it - and then install from the Gallery.

**Comment by KarolKaczmarek** [comment]
True, that will also allow us to enable PSSA runs on all other repos where they are currently disabled without moving them to WMF5 test VMs

**Comment by tysonjhayes** [comment]
@kilasuit - I was aware we were workign on it, not that we'd released it. Thanks for the tip!

**Comment by kilasuit** [comment]
@tysonjhayes No Problem - luckily PSScriptAnalyzer is one of those Repos that I follow almost religiously because I believe that it is a key component to making the PowerShell EcoSystem Sustainable in future. That and Pester & all the DSCResources Repos

**Comment by PlagueHO** [comment]
@KarolKaczmarek - I'll submit a PR for the StyleGuidelines.md change.

Regarding the PSSA warning level change, should I open an issue so it can be discussed further? I've done a few tests on the xNetworking repo and running PSSA on warning level and there are definitely a number of tests that don't make sense to run against DSC resources.

**Comment by KarolKaczmarek** [comment]
@PlagueHO Sure, open issue and we can discuss it there. We may need to come up with specific set of rules we want to run across all DscResources as as you've noticed not all of them may make sense for us - please mention the ones you think we shouldn't run to get it started.

**Comment by PlagueHO** [comment]
@KarolKaczmarek - will do. I'll add it to the [DSCResources.Tests](https://github.com/PowerShell/DscResource.Tests) repo though as that is where the change will be made.

**Comment by kwirkykat** [comment]
Guideline to use named parameters instead of positional parameters has been included in the [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md#use-named-parameters-instead-of-positional-parameters) document. (And it's also still in the style guidelines as well.) The [PSSA rule severity list](https://github.com/PowerShell/DscResources/blob/master/PSSARuleSeverities.md) for the DSC Resource Kit has also now been posted.
